// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column } from 'metal-orm';

@Entity()
export class Abreviatura {
  /**
   * armazena abreviações que representam nomes completos ou informações mais longas, uma forma mais curta e eficiente de armazenar e acessar esses dados.
   */
  @Column(col.varchar(255))
  codigo?: string;

  /**
   * armazena os nomes completos que foram abreviados. Corresponde a um nome completo ou informação detalhada que foi encurtada por meio de uma abreviatura.
   */
  @Column(col.varchar(255))
  nome?: string;

  /**
   * ?
   */
  @Column(col.varchar(255))
  F3?: string;

}
