// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { Acervo } from './Acervo.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'acervo_destinatario_pa' })
export class AcervoDestinatarioPa {
  /**
   * Armazena um identificador único para cada registro na tabela.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Armazena um identificador ou código relacionado a destinatários de processos administrativos.
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  destinatario_pa_id!: number;

  /**
   * Identificador usado para associar informações sobre o destino de processos administrativos a registros na tabela.
   * @remarks References dbo.acervo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'acervo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  acervo_id!: number;

  @BelongsTo({ target: () => Usuario, foreignKey: 'destinatario_pa_id' })
  destinatarioPa?: Usuario;

  @BelongsTo({ target: () => Acervo, foreignKey: 'acervo_id' })
  acervo?: Acervo;

}
