// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, BelongsToReference, ManyToManyCollection } from 'metal-orm';
import { AcervoClassificacao } from './AcervoClassificacao';
import { AcervoDestinatarioPa } from './AcervoDestinatarioPa';
import { AcervoEquipeApoio } from './AcervoEquipeApoio';
import { AcervoMateria } from './AcervoMateria';
import { AcervoTema } from './AcervoTema';
import { Classificacao } from './Classificacao';
import { Equipe } from './Equipe';
import { Especializada } from './Especializada';
import { FilaCircular } from './FilaCircular';
import { HistoricoDistribuicaoAcervo } from './HistoricoDistribuicaoAcervo';
import { MapeamentoAcervoSicaj } from './MapeamentoAcervoSicaj';
import { Materia } from './Materia';
import { Pessoa } from './Pessoa';
import { ProcessoAdministrativo } from './ProcessoAdministrativo';
import { RaizCnpjAcervo } from './RaizCnpjAcervo';
import { Tema } from './Tema';
import { TipoAcervo } from './TipoAcervo';
import { TipoDivisaoCargaTrabalho } from './TipoDivisaoCargaTrabalho';
import { TipoMigracaoAcervo } from './TipoMigracaoAcervo';
import { Usuario } from './Usuario';

@Entity({ tableName: 'acervo' })
export class Acervo {
  /**
   * Identificador único do acervo. Usado para identificar e diferenciar cada entrada na tabela de forma exclusiva.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Armazena o nome ou título do acervo em si, fornecendo uma identificação do acervo.
   */
  @Column(col.notNull(col.varchar(125)))
  nome!: string;

  /**
   * Identificador único da equipe responsável pelo acervo. Usado para identificar e diferenciar cada entrada na tabela de forma exclusiva.
   * @remarks References dbo.equipe.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'equipe', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  equipe_responsavel_id?: number;

  /**
   * Tipo de divisão de carga de trabalho: Padrão.
   * @remarks References dbo.tipo_divisao_carga_trabalho.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tipo_divisao_carga_trabalho', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_divisao_carga_trabalho_id?: number;

  /**
   * identificador único que está relacionando o procurador titular associado a um registro específico na tabela.
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  procurador_titular_id!: number;

  /**
   * Usada para vincular os itens a uma categoria ou área de especializada dentro do acervo.
   * @remarks References dbo.especializada.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'especializada', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  especializada_id!: number;

  /**
   * Coluna usada para classificar os itens do acervo de acordo com suas diferentes categorias ou tipos. Ex: Acervo da Chefia/Assistente, Especializado, Núcleo e Regular.
   * @remarks References dbo.tipo_acervo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'tipo_acervo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_acervo_id!: number;

  /**
   * Armazena um identificador ou código que está relacionado a uma fila circular específica no contexto do acervo.
   * @remarks References dbo.fila_circular.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'fila_circular', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  fila_circular_id?: number;

  /**
   * Identificador único que informa o tipo de migração do acervo.
   * @remarks References dbo.tipo_migracao_acervo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tipo_migracao_acervo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_migracao_acervo_id?: number;

  /**
   * Informa se está em rotina.
   */
  @Column(col.notNull(col.boolean()))
  rotina_sob_demanda!: boolean;

  /**
   * armazena informações sobre o status de ativação ou disponibilidade do acervo.
   * @defaultValue ((1))
   */
  @Column(col.defaultRaw(col.notNull(col.int()), '((1))'))
  ativo!: number;

  /**
   * Armazena a data e hora da última modificação ou atualização de um registro específico no banco de dados. Útil para rastrear quando um registro foi alterado pela última vez.
   */
  @Column(col.datetime<Date>())
  modified?: Date;

  /**
   * Armazena a data e hora em que o registro específico foi criado ou adicionado à tabela.
   */
  @Column(col.datetime<Date>())
  created?: Date;

  @BelongsToMany({ target: () => Equipe, pivotTable: () => AcervoEquipeApoio, pivotForeignKeyToRoot: 'acervo_id', pivotForeignKeyToTarget: 'equipe_apoio_id' })
  equipes!: ManyToManyCollection<Equipe>;

  @BelongsToMany({ target: () => Usuario, pivotTable: () => AcervoDestinatarioPa, pivotForeignKeyToRoot: 'acervo_id', pivotForeignKeyToTarget: 'destinatario_pa_id' })
  usuarios!: ManyToManyCollection<Usuario>;

  @BelongsToMany({ target: () => Classificacao, pivotTable: () => AcervoClassificacao, pivotForeignKeyToRoot: 'acervo_id', pivotForeignKeyToTarget: 'classificacao_id' })
  classificacaos!: ManyToManyCollection<Classificacao>;

  @BelongsToMany({ target: () => Materia, pivotTable: () => AcervoMateria, pivotForeignKeyToRoot: 'acervo_id', pivotForeignKeyToTarget: 'materia_id' })
  materias!: ManyToManyCollection<Materia>;

  @BelongsToMany({ target: () => Tema, pivotTable: () => AcervoTema, pivotForeignKeyToRoot: 'acervo_id', pivotForeignKeyToTarget: 'tema_id' })
  temas!: ManyToManyCollection<Tema>;

  @BelongsToMany({ target: () => Pessoa, pivotTable: () => RaizCnpjAcervo, pivotForeignKeyToRoot: 'acervo_id', pivotForeignKeyToTarget: 'matriz_id' })
  pessoas!: ManyToManyCollection<Pessoa>;

  @HasMany({ target: () => ProcessoAdministrativo, foreignKey: 'acervo_id' })
  processoAdministrativos!: HasManyCollection<ProcessoAdministrativo>;

  @HasMany({ target: () => HistoricoDistribuicaoAcervo, foreignKey: 'acervo_id' })
  historicoDistribuicaoAcervos!: HasManyCollection<HistoricoDistribuicaoAcervo>;

  @HasMany({ target: () => MapeamentoAcervoSicaj, foreignKey: 'acervo_id' })
  mapeamentoAcervoSicajs!: HasManyCollection<MapeamentoAcervoSicaj>;

  @BelongsTo({ target: () => Equipe, foreignKey: 'equipe_responsavel_id' })
  equipeResponsavel!: BelongsToReference<Equipe>;

  @BelongsTo({ target: () => TipoDivisaoCargaTrabalho, foreignKey: 'tipo_divisao_carga_trabalho_id' })
  tipoDivisaoCargaTrabalho!: BelongsToReference<TipoDivisaoCargaTrabalho>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'procurador_titular_id' })
  procuradorTitular!: BelongsToReference<Usuario>;

  @BelongsTo({ target: () => Especializada, foreignKey: 'especializada_id' })
  especializada!: BelongsToReference<Especializada>;

  @BelongsTo({ target: () => TipoAcervo, foreignKey: 'tipo_acervo_id' })
  tipoAcervo!: BelongsToReference<TipoAcervo>;

  @BelongsTo({ target: () => FilaCircular, foreignKey: 'fila_circular_id' })
  filaCircular!: BelongsToReference<FilaCircular>;

  @BelongsTo({ target: () => TipoMigracaoAcervo, foreignKey: 'tipo_migracao_acervo_id' })
  tipoMigracaoAcervo!: BelongsToReference<TipoMigracaoAcervo>;

}
