// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { AcessoRestritoFuncionalidade } from './AcessoRestritoFuncionalidade.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'acesso_restrito_funcionalidade_usuario' })
export class AcessoRestritoFuncionalidadeUsuario {
  /**
   * Identificador único da relação das tabelas: acesso restrito, funcionalidade e usuario.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Usuário que será autorizado.
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id!: number;

  /**
   * Funcionalidade que é autorizada o acesso pelo usuário vinculado.
   * @remarks References dbo.acesso_restrito_funcionalidade.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'acesso_restrito_funcionalidade', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  acesso_restrito_funcionalidade_id!: number;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario?: Usuario;

  @BelongsTo({ target: () => AcessoRestritoFuncionalidade, foreignKey: 'acesso_restrito_funcionalidade_id' })
  acessoRestritoFuncionalidade?: AcessoRestritoFuncionalidade;

}
