// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsToMany, HasManyCollection, ManyToManyCollection } from 'metal-orm';
import { AcessoRestritoFuncionalidadePerfil } from './AcessoRestritoFuncionalidadePerfil.js';
import { AcessoRestritoFuncionalidadeUsuario } from './AcessoRestritoFuncionalidadeUsuario.js';
import { Perfil } from './Perfil.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'acesso_restrito_funcionalidade' })
export class AcessoRestritoFuncionalidade {
  /**
   * Armazena um identificador único para cada registro na tabela.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * armazena o nome ou identificador de um controlador ou funcionalidade dentro do sistema.
   */
  @Column(col.notNull(col.text()))
  controller_funcionalidade!: string;

  /**
   * Armazena um identificador ou código que está relacionado a um objeto ou funcionalidade específica no sistema.
   */
  @Column(col.text())
  identificador_objeto?: string;

  /**
   * Armazena o nome ou identificador de uma ação ou função específica dentro de um controlador.
   */
  @Column(col.text())
  action_funcionalidade?: string;

  /**
   * Armazena uma descrição ou texto que fornece informações detalhadas sobre a funcionalidade ou ação associada.
   */
  @Column(col.notNull(col.text()))
  descricao_funcionalidade!: string;

  @BelongsToMany({ target: () => Perfil, pivotTable: () => AcessoRestritoFuncionalidadePerfil, pivotForeignKeyToRoot: 'acesso_restrito_funcionalidade_id', pivotForeignKeyToTarget: 'perfil_id' })
  perfis!: ManyToManyCollection<Perfil>;

  @BelongsToMany({ target: () => Usuario, pivotTable: () => AcessoRestritoFuncionalidadeUsuario, pivotForeignKeyToRoot: 'acesso_restrito_funcionalidade_id', pivotForeignKeyToTarget: 'usuario_id' })
  usuarios!: ManyToManyCollection<Usuario>;

  @HasMany({ target: () => AcessoRestritoFuncionalidadePerfil, foreignKey: 'acesso_restrito_funcionalidade_id' })
  acessosRestritosFuncionalidadesPerfis!: HasManyCollection<AcessoRestritoFuncionalidadePerfil>;

  @HasMany({ target: () => AcessoRestritoFuncionalidadeUsuario, foreignKey: 'acesso_restrito_funcionalidade_id' })
  acessosRestritosFuncionalidadesUsuarios!: HasManyCollection<AcessoRestritoFuncionalidadeUsuario>;

}
