// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { ProcessoJudicial } from './ProcessoJudicial.js';

@Entity({ tableName: 'acompanhamento' })
export class Acompanhamento {
  /**
   * Armazena um identificador único ou código específico para cada registro na tabela.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Registra o número do processo administrativo relacionado.
   */
  @Column(col.notNull(col.varchar(20)))
  numero_processo_administrativo!: string;

  /**
   * Registra o código ou identificador único do processo judicial relacionado.
   * @remarks References dbo.processo_judicial.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'processo_judicial', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_judicial_id!: number;

  @BelongsTo({ target: () => ProcessoJudicial, foreignKey: 'processo_judicial_id' })
  processoJudicial?: ProcessoJudicial;

}
