// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { AfastamentoPessoa } from './AfastamentoPessoa.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'afastamento_pessoa_usuario' })
export class AfastamentoPessoaUsuario {
  /**
   * Identificador único da relação da tabela de afastamento e usuário.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador único do afastamento.
   * @remarks References dbo.afastamento_pessoa.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'afastamento_pessoa', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  afastamento_pessoa_id!: number;

  /**
   * Usuário em relação ao afastamento.
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id!: number;

  /**
   * Infoma se usa equipe de acervo substituta.
   */
  @Column(col.boolean())
  usa_equipe_acervo_substituto?: boolean;

  /**
   * Final do código pa.
   */
  @Column(col.text())
  final_codigo_pa?: string;

  @BelongsTo({ target: () => AfastamentoPessoa, foreignKey: 'afastamento_pessoa_id' })
  afastamentoPessoa?: AfastamentoPessoa;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario?: Usuario;

}
