// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey } from 'metal-orm';

@Entity({ tableName: 'arquivo' })
export class Arquivo {
  /**
   * Armazena um identificador único ou código relacionado a um arquivo específico na tabela.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Armazena um código ou identificador único da caixa de entrada que será vinculada ao arquivo.
   */
  @Column(col.notNull(col.int()))
  caixa_entrada_id!: number;

  /**
   * Informa a data de retorno programada do arquivo.
   */
  @Column(col.datetime<Date>())
  data_retorno_programado?: Date;

  /**
   * Informa a data de arquivamento do arquivo.
   */
  @Column(col.datetime<Date>())
  data_arquivamento?: Date;

}
