// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { AssuntoLocal } from './AssuntoLocal';
import { ProcessoJudicial } from './ProcessoJudicial';

@Entity({ tableName: 'assunto_processo_judicial' })
export class AssuntoProcessoJudicial {
  /**
   * Identificador único da relação da tabela de assunto com a tabela de processo judicial.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador do assunto local.
   * @remarks References dbo.assunto_local.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'assunto_local', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  assunto_local_id?: number;

  /**
   * Identificador do processo judicial vinculado.
   * @remarks References dbo.processo_judicial.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'processo_judicial', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_judicial_id?: number;

  @BelongsTo({ target: () => AssuntoLocal, foreignKey: 'assunto_local_id' })
  assuntoLocal!: BelongsToReference<AssuntoLocal>;

  @BelongsTo({ target: () => ProcessoJudicial, foreignKey: 'processo_judicial_id' })
  processoJudicial!: BelongsToReference<ProcessoJudicial>;

}
