// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsToMany, HasManyCollection, ManyToManyCollection } from 'metal-orm';
import { AvisoPendenteOutroParametro } from './AvisoPendenteOutroParametro';
import { Comunicacao } from './Comunicacao';
import { ConsumoTeorAvisoErro } from './ConsumoTeorAvisoErro';
import { InstantaneoAvisoPendente } from './InstantaneoAvisoPendente';
import { RegistroEnvioComunicacao } from './RegistroEnvioComunicacao';

@Entity({ tableName: 'aviso_pendente' })
export class AvisoPendente {
  /**
   * Identificador único.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador do aviso.
   */
  @Column(col.varchar(30))
  id_aviso?: string;

  /**
   * Tribunal fonte.
   */
  @Column(col.varchar(10))
  fonte?: string;

  /**
   * Identificador do destinatário.
   */
  @Column(col.int())
  destinatario_id?: number;

  /**
   * Identificador do processo relacionado.
   */
  @Column(col.notNull(col.int()))
  processo_id!: number;

  /**
   * Informa a data de disponibilização.
   */
  @Column(col.datetime<Date>())
  data_disponibilizacao?: Date;

  /**
   * Informa o tipo de comunicação.
   */
  @Column(col.varchar(3))
  tipo_comunicacao_id?: string;

  /**
   * Informa se foi enviado com sucesso.
   */
  @Column(col.boolean())
  sucesso?: boolean;

  /**
   * Mensagem retornada.
   */
  @Column(col.text())
  mensagem?: string;

  /**
   * Data em que foi consultado.
   */
  @Column(col.datetime<Date>())
  data_consultado?: Date;

  /**
   * Informa se foi baixado.
   */
  @Column(col.boolean())
  baixado?: boolean;

  @Column(col.varchar(3))
  origem?: string;

  @BelongsToMany({ target: () => Comunicacao, pivotTable: () => RegistroEnvioComunicacao, pivotForeignKeyToRoot: 'aviso_pendente_id', pivotForeignKeyToTarget: 'comunicacao_id' })
  comunicacaos!: ManyToManyCollection<Comunicacao>;

  @HasMany({ target: () => ConsumoTeorAvisoErro, foreignKey: 'aviso_pendente_id' })
  consumoTeorAvisoErros!: HasManyCollection<ConsumoTeorAvisoErro>;

  @HasMany({ target: () => InstantaneoAvisoPendente, foreignKey: 'aviso_pendente_id' })
  instantaneoAvisoPendentes!: HasManyCollection<InstantaneoAvisoPendente>;

  @HasMany({ target: () => AvisoPendenteOutroParametro, foreignKey: 'aviso_pendente_id' })
  avisoPendenteOutroParametros!: HasManyCollection<AvisoPendenteOutroParametro>;

}
