// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, BelongsToReference, ManyToManyCollection } from 'metal-orm';
import { Modelo } from './Modelo';

@Entity({ tableName: 'capitulo' })
export class Capitulo {
  /**
   * Identificador único da tabela.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador do modelo.
   * @remarks References dbo.modelo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'modelo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  modelo_id!: number;

  /**
   * Informa o título do capítulo.
   */
  @Column(col.notNull(col.varchar(255)))
  titulo!: string;

  /**
   * html.
   */
  @Column(col.notNull(col.text()))
  html!: string;

  /**
   * Informa um id relacionado
   * @remarks References dbo.capitulo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'capitulo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  parent_id?: number;

  /**
   * Valor a esquerda.
   */
  @Column(col.int())
  lft?: number;

  /**
   * Valor a direita.
   */
  @Column(col.int())
  rght?: number;

  /**
   * @defaultValue (getdate())
   */
  @Column(col.defaultRaw(col.datetime<Date>(), '(getdate())'))
  created?: Date;

  @Column(col.datetime<Date>())
  modified?: Date;

  @BelongsToMany({ target: () => Modelo, pivotTable: () => Capitulo, pivotForeignKeyToRoot: 'parent_id', pivotForeignKeyToTarget: 'modelo_id' })
  modelos!: ManyToManyCollection<Modelo>;

  @BelongsTo({ target: () => Modelo, foreignKey: 'modelo_id' })
  modelo!: BelongsToReference<Modelo>;

  @BelongsTo({ target: () => Capitulo, foreignKey: 'parent_id' })
  parent!: BelongsToReference<Capitulo>;

  @HasMany({ target: () => Capitulo, foreignKey: 'parent_id' })
  capitulos!: HasManyCollection<Capitulo>;

}
