// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { PastaCaixaEntrada } from './PastaCaixaEntrada.js';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';
import { RegistroTramitacao } from './RegistroTramitacao.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'carga' })
export class Carga {
  /**
   * Identificador único.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador que informa o registro de tramitação.
   * @remarks References dbo.registro_tramitacao.id (on delete CASCADE, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'registro_tramitacao', column: 'id', onDelete: 'CASCADE', onUpdate: 'NO ACTION' }))
  registro_tramitacao_id!: number;

  /**
   * Usuário relacionado.
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id!: number;

  /**
   * Identificador que informa o processo administrativo vinculado.
   * @remarks References dbo.processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_administrativo_id?: number;

  /**
   * Informa se foi lido.
   */
  @Column(col.boolean())
  lido?: boolean;

  /**
   * Identificador da pasta onde localiza-se a carga.
   * @remarks References dbo.pasta_caixa_entrada.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'pasta_caixa_entrada', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  pasta_id?: number;

  @BelongsTo({ target: () => RegistroTramitacao, foreignKey: 'registro_tramitacao_id' })
  registroTramitacao!: BelongsToReference<RegistroTramitacao>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario!: BelongsToReference<Usuario>;

  @BelongsTo({ target: () => ProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  processoAdministrativo!: BelongsToReference<ProcessoAdministrativo>;

  @BelongsTo({ target: () => PastaCaixaEntrada, foreignKey: 'pasta_id' })
  pasta!: BelongsToReference<PastaCaixaEntrada>;

}
