// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { ProcessoJudicial } from './ProcessoJudicial';

@Entity({ tableName: 'cda' })
export class Cda {
  /**
   * Armazena um identificador único para cada registro na tabela.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Armazena os números das certidões de dívida ativa, que são gerados a partir de integrações com o Tribunal de Justiça do Rio de Janeiro (TJRJ) ou o Processo Judicial Eletrônico (PJE)
   */
  @Column(col.notNull(col.varchar(40)))
  numero!: string;

  /**
   * Armazena números ou códigos de controle associados às certidões de dívida ativa.
   */
  @Column(col.varchar(20))
  numero_controle?: string;

  /**
   * Armazena o montante financeiro associado a cada certidão de dívida ativa.
   */
  @Column(col.decimal(18, 2))
  valor?: number;

  /**
   * Descreve o tipo ou natureza do valor associado a cada certidão de dívida ativa.
   */
  @Column(col.varchar(20))
  tipo_valor?: string;

  /**
   * Armazena a data em que a dívida registrada na certidão de dívida ativa foi apurada ou calculada.
   */
  @Column(col.datetime<Date>())
  data_apuracao?: Date;

  /**
   * Armazena a data em que a dívida registrada na certidão de dívida ativa prescreverá ou se tornará inválida legalmente se não for cobrada dentro de um período específico.
   */
  @Column(col.datetime<Date>())
  data_prescricao?: Date;

  /**
   * Armazena informações sobre o valor ou montante de crédito tributário associado a cada certidão de dívida ativa.
   */
  @Column(col.boolean())
  credito_tributario?: boolean;

  /**
   * Armazena um identificador ou código que está relacionado a um processo judicial específico associado à certidão de dívida ativa.
   * @remarks References dbo.processo_judicial.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'processo_judicial', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_judicial_id!: number;

  @BelongsTo({ target: () => ProcessoJudicial, foreignKey: 'processo_judicial_id' })
  processoJudicial!: BelongsToReference<ProcessoJudicial>;

}
