// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsToMany, HasManyCollection, ManyToManyCollection } from 'metal-orm';
import { Classificacao } from './Classificacao.js';
import { ClassificacaoRecorrencia } from './ClassificacaoRecorrencia.js';

@Entity({ tableName: 'classificacao_relevancia' })
export class ClassificacaoRelevancia {
  /**
   * Identificador único.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Informa o nome dado à classificação de relevância: Comum, Estratégico ou Prioritário.
   */
  @Column(col.notNull(col.varchar(63)))
  nome!: string;

  @BelongsToMany({ target: () => ClassificacaoRecorrencia, pivotTable: () => Classificacao, pivotForeignKeyToRoot: 'classificacao_relevancia_id', pivotForeignKeyToTarget: 'classificacao_recorrencia_id' })
  classificacoesRecorrencia!: ManyToManyCollection<ClassificacaoRecorrencia>;

  @HasMany({ target: () => Classificacao, foreignKey: 'classificacao_relevancia_id' })
  classificacoes!: HasManyCollection<Classificacao>;

}
