// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, HasManyCollection } from 'metal-orm';
import { MniTribunal } from './MniTribunal.js';
import { ProcessoJudicial } from './ProcessoJudicial.js';

@Entity({ tableName: 'competencia' })
export class Competencia {
  /**
   * Identificador único.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Informa o identificador do local do tribunal.
   */
  @Column(col.int())
  id_local_tribunal?: number;

  /**
   * Informa o tribunal vinculado.
   * @remarks References dbo.mni_tribunal.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'mni_tribunal', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tribunal_id?: number;

  /**
   * Breve descrição.
   */
  @Column(col.varchar(500))
  descricao?: string;

  @HasMany({ target: () => ProcessoJudicial, foreignKey: 'competencia_id' })
  processosJudicial!: HasManyCollection<ProcessoJudicial>;

  @BelongsTo({ target: () => MniTribunal, foreignKey: 'tribunal_id' })
  tribunal?: MniTribunal;

}
