// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey } from 'metal-orm';

@Entity({ tableName: 'complemento_movimentacao_judicial' })
export class ComplementoMovimentacaoJudicial {
  /**
   * Identificador único.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Texto explicativo do complemento.
   */
  @Column(col.text())
  texto?: string;

  /**
   * Identificador único da movimentação judicial.
   */
  @Column(col.notNull(col.int()))
  movimentacao_judicial_id!: number;

}
