// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { Comunicacao } from './Comunicacao.js';

@Entity({ tableName: 'comunicacao_outro_parametro' })
export class ComunicacaoOutroParametro {
  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  @Column(col.varchar(1000))
  nome?: string;

  @Column(col.varchar(5000))
  valor?: string;

  /**
   * @remarks References dbo.comunicacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'comunicacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  comunicacao_id!: number;

  @BelongsTo({ target: () => Comunicacao, foreignKey: 'comunicacao_id' })
  comunicacao!: BelongsToReference<Comunicacao>;

}
