// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { AvisoPendente } from './AvisoPendente';

@Entity({ tableName: 'consumo_teor_aviso_erro' })
export class ConsumoTeorAvisoErro {
  /**
   * Identificador único.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Mensagem retornada.
   */
  @Column(col.notNull(col.text()))
  mensagem!: string;

  /**
   * Informa a data em que ocorreu.
   */
  @Column(col.notNull(col.datetime<Date>()))
  data_hora!: Date;

  /**
   * Erro retornado.
   */
  @Column(col.text())
  throwable_json?: string;

  /**
   * Identificador único do aviso pendente.
   * @remarks References dbo.aviso_pendente.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'aviso_pendente', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  aviso_pendente_id?: number;

  @BelongsTo({ target: () => AvisoPendente, foreignKey: 'aviso_pendente_id' })
  avisoPendente!: BelongsToReference<AvisoPendente>;

}
