// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, BelongsToReference, ManyToManyCollection } from 'metal-orm';
import { CorreicaoQuesito } from './CorreicaoQuesito';
import { Quesito } from './Quesito';
import { SorteioCorreicao } from './SorteioCorreicao';
import { Usuario } from './Usuario';

@Entity({ tableName: 'correicao' })
export class Correicao {
  /**
   * Identificador único.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador que informa o usuário vinculado à correição.
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id!: number;

  /**
   * Identificador que informa o corregedor.\n???? vinculado em que sentido? É o log de quem cria a correição no sistema?
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  corregedor_id?: number;

  /**
   * Nome da correição.
   */
  @Column(col.unique(col.notNull(col.varchar(255))))
  nome!: string;

  /**
   * Flag que define se a correição é extraordinária  (1) ou não (0)\nA extraordinária possui caráter excepcional, é feita “de surpresa”
   * @defaultValue ((0))
   */
  @Column(col.defaultRaw(col.notNull(col.boolean()), '((0))'))
  extraordinaria!: boolean;

  /**
   * Informa a data de início da correição.
   */
  @Column(col.date<Date>())
  data_inicio?: Date;

  /**
   * Data final da correição.
   */
  @Column(col.date<Date>())
  data_fim?: Date;

  /**
   * Data em que a correição foi criada.
   * @defaultValue (getdate())
   */
  @Column(col.defaultRaw(col.notNull(col.datetime<Date>()), '(getdate())'))
  created!: Date;

  /**
   * Data em que a correição foi modificada.
   * @defaultValue (getdate())
   */
  @Column(col.defaultRaw(col.notNull(col.datetime<Date>()), '(getdate())'))
  modified!: Date;

  @BelongsToMany({ target: () => Quesito, pivotTable: () => CorreicaoQuesito, pivotForeignKeyToRoot: 'correicao_id', pivotForeignKeyToTarget: 'quesito_id' })
  quesitos!: ManyToManyCollection<Quesito>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario!: BelongsToReference<Usuario>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'corregedor_id' })
  corregedor!: BelongsToReference<Usuario>;

  @HasMany({ target: () => SorteioCorreicao, foreignKey: 'correicao_id' })
  sorteioCorreicaos!: HasManyCollection<SorteioCorreicao>;

  @HasMany({ target: () => CorreicaoQuesito, foreignKey: 'correicao_id' })
  correicaoQuesitos!: HasManyCollection<CorreicaoQuesito>;

}
