// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { Comunicacao } from './Comunicacao.js';
import { InstanciaMniTribunal } from './InstanciaMniTribunal.js';
import { ProcessoJudicial } from './ProcessoJudicial.js';
import { TipoDecisao } from './TipoDecisao.js';
import { TipoFaseJudicial } from './TipoFaseJudicial.js';

@Entity({ tableName: 'decisao_judicial' })
export class DecisaoJudicial {
  /**
   * Identificador único.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador que informa o tipo da fase judicial.
   * @remarks References dbo.tipo_fase_judicial.id (on delete NO ACTION, on update CASCADE)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'tipo_fase_judicial', column: 'id', onDelete: 'NO ACTION', onUpdate: 'CASCADE' }))
  tipo_fase_judicial_id!: number;

  /**
   * Identificador que informa o processo judicial vinculado.
   * @remarks References dbo.processo_judicial.id (on delete NO ACTION, on update CASCADE)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'processo_judicial', column: 'id', onDelete: 'NO ACTION', onUpdate: 'CASCADE' }))
  processo_judicial_id!: number;

  /**
   * Identificador que informa a instância do mni no tribunal.
   * @remarks References dbo.instancia_mni_tribunal.id (on delete NO ACTION, on update CASCADE)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'instancia_mni_tribunal', column: 'id', onDelete: 'NO ACTION', onUpdate: 'CASCADE' }))
  instancia_mni_tribunal_id!: number;

  /**
   * Identificador que informa qual o tipo de decisão.
   * @remarks References dbo.tipo_decisao.id (on delete NO ACTION, on update CASCADE)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'tipo_decisao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'CASCADE' }))
  tipo_decisao_id!: number;

  /**
   * Data da decisão judicial.
   */
  @Column(col.notNull(col.date<Date>()))
  data_decisao!: Date;

  /**
   * @remarks References dbo.comunicacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'comunicacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  comunicacao_id?: number;

  @BelongsTo({ target: () => TipoFaseJudicial, foreignKey: 'tipo_fase_judicial_id' })
  tipoFaseJudicial!: BelongsToReference<TipoFaseJudicial>;

  @BelongsTo({ target: () => ProcessoJudicial, foreignKey: 'processo_judicial_id' })
  processoJudicial!: BelongsToReference<ProcessoJudicial>;

  @BelongsTo({ target: () => InstanciaMniTribunal, foreignKey: 'instancia_mni_tribunal_id' })
  instanciaMniTribunal!: BelongsToReference<InstanciaMniTribunal>;

  @BelongsTo({ target: () => TipoDecisao, foreignKey: 'tipo_decisao_id' })
  tipoDecisao!: BelongsToReference<TipoDecisao>;

  @BelongsTo({ target: () => Comunicacao, foreignKey: 'comunicacao_id' })
  comunicacao!: BelongsToReference<Comunicacao>;

}
