// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { Pessoa } from './Pessoa.js';
import { TipoDocumentoPessoa } from './TipoDocumentoPessoa.js';

@Entity({ tableName: 'documento_pessoa' })
export class DocumentoPessoa {
  /**
   * Identificador único.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador que informa a pessoa vinculada.
   * @remarks References dbo.pessoa.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'pessoa', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  pessoa_id?: number;

  /**
   * Código do documento.
   */
  @Column(col.text())
  codigo_documento?: string;

  /**
   * Órgão emissor do documento.
   */
  @Column(col.text())
  emissor_documento?: string;

  /**
   * Nome da pessoa.
   */
  @Column(col.text())
  nome?: string;

  /**
   * Identificador que informa o tipo de documento.
   * @remarks References dbo.tipo_documento_pessoa.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.varchar(10), { table: 'tipo_documento_pessoa', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_documento_pessoa_id?: string;

  @BelongsTo({ target: () => Pessoa, foreignKey: 'pessoa_id' })
  pessoa?: Pessoa;

  @BelongsTo({ target: () => TipoDocumentoPessoa, foreignKey: 'tipo_documento_pessoa_id' })
  tipoDocumentoPessoa?: TipoDocumentoPessoa;

}
