// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey } from 'metal-orm';

@Entity({ tableName: 'documento_movimentacao_judicial' })
export class DocumentoMovimentacaoJudicial {
  /**
   * Identificador único.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador que informa a movimentação judicial vinculada.
   */
  @Column(col.notNull(col.int()))
  movimentacao_judicial_id!: number;

  /**
   * Identificador que informa o documento vinculado.
   */
  @Column(col.text())
  documento_id?: string;

}
