// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, HasManyCollection, BelongsToReference } from 'metal-orm';
import { DocumentoComunicacao } from './DocumentoComunicacao.js';
import { DocumentoProcessoAdministrativoAcordo } from './DocumentoProcessoAdministrativoAcordo.js';
import { DocumentoProtocolizacao } from './DocumentoProtocolizacao.js';
import { DocumentoRascunho } from './DocumentoRascunho.js';
import { Manifestacao } from './Manifestacao.js';
import { ModeloFormularioProcessoAdministrativo } from './ModeloFormularioProcessoAdministrativo.js';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';
import { Protocolizacao } from './Protocolizacao.js';
import { ProvidenciaJuridica } from './ProvidenciaJuridica.js';
import { TipoDocumento } from './TipoDocumento.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'documento_processo_administrativo' })
export class DocumentoProcessoAdministrativo {
  /**
   * Identificador único.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Nome do documento.
   */
  @Column(col.text())
  nome?: string;

  /**
   * Binário do documento.
   */
  @Column(col.blob())
  binario?: Buffer;

  /**
   * Mimetype do documento.
   */
  @Column(col.varchar(50))
  mimetype?: string;

  /**
   * Breve descrição do documento.
   */
  @Column(col.text())
  descricao?: string;

  /**
   * Identificador do processo administrativo vinculado ao documento.
   * @remarks References dbo.processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_administrativo_id!: number;

  /**
   * informa o documento pai.
   * @remarks References dbo.documento_processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'documento_processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  parent_id?: number;

  /**
   * Armazena a data de criação/inclusão do documento.
   * @defaultValue (getdate())
   */
  @Column(col.defaultRaw(col.datetime<Date>(), '(getdate())'))
  data_inclusao?: Date;

  /**
   * Informa a ordem do documento.
   */
  @Column(col.int())
  ordem?: number;

  /**
   * Identificador do usuário vinculado ao documento.
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id?: number;

  /**
   * Identificador que informa qual o tipo de documento.
   * @remarks References dbo.tipo_documento.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tipo_documento', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_documento_id?: number;

  /**
   * Informa se permite alteração.
   */
  @Column(col.boolean())
  permite_alteracao?: boolean;

  /**
   * Informa se documento é rascunho.
   */
  @Column(col.boolean())
  rascunho?: boolean;

  /**
   * Caso seja rascunho, informa o identificador.
   * @remarks References dbo.documento_rascunho.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'documento_rascunho', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  documento_rascunho_id?: number;

  /**
   * Informa se documento foi protocolizado.
   */
  @Column(col.boolean())
  protocolizado?: boolean;

  /**
   * Identificador da providência jurídica relacionada.
   * @remarks References dbo.providencia_juridica.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'providencia_juridica', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  providencia_juridica_id?: number;

  /**
   * Id da comunicação
   * @remarks References dbo.documento_comunicacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'documento_comunicacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  documento_comunicacao_id?: number;

  /**
   * Informa qual a extensão do documento, ex: .pdf, .doc;
   * @defaultValue (\'.pdf\')
   */
  @Column(col.defaultRaw(col.varchar(5), '(\'.pdf\')'))
  extensao?: string;

  /**
   * Informa se documento é original.
   */
  @Column(col.boolean())
  confere_original?: boolean;

  /**
   * Informa se é versão em PDF.
   */
  @Column(col.boolean())
  versao_pdf?: boolean;

  /**
   * Informa se documento está assinado.
   */
  @Column(col.boolean())
  assinado?: boolean;

  @Column(col.int())
  lft?: number;

  @Column(col.int())
  rght?: number;

  @HasMany({ target: () => DocumentoProcessoAdministrativoAcordo, foreignKey: 'documento_processo_administrativo_id' })
  documentosProcessosAdministrativosAcordos!: HasManyCollection<DocumentoProcessoAdministrativoAcordo>;

  @HasMany({ target: () => ModeloFormularioProcessoAdministrativo, foreignKey: 'documento_processo_administrativo_id' })
  modelosFormulariosProcessosAdministrativos!: HasManyCollection<ModeloFormularioProcessoAdministrativo>;

  @HasMany({ target: () => Manifestacao, foreignKey: 'documento_processo_administrativo_id' })
  manifestacoes!: HasManyCollection<Manifestacao>;

  @BelongsTo({ target: () => ProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  processoAdministrativo!: BelongsToReference<ProcessoAdministrativo>;

  @BelongsTo({ target: () => DocumentoProcessoAdministrativo, foreignKey: 'parent_id' })
  parent!: BelongsToReference<DocumentoProcessoAdministrativo>;

  @HasMany({ target: () => DocumentoProcessoAdministrativo, foreignKey: 'parent_id' })
  documentosProcessosAdministrativos!: HasManyCollection<DocumentoProcessoAdministrativo>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario!: BelongsToReference<Usuario>;

  @BelongsTo({ target: () => TipoDocumento, foreignKey: 'tipo_documento_id' })
  tipoDocumento!: BelongsToReference<TipoDocumento>;

  @BelongsTo({ target: () => DocumentoRascunho, foreignKey: 'documento_rascunho_id' })
  documentoRascunho!: BelongsToReference<DocumentoRascunho>;

  @BelongsTo({ target: () => ProvidenciaJuridica, foreignKey: 'providencia_juridica_id' })
  providenciaJuridica!: BelongsToReference<ProvidenciaJuridica>;

  @BelongsTo({ target: () => DocumentoComunicacao, foreignKey: 'documento_comunicacao_id' })
  documentoComunicacao!: BelongsToReference<DocumentoComunicacao>;

  @HasMany({ target: () => Protocolizacao, foreignKey: 'peticao_id' })
  protocolizacoes!: HasManyCollection<Protocolizacao>;

  @HasMany({ target: () => DocumentoProtocolizacao, foreignKey: 'documento_processo_administrativo_id' })
  documentosProtocolizacoes!: HasManyCollection<DocumentoProtocolizacao>;

}
