// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { DocumentoComunicacao } from './DocumentoComunicacao';

@Entity({ tableName: 'documento_comunicacao_outro_parametro' })
export class DocumentoComunicacaoOutroParametro {
  /**
   * Identificador único.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Armazena o nome específico do documento.
   */
  @Column(col.notNull(col.varchar(500)))
  nome!: string;

  /**
   * Armazena o valor.
   */
  @Column(col.text())
  valor?: string;

  /**
   * Identificador que informa o documento de comunicação relacionado.
   * @remarks References dbo.documento_comunicacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'documento_comunicacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  documento_comunicacao_id!: number;

  @BelongsTo({ target: () => DocumentoComunicacao, foreignKey: 'documento_comunicacao_id' })
  documentoComunicacao!: BelongsToReference<DocumentoComunicacao>;

}
