// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { Acordo } from './Acordo';
import { DocumentoProcessoAdministrativo } from './DocumentoProcessoAdministrativo';
import { Usuario } from './Usuario';

@Entity({ tableName: 'documento_processo_administrativo_acordo' })
export class DocumentoProcessoAdministrativoAcordo {
  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * @remarks References dbo.documento_processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'documento_processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  documento_processo_administrativo_id!: number;

  /**
   * @remarks References dbo.acordo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'acordo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  acordo_id!: number;

  @Column(col.notNull(col.int()))
  documento_acordo_id!: number;

  /**
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id!: number;

  @Column(col.int())
  pessoa_id?: number;

  @Column(col.notNull(col.datetime<Date>()))
  created!: Date;

  @Column(col.notNull(col.datetime<Date>()))
  modified!: Date;

  @BelongsTo({ target: () => DocumentoProcessoAdministrativo, foreignKey: 'documento_processo_administrativo_id' })
  documentoProcessoAdministrativo!: BelongsToReference<DocumentoProcessoAdministrativo>;

  @BelongsTo({ target: () => Acordo, foreignKey: 'acordo_id' })
  acordo!: BelongsToReference<Acordo>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario!: BelongsToReference<Usuario>;

}
