// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, BelongsToReference, ManyToManyCollection } from 'metal-orm';
import { DocumentoProcessoAdministrativo } from './DocumentoProcessoAdministrativo.js';
import { DocumentoRascunhoEstado } from './DocumentoRascunhoEstado.js';
import { DocumentoRascunhoProvidenciaJuridica } from './DocumentoRascunhoProvidenciaJuridica.js';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';
import { ProvidenciaJuridica } from './ProvidenciaJuridica.js';
import { RegistroTramitacao } from './RegistroTramitacao.js';
import { Solicitacao } from './Solicitacao.js';
import { TipoAcao } from './TipoAcao.js';
import { TipoDocumento } from './TipoDocumento.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'documento_rascunho' })
export class DocumentoRascunho {
  /**
   * Identificador único.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Descrição do rascunho.
   */
  @Column(col.notNull(col.text()))
  descricao!: string;

  /**
   * Solicitação.
   * @remarks References dbo.solicitacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'solicitacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  solicitacao_id?: number;

  /**
   * Providência jurídica relacionada.
   * @remarks References dbo.providencia_juridica.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'providencia_juridica', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  providencia_juridica_id?: number;

  /**
   * Conteúdo do documento.
   */
  @Column(col.text())
  documento?: string;

  /**
   * data de criação.
   */
  @Column(col.notNull(col.datetime<Date>()))
  data!: Date;

  /**
   * Identificador do tipo de ação.
   * @remarks References dbo.tipo_acao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tipo_acao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_acao_id?: number;

  /**
   * Tipo do documento.
   * @remarks References dbo.tipo_documento.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tipo_documento', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_documento_id?: number;

  /**
   * Usuário que criou o documento.
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id?: number;

  /**
   * Processo administrativo vinculado ao documento.
   * @remarks References dbo.processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_administrativo_id?: number;

  /**
   * Revisor vinculado.
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  revisor_id?: number;

  /**
   * Estado vinculado.
   */
  @Column(col.int())
  estado_id?: number;

  @BelongsToMany({ target: () => ProvidenciaJuridica, pivotTable: () => DocumentoRascunhoProvidenciaJuridica, pivotForeignKeyToRoot: 'documento_rascunho_id', pivotForeignKeyToTarget: 'providencia_juridica_id' })
  providenciasJuridicas!: ManyToManyCollection<ProvidenciaJuridica>;

  @BelongsTo({ target: () => Solicitacao, foreignKey: 'solicitacao_id' })
  solicitacao!: BelongsToReference<Solicitacao>;

  @BelongsTo({ target: () => ProvidenciaJuridica, foreignKey: 'providencia_juridica_id' })
  providenciaJuridica!: BelongsToReference<ProvidenciaJuridica>;

  @BelongsTo({ target: () => TipoAcao, foreignKey: 'tipo_acao_id' })
  tipoAcao!: BelongsToReference<TipoAcao>;

  @BelongsTo({ target: () => TipoDocumento, foreignKey: 'tipo_documento_id' })
  tipoDocumento!: BelongsToReference<TipoDocumento>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario!: BelongsToReference<Usuario>;

  @BelongsTo({ target: () => ProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  processoAdministrativo!: BelongsToReference<ProcessoAdministrativo>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'revisor_id' })
  revisor!: BelongsToReference<Usuario>;

  @HasMany({ target: () => DocumentoRascunhoEstado, foreignKey: 'documento_rascunho_id' })
  documentosRascunhosEstados!: HasManyCollection<DocumentoRascunhoEstado>;

  @HasMany({ target: () => DocumentoRascunhoProvidenciaJuridica, foreignKey: 'documento_rascunho_id' })
  documentosRascunhosProvidenciasJuridicas!: HasManyCollection<DocumentoRascunhoProvidenciaJuridica>;

  @HasMany({ target: () => DocumentoProcessoAdministrativo, foreignKey: 'documento_rascunho_id' })
  documentosProcessosAdministrativos!: HasManyCollection<DocumentoProcessoAdministrativo>;

  @HasMany({ target: () => RegistroTramitacao, foreignKey: 'documento_rascunho_id' })
  registrosTramitacoes!: HasManyCollection<RegistroTramitacao>;

}
