// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { Pessoa } from './Pessoa';

@Entity({ tableName: 'endereco_pessoa' })
export class EnderecoPessoa {
  /**
   * Armazena um código ou identificador único de um endereço específico na tabela.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Armazena o identificador único ou código de uma pessoa específica relacionada ao endereço.
   * @remarks References dbo.pessoa.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'pessoa', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  pessoa_id?: number;

  /**
   * Armazena o logradouro da pessoa.
   */
  @Column(col.text())
  logradouro?: string;

  /**
   * Armazena o número residencial da pessoa.
   */
  @Column(col.text())
  numero?: string;

  /**
   * Armazena o complemento residencial da pessoa.
   */
  @Column(col.text())
  complemento?: string;

  /**
   * Armazena o bairro da pessoa.
   */
  @Column(col.text())
  bairro?: string;

  /**
   * Armazena a cidade da pessoa.
   */
  @Column(col.text())
  cidade?: string;

  /**
   * Armazena o estado da pessoa.
   */
  @Column(col.text())
  estado?: string;

  /**
   * Armazena o país da pessoa.
   */
  @Column(col.text())
  pais?: string;

  /**
   * Armazena o CEP da pessoa.
   */
  @Column(col.varchar(50))
  cep?: string;

  @BelongsTo({ target: () => Pessoa, foreignKey: 'pessoa_id' })
  pessoa!: BelongsToReference<Pessoa>;

}
