// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import {
  col,
  Entity,
  Column,
  PrimaryKey,
  bootstrapEntities,
  getTableDefFromEntity,
} from 'metal-orm';

@Entity({ tableName: 'nota_versao' })
export class NotaVersao {
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  @Column(col.notNull(col.date<Date>()))
  data!: Date;

  @Column(col.notNull(col.int()))
  sprint!: number;

  @Column(col.notNull(col.boolean()))
  ativo!: boolean;

  @Column(col.notNull(col.varchar(255)))
  mensagem!: string;

  @Column(col.datetime<Date>())
  data_exclusao?: Date;

  @Column(col.datetime<Date>())
  data_inativacao?: Date;

}

export const bootstrapEntityTables = () => {
  const tables = bootstrapEntities();
  return {
    NotaVersao: getTableDefFromEntity(NotaVersao)!,
  };
};

export const allTables = () => bootstrapEntities();
