// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { Equipe } from './Equipe';
import { Usuario } from './Usuario';

@Entity({ tableName: 'equipe_usuario' })
export class EquipeUsuario {
  /**
   * Armazena um identificador único para cada registro na tabela.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Armazena um identificador ou código que está relacionado a uma equipe específica.
   * @remarks References dbo.equipe.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'equipe', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  equipe_id!: number;

  /**
   * Armazena um identificador ou código que está relacionado a um usuário específico.
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id!: number;

  @BelongsTo({ target: () => Equipe, foreignKey: 'equipe_id' })
  equipe!: BelongsToReference<Equipe>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario!: BelongsToReference<Usuario>;

}
