// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { Especializada } from './Especializada.js';
import { Materia } from './Materia.js';

@Entity({ tableName: 'especializada_materia' })
export class EspecializadaMateria {
  /**
   * Identificador da especializada matéria
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador da especializada
   * @remarks References dbo.especializada.id (on delete CASCADE, on update CASCADE)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'especializada', column: 'id', onDelete: 'CASCADE', onUpdate: 'CASCADE' }))
  especializada_id!: number;

  /**
   * Identificador da matéria
   * @remarks References dbo.materia.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'materia', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  materia_id!: number;

  /**
   * Identificador do tipo acervo
   */
  @Column(col.int())
  tipo_acervo_id?: number;

  /**
   * Indica se a distribuição de um caso ou matéria para avaliação foi realizada de forma automática pelo sistema.
   */
  @Column(col.boolean())
  distribuicao_automatica?: boolean;

  @BelongsTo({ target: () => Especializada, foreignKey: 'especializada_id' })
  especializada?: Especializada;

  @BelongsTo({ target: () => Materia, foreignKey: 'materia_id' })
  materia?: Materia;

}
