// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { Especializada } from './Especializada.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'especializada_assistente' })
export class EspecializadaAssistente {
  /**
   * Armazena o identificador único ou o código para cada registro específico.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Armazena o identificador único ou o código da especializada relacionada.
   * @remarks References dbo.especializada.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'especializada', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  especializada_id?: number;

  /**
   * Armazena o código ou o identificador único específico do assistente.
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  assistente_id?: number;

  @BelongsTo({ target: () => Especializada, foreignKey: 'especializada_id' })
  especializada?: Especializada;

  @BelongsTo({ target: () => Usuario, foreignKey: 'assistente_id' })
  assistente?: Usuario;

}
