// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { EstadoProcessoAdministrativo } from './EstadoProcessoAdministrativo';
import { MotivoArquivamento } from './MotivoArquivamento';

@Entity({ tableName: 'estado_processo_administrativo_motivo_arquivamento' })
export class EstadoProcessoAdministrativoMotivoArquivamento {
  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * @remarks References dbo.estado_processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'estado_processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  estado_processo_administrativo_id!: number;

  /**
   * @remarks References dbo.motivo_arquivamento.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'motivo_arquivamento', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  motivo_arquivamento_id!: number;

  @BelongsTo({ target: () => EstadoProcessoAdministrativo, foreignKey: 'estado_processo_administrativo_id' })
  estadoProcessoAdministrativo!: BelongsToReference<EstadoProcessoAdministrativo>;

  @BelongsTo({ target: () => MotivoArquivamento, foreignKey: 'motivo_arquivamento_id' })
  motivoArquivamento!: BelongsToReference<MotivoArquivamento>;

}
