// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsToMany, HasManyCollection, ManyToManyCollection } from 'metal-orm';
import { Comunicacao } from './Comunicacao.js';
import { ComunicacaoEstado } from './ComunicacaoEstado.js';
import { DocumentoRascunhoEstado } from './DocumentoRascunhoEstado.js';
import { EstadoProcessoAdministrativo } from './EstadoProcessoAdministrativo.js';
import { EstadoSolicitacao } from './EstadoSolicitacao.js';
import { Manifestacao } from './Manifestacao.js';
import { ManifestacaoEstado } from './ManifestacaoEstado.js';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';
import { ProvidenciaJuridica } from './ProvidenciaJuridica.js';
import { Solicitacao } from './Solicitacao.js';
import { SorteioCorreicaoProcessoAdministrativo } from './SorteioCorreicaoProcessoAdministrativo.js';
import { TipoAcao } from './TipoAcao.js';
import { TipoAcaoEstado } from './TipoAcaoEstado.js';

@Entity({ tableName: 'estado' })
export class Estado {
  /**
   * Identificador do estado
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Indica o status atual em que se encontra o processo administrativo.
   */
  @Column(col.notNull(col.varchar(127)))
  nome!: string;

  /**
   * Se refere à categorização ou agrupamento do processo de acordo com critérios específicos.
   */
  @Column(col.varchar(255))
  classificacao?: string;

  @BelongsToMany({ target: () => TipoAcao, pivotTable: () => TipoAcaoEstado, pivotForeignKeyToRoot: 'estado_id', pivotForeignKeyToTarget: 'tipo_acao_id' })
  tiposAcao!: ManyToManyCollection<TipoAcao>;

  @HasMany({ target: () => EstadoSolicitacao, foreignKey: 'estado_id' })
  estadosSolicitacao!: HasManyCollection<EstadoSolicitacao>;

  @HasMany({ target: () => Manifestacao, foreignKey: 'estado_id' })
  manifestacoes!: HasManyCollection<Manifestacao>;

  @HasMany({ target: () => DocumentoRascunhoEstado, foreignKey: 'estado_id' })
  documentosRascunhoEstado!: HasManyCollection<DocumentoRascunhoEstado>;

  @HasMany({ target: () => EstadoProcessoAdministrativo, foreignKey: 'estado_id' })
  estadosProcessoAdministrativo!: HasManyCollection<EstadoProcessoAdministrativo>;

  @HasMany({ target: () => ProcessoAdministrativo, foreignKey: 'estado_id' })
  processosAdministrativo!: HasManyCollection<ProcessoAdministrativo>;

  @HasMany({ target: () => TipoAcaoEstado, foreignKey: 'estado_id' })
  tiposAcaoEstado!: HasManyCollection<TipoAcaoEstado>;

  @HasMany({ target: () => SorteioCorreicaoProcessoAdministrativo, foreignKey: 'estado_id' })
  sorteiosCorreicaoProcessoAdministrativo!: HasManyCollection<SorteioCorreicaoProcessoAdministrativo>;

  @HasMany({ target: () => ProvidenciaJuridica, foreignKey: 'estado_id' })
  providenciasJuridica!: HasManyCollection<ProvidenciaJuridica>;

  @HasMany({ target: () => Comunicacao, foreignKey: 'estado_id' })
  comunicacoes!: HasManyCollection<Comunicacao>;

  @HasMany({ target: () => ComunicacaoEstado, foreignKey: 'estado_id' })
  comunicacoesEstado!: HasManyCollection<ComunicacaoEstado>;

  @HasMany({ target: () => Solicitacao, foreignKey: 'estado_id' })
  solicitacoes!: HasManyCollection<Solicitacao>;

  @HasMany({ target: () => ManifestacaoEstado, foreignKey: 'estado_id' })
  manifestacoesEstado!: HasManyCollection<ManifestacaoEstado>;

}
