// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsToMany, HasManyCollection, ManyToManyCollection } from 'metal-orm';
import { Comunicacao } from './Comunicacao';
import { ComunicacaoEstado } from './ComunicacaoEstado';
import { DocumentoRascunhoEstado } from './DocumentoRascunhoEstado';
import { EstadoProcessoAdministrativo } from './EstadoProcessoAdministrativo';
import { EstadoSolicitacao } from './EstadoSolicitacao';
import { Manifestacao } from './Manifestacao';
import { ManifestacaoEstado } from './ManifestacaoEstado';
import { ProcessoAdministrativo } from './ProcessoAdministrativo';
import { ProvidenciaJuridica } from './ProvidenciaJuridica';
import { Solicitacao } from './Solicitacao';
import { SorteioCorreicaoProcessoAdministrativo } from './SorteioCorreicaoProcessoAdministrativo';
import { TipoAcao } from './TipoAcao';
import { TipoAcaoEstado } from './TipoAcaoEstado';

@Entity({ tableName: 'estado' })
export class Estado {
  /**
   * Identificador do estado
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Indica o status atual em que se encontra o processo administrativo.
   */
  @Column(col.notNull(col.varchar(127)))
  nome!: string;

  /**
   * Se refere à categorização ou agrupamento do processo de acordo com critérios específicos.
   */
  @Column(col.varchar(255))
  classificacao?: string;

  @BelongsToMany({ target: () => TipoAcao, pivotTable: () => TipoAcaoEstado, pivotForeignKeyToRoot: 'estado_id', pivotForeignKeyToTarget: 'tipo_acao_id' })
  tipoAcaos!: ManyToManyCollection<TipoAcao>;

  @HasMany({ target: () => EstadoSolicitacao, foreignKey: 'estado_id' })
  estadoSolicitacaos!: HasManyCollection<EstadoSolicitacao>;

  @HasMany({ target: () => Manifestacao, foreignKey: 'estado_id' })
  manifestacaos!: HasManyCollection<Manifestacao>;

  @HasMany({ target: () => DocumentoRascunhoEstado, foreignKey: 'estado_id' })
  documentoRascunhoEstados!: HasManyCollection<DocumentoRascunhoEstado>;

  @HasMany({ target: () => EstadoProcessoAdministrativo, foreignKey: 'estado_id' })
  estadoProcessoAdministrativos!: HasManyCollection<EstadoProcessoAdministrativo>;

  @HasMany({ target: () => ProcessoAdministrativo, foreignKey: 'estado_id' })
  processoAdministrativos!: HasManyCollection<ProcessoAdministrativo>;

  @HasMany({ target: () => SorteioCorreicaoProcessoAdministrativo, foreignKey: 'estado_id' })
  sorteioCorreicaoProcessoAdministrativos!: HasManyCollection<SorteioCorreicaoProcessoAdministrativo>;

  @HasMany({ target: () => ProvidenciaJuridica, foreignKey: 'estado_id' })
  providenciaJuridicas!: HasManyCollection<ProvidenciaJuridica>;

  @HasMany({ target: () => Comunicacao, foreignKey: 'estado_id' })
  comunicacaos!: HasManyCollection<Comunicacao>;

  @HasMany({ target: () => ComunicacaoEstado, foreignKey: 'estado_id' })
  comunicacaoEstados!: HasManyCollection<ComunicacaoEstado>;

  @HasMany({ target: () => Solicitacao, foreignKey: 'estado_id' })
  solicitacaos!: HasManyCollection<Solicitacao>;

  @HasMany({ target: () => ManifestacaoEstado, foreignKey: 'estado_id' })
  manifestacaoEstados!: HasManyCollection<ManifestacaoEstado>;

}
