// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, HasManyCollection, BelongsToReference } from 'metal-orm';
import { Estado } from './Estado';
import { RegistroTramitacao } from './RegistroTramitacao';
import { Solicitacao } from './Solicitacao';
import { Usuario } from './Usuario';

@Entity({ tableName: 'estado_solicitacao' })
export class EstadoSolicitacao {
  /**
   * Identificador do estado da solicitação
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador da solicitação
   * @remarks References dbo.solicitacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'solicitacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  solicitacao_id!: number;

  /**
   * Identificador do estado
   * @remarks References dbo.estado.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'estado', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  estado_id!: number;

  /**
   * Indica a data em que ocorreu a troca ou transição de estado em uma solicitação.
   */
  @Column(col.datetime<Date>())
  data_troca_estado?: Date;

  /**
   * Identificador do usuário
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id?: number;

  /**
   * Armazena informações descritivas sobre o estado de uma solicitação.
   */
  @Column(col.text())
  descricao?: string;

  @BelongsTo({ target: () => Solicitacao, foreignKey: 'solicitacao_id' })
  solicitacao!: BelongsToReference<Solicitacao>;

  @BelongsTo({ target: () => Estado, foreignKey: 'estado_id' })
  estado!: BelongsToReference<Estado>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario!: BelongsToReference<Usuario>;

  @HasMany({ target: () => RegistroTramitacao, foreignKey: 'estado_solicitacao_id' })
  registrosTramitacoes!: HasManyCollection<RegistroTramitacao>;

}
