// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { Indexador } from './Indexador';

@Entity({ tableName: 'fator_correcao' })
export class FatorCorrecao {
  /**
   * Identificador do fator correção
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Se refere ao intervalo de tempo durante o qual um determinado fator de correção é aplicável.
   */
  @Column(col.notNull(col.date<Date>()))
  periodo!: Date;

  /**
   * Armazena o valor do fator de correção aplicado a determinados dados ou valores financeiros.
   */
  @Column(col.notNull(col.decimal(18, 10)))
  valor!: number;

  /**
   * Identificador do indexador
   * @remarks References dbo.indexador.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'indexador', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  indexador_id!: number;

  /**
   * Registra a data e hora de criação de um registro de fator de correção.
   */
  @Column(col.datetime<Date>())
  created?: Date;

  /**
   * Indica a data e hora da última modificação ou atualização de um registro de fator de correção.
   */
  @Column(col.datetime<Date>())
  modified?: Date;

  @BelongsTo({ target: () => Indexador, foreignKey: 'indexador_id' })
  indexador!: BelongsToReference<Indexador>;

}
