// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { MniTribunal } from './MniTribunal';

@Entity({ tableName: 'feriado' })
export class Feriado {
  /**
   * Identificador do feriado
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Data de início do feriado
   */
  @Column(col.notNull(col.date<Date>()))
  data_inicio!: Date;

  /**
   * Data fim do feriado
   */
  @Column(col.date<Date>())
  data_fim?: Date;

  /**
   * Armazena uma descrição textual que identifica ou descreve um feriado específico.
   */
  @Column(col.text())
  descricao?: string;

  /**
   * Identificador do tribunal
   * @remarks References dbo.mni_tribunal.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'mni_tribunal', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tribunal_id?: number;

  @Column(col.datetime<Date>())
  created?: Date;

  @Column(col.datetime<Date>())
  modified?: Date;

  @BelongsTo({ target: () => MniTribunal, foreignKey: 'tribunal_id' })
  tribunal!: BelongsToReference<MniTribunal>;

}
