// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsToMany, HasManyCollection, ManyToManyCollection } from 'metal-orm';
import { Acervo } from './Acervo';
import { AfastamentoPessoa } from './AfastamentoPessoa';
import { ClassificacaoEspecializadaTema } from './ClassificacaoEspecializadaTema';
import { ElementoFilaCircular } from './ElementoFilaCircular';
import { Equipe } from './Equipe';
import { Especializada } from './Especializada';
import { EspecializadaTema } from './EspecializadaTema';

@Entity({ tableName: 'fila_circular' })
export class FilaCircular {
  /**
   * Identificador da fila circular
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Indica o último elemento inserido ou processado em uma fila circular.
   */
  @Column(col.notNull(col.int()))
  ultimo_elemento!: number;

  @BelongsToMany({ target: () => Especializada, pivotTable: () => Equipe, pivotForeignKeyToRoot: 'fila_circular_id', pivotForeignKeyToTarget: 'especializada_id' })
  especializadas!: ManyToManyCollection<Especializada>;

  @HasMany({ target: () => ClassificacaoEspecializadaTema, foreignKey: 'fila_circular_id' })
  classificacoesEspecializadasTemas!: HasManyCollection<ClassificacaoEspecializadaTema>;

  @HasMany({ target: () => EspecializadaTema, foreignKey: 'fila_circular_id' })
  especializadasTemas!: HasManyCollection<EspecializadaTema>;

  @HasMany({ target: () => AfastamentoPessoa, foreignKey: 'fila_circular_id' })
  afastamentosPessoas!: HasManyCollection<AfastamentoPessoa>;

  @HasMany({ target: () => ElementoFilaCircular, foreignKey: 'fila_circular_id' })
  elementosFilasCirculares!: HasManyCollection<ElementoFilaCircular>;

  @HasMany({ target: () => Acervo, foreignKey: 'fila_circular_id' })
  acervos!: HasManyCollection<Acervo>;

}
