// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { Especializada } from './Especializada';
import { Usuario } from './Usuario';

@Entity({ tableName: 'historico_usuario_especializada' })
export class HistoricoUsuarioEspecializada {
  /**
   * Identificador do histórico usuário especializada
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador da especializada
   * @remarks References dbo.especializada.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'especializada', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  especializada_id!: number;

  /**
   * Identificador do usuário da ação
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_acao_id!: number;

  /**
   * Identificador do usuário
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id!: number;

  /**
   * Registra o horário exato em que ocorreu a distribuição
   */
  @Column(col.notNull(col.datetime<Date>()))
  horario_distribuicao!: Date;

  /**
   * Registra o endereço IP associado a uma distribuição
   */
  @Column(col.notNull(col.varchar(15)))
  ip!: string;

  @BelongsTo({ target: () => Especializada, foreignKey: 'especializada_id' })
  especializada!: BelongsToReference<Especializada>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_acao_id' })
  usuarioAcao!: BelongsToReference<Usuario>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario!: BelongsToReference<Usuario>;

}
