// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { Justificativa } from './Justificativa.js';
import { ProvidenciaJuridica } from './ProvidenciaJuridica.js';
import { TipoProvidenciaJuridica } from './TipoProvidenciaJuridica.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'historico_prazo' })
export class HistoricoPrazo {
  /**
   * Identificador do histórico do prazo
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Registra informações relacionadas a um prazo específico.
   */
  @Column(col.date<Date>())
  prazo?: Date;

  /**
   * Identificador da justificativa
   * @remarks References dbo.justificativa.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'justificativa', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  justificativa_id!: number;

  /**
   * Armazena informações detalhadas ou observações relevantes associadas a um prazo específico registrado.
   */
  @Column(col.text())
  detalhes?: string;

  /**
   * Identificador da providência jurídica
   * @remarks References dbo.providencia_juridica.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'providencia_juridica', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  providencia_juridica_id!: number;

  /**
   * Identificador do tipo da providência jurídica
   * @remarks References dbo.tipo_providencia_juridica.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tipo_providencia_juridica', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_providencia_juridica_id?: number;

  /**
   * Identificador do usuário
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id?: number;

  /**
   * @defaultValue (getdate())
   */
  @Column(col.defaultRaw(col.datetime<Date>(), '(getdate())'))
  created?: Date;

  @BelongsTo({ target: () => Justificativa, foreignKey: 'justificativa_id' })
  justificativa?: Justificativa;

  @BelongsTo({ target: () => ProvidenciaJuridica, foreignKey: 'providencia_juridica_id' })
  providenciaJuridica?: ProvidenciaJuridica;

  @BelongsTo({ target: () => TipoProvidenciaJuridica, foreignKey: 'tipo_providencia_juridica_id' })
  tipoProvidenciaJuridica?: TipoProvidenciaJuridica;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario?: Usuario;

}
