// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { DesabilitaTipoIntegracao } from './DesabilitaTipoIntegracao';
import { TipoIncidente } from './TipoIncidente';

@Entity({ tableName: 'incidente' })
export class Incidente {
  /**
   * Identificador do incidente
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Data do incidente
   */
  @Column(col.notNull(col.date<Date>()))
  data!: Date;

  /**
   * Indicador que mostra se um incidente específico está ativo ou inativo no sistema.
   */
  @Column(col.notNull(col.boolean()))
  ativo!: boolean;

  /**
   * Armazena informações detalhadas ou observações relevantes relacionadas a um incidente específico.
   */
  @Column(col.notNull(col.text()))
  mensagem!: string;

  /**
   * Identificador do tipo incidente
   * @remarks References dbo.tipo_incidente.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tipo_incidente', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_incidente_id?: number;

  /**
   * Indica a data em que um incidente foi excluído do sistema ou marcado como inativo.
   */
  @Column(col.datetime<Date>())
  data_exclusao?: Date;

  /**
   * Identificador do desabilita tipo integração
   * @remarks References dbo.desabilita_tipo_integracao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'desabilita_tipo_integracao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  desabilita_tipo_integracao_id?: number;

  /**
   * Representa a data em que um incidente específico foi inativado.
   */
  @Column(col.datetime<Date>())
  data_inativacao?: Date;

  /**
   * Armazena um número ou código único associado a cada ocorrência de incidente.
   */
  @Column(col.int())
  numero_ocorrencia?: number;

  @BelongsTo({ target: () => TipoIncidente, foreignKey: 'tipo_incidente_id' })
  tipoIncidente!: BelongsToReference<TipoIncidente>;

  @BelongsTo({ target: () => DesabilitaTipoIntegracao, foreignKey: 'desabilita_tipo_integracao_id' })
  desabilitaTipoIntegracao!: BelongsToReference<DesabilitaTipoIntegracao>;

}
