// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { bootstrapEntities, getTableDefFromEntity } from 'metal-orm';
import { PredicaoOrgaoJulgadorEspecializada } from './PredicaoOrgaoJulgadorEspecializada.js';
import { ProcessoJudicial } from './ProcessoJudicial.js';
import { ExitoSucumbencia } from './ExitoSucumbencia.js';
import { DesabilitaTipoIntegracao } from './DesabilitaTipoIntegracao.js';
import { DocumentoProcessoAdministrativoAcordo } from './DocumentoProcessoAdministrativoAcordo.js';
import { CodigoExterno } from './CodigoExterno.js';
import { ProvidenciaJuridicaSolicitacao } from './ProvidenciaJuridicaSolicitacao.js';
import { PalavraChaveProcessoAdministrativo } from './PalavraChaveProcessoAdministrativo.js';
import { ClassificacaoEspecializadaTema } from './ClassificacaoEspecializadaTema.js';
import { TipoInteressadoConsultivo } from './TipoInteressadoConsultivo.js';
import { PredicaoAssuntoEspecializada } from './PredicaoAssuntoEspecializada.js';
import { MovimentacaoJudicial } from './MovimentacaoJudicial.js';
import { PreferenciaUsuario } from './PreferenciaUsuario.js';
import { TipoDivisaoCargaTrabalho } from './TipoDivisaoCargaTrabalho.js';
import { Natureza } from './Natureza.js';
import { TipoManifestacao } from './TipoManifestacao.js';
import { EstadoSolicitacao } from './EstadoSolicitacao.js';
import { NivelSigilo } from './NivelSigilo.js';
import { Estado } from './Estado.js';
import { ProcessoJudicialOriginario } from './ProcessoJudicialOriginario.js';
import { Correicao } from './Correicao.js';
import { MarcadorDocumentoProcessoJudicial } from './MarcadorDocumentoProcessoJudicial.js';
import { ProcessoAdministrativoTema } from './ProcessoAdministrativoTema.js';
import { ProcessoJudicialOutroNumero } from './ProcessoJudicialOutroNumero.js';
import { EspecializadaMateria } from './EspecializadaMateria.js';
import { ModeloFormularioProcessoAdministrativo } from './ModeloFormularioProcessoAdministrativo.js';
import { Pessoa } from './Pessoa.js';
import { OutroParametroDocumentoComunicacao } from './OutroParametroDocumentoComunicacao.js';
import { RetornoProgramado } from './RetornoProgramado.js';
import { Parte } from './Parte.js';
import { Manifestacao } from './Manifestacao.js';
import { EspecializadaTema } from './EspecializadaTema.js';
import { PalavraChaveTema } from './PalavraChaveTema.js';
import { ParteRepresentante } from './ParteRepresentante.js';
import { TipoMigracaoAcervo } from './TipoMigracaoAcervo.js';
import { Tramitacao } from './Tramitacao.js';
import { TipoLocalidadeEspecializada } from './TipoLocalidadeEspecializada.js';
import { EspecializadaDistribuidor } from './EspecializadaDistribuidor.js';
import { ContatoMniTribunal } from './ContatoMniTribunal.js';
import { Equipe } from './Equipe.js';
import { AcervoEquipeApoio } from './AcervoEquipeApoio.js';
import { Materia } from './Materia.js';
import { ModeloFormularioProcessoAdministrativoEstadoModeloFormulario } from './ModeloFormularioProcessoAdministrativoEstadoModeloFormulario.js';
import { TipoDispensa } from './TipoDispensa.js';
import { Publicacao } from './Publicacao.js';
import { DocumentoRascunho } from './DocumentoRascunho.js';
import { CodigoUnidadeProtocoladora } from './CodigoUnidadeProtocoladora.js';
import { AssuntoLocal } from './AssuntoLocal.js';
import { Perfil } from './Perfil.js';
import { Carga } from './Carga.js';
import { DispensaGenerica } from './DispensaGenerica.js';
import { TempInformacaoComplementar } from './TempInformacaoComplementar.js';
import { Classificacao } from './Classificacao.js';
import { ReciboTj } from './ReciboTj.js';
import { DocumentoRascunhoEstado } from './DocumentoRascunhoEstado.js';
import { ComunicacaoOutroParametro } from './ComunicacaoOutroParametro.js';
import { ModeloFormulario } from './ModeloFormulario.js';
import { DescricaoSolicitacao } from './DescricaoSolicitacao.js';
import { Capitulo } from './Capitulo.js';
import { RelacionamentoProcessual } from './RelacionamentoProcessual.js';
import { RepresentanteJudicial } from './RepresentanteJudicial.js';
import { DocumentoRascunhoProvidenciaJuridica } from './DocumentoRascunhoProvidenciaJuridica.js';
import { Tema } from './Tema.js';
import { TipoProcessoAdministrativo } from './TipoProcessoAdministrativo.js';
import { TipoAcao } from './TipoAcao.js';
import { TipoAtividade } from './TipoAtividade.js';
import { ConsumoProcesso } from './ConsumoProcesso.js';
import { DocumentoAcordoContencioso } from './DocumentoAcordoContencioso.js';
import { UsuarioPerfil } from './UsuarioPerfil.js';
import { OrgaoJulgador } from './OrgaoJulgador.js';
import { TipoComunicacao } from './TipoComunicacao.js';
import { TipoAcaoTipoProcessoAdministrativo } from './TipoAcaoTipoProcessoAdministrativo.js';
import { TipoDocumentoPessoa } from './TipoDocumentoPessoa.js';
import { EstadoProcessoAdministrativo } from './EstadoProcessoAdministrativo.js';
import { EspecializadaAssistente } from './EspecializadaAssistente.js';
import { DocumentoComunicacao } from './DocumentoComunicacao.js';
import { Magistrado } from './Magistrado.js';
import { TipoInstancia } from './TipoInstancia.js';
import { Despacho } from './Despacho.js';
import { RaioXJuridico } from './RaioXJuridico.js';
import { TipoLogradouro } from './TipoLogradouro.js';
import { PalavraChave } from './PalavraChave.js';
import { InteressadoConsultivo } from './InteressadoConsultivo.js';
import { OutroParametroComunicacao } from './OutroParametroComunicacao.js';
import { TipoModalidadeRelacionamentoPessoal } from './TipoModalidadeRelacionamentoPessoal.js';
import { Especializada } from './Especializada.js';
import { DocumentoAnexoRascunho } from './DocumentoAnexoRascunho.js';
import { TipoSolicitacao } from './TipoSolicitacao.js';
import { TipoModalidadeVinculacaoProcessual } from './TipoModalidadeVinculacaoProcessual.js';
import { DjeTribunal } from './DjeTribunal.js';
import { AcervoDestinatarioPa } from './AcervoDestinatarioPa.js';
import { TipoValorAdicional } from './TipoValorAdicional.js';
import { TipoAcervo } from './TipoAcervo.js';
import { TipoOrgaoJulgador } from './TipoOrgaoJulgador.js';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';
import { TipoEspecializada } from './TipoEspecializada.js';
import { EquipeUsuario } from './EquipeUsuario.js';
import { TipoPolo } from './TipoPolo.js';
import { DecisaoJudicial } from './DecisaoJudicial.js';
import { PedidoComplementar } from './PedidoComplementar.js';
import { RelatorioDje } from './RelatorioDje.js';
import { DocumentoProcessoAdministrativo } from './DocumentoProcessoAdministrativo.js';
import { TipoPrazo } from './TipoPrazo.js';
import { DocumentoComunicacaoOutroParametro } from './DocumentoComunicacaoOutroParametro.js';
import { TipoSolicitacaoTipoProcessoAdministrativo } from './TipoSolicitacaoTipoProcessoAdministrativo.js';
import { HistoricoDistribuicaoAcervo } from './HistoricoDistribuicaoAcervo.js';
import { TipoRepresentante } from './TipoRepresentante.js';
import { FatorCorrecao } from './FatorCorrecao.js';
import { TipoRespostaCorreicao } from './TipoRespostaCorreicao.js';
import { HistoricoDistribuicaoEspecializada } from './HistoricoDistribuicaoEspecializada.js';
import { TipoDocumentoTipoProcessoAdministrativo } from './TipoDocumentoTipoProcessoAdministrativo.js';
import { MniTribunal } from './MniTribunal.js';
import { HistoricoUsuarioEspecializada } from './HistoricoUsuarioEspecializada.js';
import { Quesito } from './Quesito.js';
import { AcervoClassificacao } from './AcervoClassificacao.js';
import { Indexador } from './Indexador.js';
import { AfastamentoPessoa } from './AfastamentoPessoa.js';
import { Sysdiagrams } from './Sysdiagrams.js';
import { ProcessoJudicialOutroParametro } from './ProcessoJudicialOutroParametro.js';
import { Instancia } from './Instancia.js';
import { EstadoModeloFormulario } from './EstadoModeloFormulario.js';
import { InstanciaMniTribunal } from './InstanciaMniTribunal.js';
import { Protocolizacao } from './Protocolizacao.js';
import { Acordo } from './Acordo.js';
import { TipoDecisao } from './TipoDecisao.js';
import { SorteioCorreicao } from './SorteioCorreicao.js';
import { Localidade } from './Localidade.js';
import { TipoFaseJudicial } from './TipoFaseJudicial.js';
import { Competencia } from './Competencia.js';
import { AcessoRestritoFuncionalidadePerfil } from './AcessoRestritoFuncionalidadePerfil.js';
import { CorreicaoQuesito } from './CorreicaoQuesito.js';
import { AcervoMateria } from './AcervoMateria.js';
import { EspecializadaUsuarioNotificacao } from './EspecializadaUsuarioNotificacao.js';
import { TipoAcaoEstado } from './TipoAcaoEstado.js';
import { SorteioCorreicaoProcessoAdministrativo } from './SorteioCorreicaoProcessoAdministrativo.js';
import { RegistroTramitacao } from './RegistroTramitacao.js';
import { ModeloFormularioValor } from './ModeloFormularioValor.js';
import { Abreviatura } from './Abreviatura.js';
import { ConsumoTeorAvisoErro } from './ConsumoTeorAvisoErro.js';
import { SorteioCorreicaoProcessoAdministrativoQuesito } from './SorteioCorreicaoProcessoAdministrativoQuesito.js';
import { AcervoTema } from './AcervoTema.js';
import { DocumentoProtocolizacao } from './DocumentoProtocolizacao.js';
import { ClasseProcessual } from './ClasseProcessual.js';
import { AcessoRestritoFuncionalidadeUsuario } from './AcessoRestritoFuncionalidadeUsuario.js';
import { Confidencialidade } from './Confidencialidade.js';
import { Justificativa } from './Justificativa.js';
import { ElementoFilaCircular } from './ElementoFilaCircular.js';
import { RegistroMigracaoSicaj } from './RegistroMigracaoSicaj.js';
import { ProcessoVinculado } from './ProcessoVinculado.js';
import { PastaCaixaEntrada } from './PastaCaixaEntrada.js';
import { TabelaExitoTj } from './TabelaExitoTj.js';
import { AfastamentoPessoaUsuario } from './AfastamentoPessoaUsuario.js';
import { Feriado } from './Feriado.js';
import { AcessoRestritoFuncionalidade } from './AcessoRestritoFuncionalidade.js';
import { Acompanhamento } from './Acompanhamento.js';
import { Servico } from './Servico.js';
import { TipoAssociacao } from './TipoAssociacao.js';
import { Arquivo } from './Arquivo.js';
import { ProcessoAdministrativoProcessoAdministrativo } from './ProcessoAdministrativoProcessoAdministrativo.js';
import { Tribunal } from './Tribunal.js';
import { TipoAudiencia } from './TipoAudiencia.js';
import { Urgencia } from './Urgencia.js';
import { ServicoToken } from './ServicoToken.js';
import { HistoricoPrazo } from './HistoricoPrazo.js';
import { AssuntoProcessoJudicial } from './AssuntoProcessoJudicial.js';
import { RaizCnpjAcervo } from './RaizCnpjAcervo.js';
import { Atividade } from './Atividade.js';
import { FilaCircular } from './FilaCircular.js';
import { MotivoAssociacao } from './MotivoAssociacao.js';
import { Usuario } from './Usuario.js';
import { ConfidencialidadeEspecializada } from './ConfidencialidadeEspecializada.js';
import { TipoDocumentoProvidencia } from './TipoDocumentoProvidencia.js';
import { ProvidenciaJuridica } from './ProvidenciaJuridica.js';
import { ComplementoMovimentacaoJudicial } from './ComplementoMovimentacaoJudicial.js';
import { Audiencia } from './Audiencia.js';
import { MotivoArquivamento } from './MotivoArquivamento.js';
import { AvisoPendente } from './AvisoPendente.js';
import { Comunicacao } from './Comunicacao.js';
import { RespostaTj } from './RespostaTj.js';
import { CodigoExternoProcessoAdministrativo } from './CodigoExternoProcessoAdministrativo.js';
import { NaturezaIncidente } from './NaturezaIncidente.js';
import { ClassificacaoRelevancia } from './ClassificacaoRelevancia.js';
import { EstadoProcessoAdministrativoMotivoArquivamento } from './EstadoProcessoAdministrativoMotivoArquivamento.js';
import { DocumentoMovimentacaoJudicial } from './DocumentoMovimentacaoJudicial.js';
import { ItemAjuda } from './ItemAjuda.js';
import { SistemaOrigem } from './SistemaOrigem.js';
import { TipoProcedimentoSei } from './TipoProcedimentoSei.js';
import { DocumentoPessoa } from './DocumentoPessoa.js';
import { TipoInteressado } from './TipoInteressado.js';
import { ProcessoFisicoAssociado } from './ProcessoFisicoAssociado.js';
import { TipoAfastamento } from './TipoAfastamento.js';
import { Modelo } from './Modelo.js';
import { ProcedimentoSei } from './ProcedimentoSei.js';
import { EnderecoPessoa } from './EnderecoPessoa.js';
import { Interessado } from './Interessado.js';
import { TipoMovimentacaoNacional } from './TipoMovimentacaoNacional.js';
import { MemoriaCalculo } from './MemoriaCalculo.js';
import { PedidoComplementarProcessoAdministrativo } from './PedidoComplementarProcessoAdministrativo.js';
import { TipoDocumento } from './TipoDocumento.js';
import { ClassificacaoRecorrencia } from './ClassificacaoRecorrencia.js';
import { NotaVersao } from './NotaVersao.js';
import { EnderecoRepresentanteJudicial } from './EnderecoRepresentanteJudicial.js';
import { ProcessoJudicialHash } from './ProcessoJudicialHash.js';
import { MapeamentoAcervoSicaj } from './MapeamentoAcervoSicaj.js';
import { UnidadeSei } from './UnidadeSei.js';
import { Incidente } from './Incidente.js';
import { Entrega } from './Entrega.js';
import { TramitacaoAutomaticaAcervoTema } from './TramitacaoAutomaticaAcervoTema.js';
import { MapeamentoLocalidadeRegional } from './MapeamentoLocalidadeRegional.js';
import { UsuarioSei } from './UsuarioSei.js';
import { InstantaneoAvisoPendente } from './InstantaneoAvisoPendente.js';
import { TipoProvidenciaJuridica } from './TipoProvidenciaJuridica.js';
import { UnidadeSeiUsuarioSei } from './UnidadeSeiUsuarioSei.js';
import { ComunicacaoEstado } from './ComunicacaoEstado.js';
import { InterpretacaoSentenca } from './InterpretacaoSentenca.js';
import { Cda } from './Cda.js';
import { TipoIncidente } from './TipoIncidente.js';
import { ModeloTema } from './ModeloTema.js';
import { UsuarioPermitidoAcessarProcessoAdministrativoSigiloso } from './UsuarioPermitidoAcessarProcessoAdministrativoSigiloso.js';
import { TipoDocumentoMni } from './TipoDocumentoMni.js';
import { ValorAdicional } from './ValorAdicional.js';
import { RegistroEnvioComunicacao } from './RegistroEnvioComunicacao.js';
import { PredicaoEspecializadaMachineLearning } from './PredicaoEspecializadaMachineLearning.js';
import { AvisoPendenteOutroParametro } from './AvisoPendenteOutroParametro.js';
import { Solicitacao } from './Solicitacao.js';
import { MagistradoProcesso } from './MagistradoProcesso.js';
import { Acervo } from './Acervo.js';
import { ManifestacaoEstado } from './ManifestacaoEstado.js';
import { ManifestacaoProcessual } from './ManifestacaoProcessual.js';

export {
  PredicaoOrgaoJulgadorEspecializada,
  ProcessoJudicial,
  ExitoSucumbencia,
  DesabilitaTipoIntegracao,
  DocumentoProcessoAdministrativoAcordo,
  CodigoExterno,
  ProvidenciaJuridicaSolicitacao,
  PalavraChaveProcessoAdministrativo,
  ClassificacaoEspecializadaTema,
  TipoInteressadoConsultivo,
  PredicaoAssuntoEspecializada,
  MovimentacaoJudicial,
  PreferenciaUsuario,
  TipoDivisaoCargaTrabalho,
  Natureza,
  TipoManifestacao,
  EstadoSolicitacao,
  NivelSigilo,
  Estado,
  ProcessoJudicialOriginario,
  Correicao,
  MarcadorDocumentoProcessoJudicial,
  ProcessoAdministrativoTema,
  ProcessoJudicialOutroNumero,
  EspecializadaMateria,
  ModeloFormularioProcessoAdministrativo,
  Pessoa,
  OutroParametroDocumentoComunicacao,
  RetornoProgramado,
  Parte,
  Manifestacao,
  EspecializadaTema,
  PalavraChaveTema,
  ParteRepresentante,
  TipoMigracaoAcervo,
  Tramitacao,
  TipoLocalidadeEspecializada,
  EspecializadaDistribuidor,
  ContatoMniTribunal,
  Equipe,
  AcervoEquipeApoio,
  Materia,
  ModeloFormularioProcessoAdministrativoEstadoModeloFormulario,
  TipoDispensa,
  Publicacao,
  DocumentoRascunho,
  CodigoUnidadeProtocoladora,
  AssuntoLocal,
  Perfil,
  Carga,
  DispensaGenerica,
  TempInformacaoComplementar,
  Classificacao,
  ReciboTj,
  DocumentoRascunhoEstado,
  ComunicacaoOutroParametro,
  ModeloFormulario,
  DescricaoSolicitacao,
  Capitulo,
  RelacionamentoProcessual,
  RepresentanteJudicial,
  DocumentoRascunhoProvidenciaJuridica,
  Tema,
  TipoProcessoAdministrativo,
  TipoAcao,
  TipoAtividade,
  ConsumoProcesso,
  DocumentoAcordoContencioso,
  UsuarioPerfil,
  OrgaoJulgador,
  TipoComunicacao,
  TipoAcaoTipoProcessoAdministrativo,
  TipoDocumentoPessoa,
  EstadoProcessoAdministrativo,
  EspecializadaAssistente,
  DocumentoComunicacao,
  Magistrado,
  TipoInstancia,
  Despacho,
  RaioXJuridico,
  TipoLogradouro,
  PalavraChave,
  InteressadoConsultivo,
  OutroParametroComunicacao,
  TipoModalidadeRelacionamentoPessoal,
  Especializada,
  DocumentoAnexoRascunho,
  TipoSolicitacao,
  TipoModalidadeVinculacaoProcessual,
  DjeTribunal,
  AcervoDestinatarioPa,
  TipoValorAdicional,
  TipoAcervo,
  TipoOrgaoJulgador,
  ProcessoAdministrativo,
  TipoEspecializada,
  EquipeUsuario,
  TipoPolo,
  DecisaoJudicial,
  PedidoComplementar,
  RelatorioDje,
  DocumentoProcessoAdministrativo,
  TipoPrazo,
  DocumentoComunicacaoOutroParametro,
  TipoSolicitacaoTipoProcessoAdministrativo,
  HistoricoDistribuicaoAcervo,
  TipoRepresentante,
  FatorCorrecao,
  TipoRespostaCorreicao,
  HistoricoDistribuicaoEspecializada,
  TipoDocumentoTipoProcessoAdministrativo,
  MniTribunal,
  HistoricoUsuarioEspecializada,
  Quesito,
  AcervoClassificacao,
  Indexador,
  AfastamentoPessoa,
  Sysdiagrams,
  ProcessoJudicialOutroParametro,
  Instancia,
  EstadoModeloFormulario,
  InstanciaMniTribunal,
  Protocolizacao,
  Acordo,
  TipoDecisao,
  SorteioCorreicao,
  Localidade,
  TipoFaseJudicial,
  Competencia,
  AcessoRestritoFuncionalidadePerfil,
  CorreicaoQuesito,
  AcervoMateria,
  EspecializadaUsuarioNotificacao,
  TipoAcaoEstado,
  SorteioCorreicaoProcessoAdministrativo,
  RegistroTramitacao,
  ModeloFormularioValor,
  Abreviatura,
  ConsumoTeorAvisoErro,
  SorteioCorreicaoProcessoAdministrativoQuesito,
  AcervoTema,
  DocumentoProtocolizacao,
  ClasseProcessual,
  AcessoRestritoFuncionalidadeUsuario,
  Confidencialidade,
  Justificativa,
  ElementoFilaCircular,
  RegistroMigracaoSicaj,
  ProcessoVinculado,
  PastaCaixaEntrada,
  TabelaExitoTj,
  AfastamentoPessoaUsuario,
  Feriado,
  AcessoRestritoFuncionalidade,
  Acompanhamento,
  Servico,
  TipoAssociacao,
  Arquivo,
  ProcessoAdministrativoProcessoAdministrativo,
  Tribunal,
  TipoAudiencia,
  Urgencia,
  ServicoToken,
  HistoricoPrazo,
  AssuntoProcessoJudicial,
  RaizCnpjAcervo,
  Atividade,
  FilaCircular,
  MotivoAssociacao,
  Usuario,
  ConfidencialidadeEspecializada,
  TipoDocumentoProvidencia,
  ProvidenciaJuridica,
  ComplementoMovimentacaoJudicial,
  Audiencia,
  MotivoArquivamento,
  AvisoPendente,
  Comunicacao,
  RespostaTj,
  CodigoExternoProcessoAdministrativo,
  NaturezaIncidente,
  ClassificacaoRelevancia,
  EstadoProcessoAdministrativoMotivoArquivamento,
  DocumentoMovimentacaoJudicial,
  ItemAjuda,
  SistemaOrigem,
  TipoProcedimentoSei,
  DocumentoPessoa,
  TipoInteressado,
  ProcessoFisicoAssociado,
  TipoAfastamento,
  Modelo,
  ProcedimentoSei,
  EnderecoPessoa,
  Interessado,
  TipoMovimentacaoNacional,
  MemoriaCalculo,
  PedidoComplementarProcessoAdministrativo,
  TipoDocumento,
  ClassificacaoRecorrencia,
  NotaVersao,
  EnderecoRepresentanteJudicial,
  ProcessoJudicialHash,
  MapeamentoAcervoSicaj,
  UnidadeSei,
  Incidente,
  Entrega,
  TramitacaoAutomaticaAcervoTema,
  MapeamentoLocalidadeRegional,
  UsuarioSei,
  InstantaneoAvisoPendente,
  TipoProvidenciaJuridica,
  UnidadeSeiUsuarioSei,
  ComunicacaoEstado,
  InterpretacaoSentenca,
  Cda,
  TipoIncidente,
  ModeloTema,
  UsuarioPermitidoAcessarProcessoAdministrativoSigiloso,
  TipoDocumentoMni,
  ValorAdicional,
  RegistroEnvioComunicacao,
  PredicaoEspecializadaMachineLearning,
  AvisoPendenteOutroParametro,
  Solicitacao,
  MagistradoProcesso,
  Acervo,
  ManifestacaoEstado,
  ManifestacaoProcessual,
};

export const bootstrapEntityTables = () => {
  const tables = bootstrapEntities();
  return {
    PredicaoOrgaoJulgadorEspecializada: getTableDefFromEntity(PredicaoOrgaoJulgadorEspecializada)!,
    ProcessoJudicial: getTableDefFromEntity(ProcessoJudicial)!,
    ExitoSucumbencia: getTableDefFromEntity(ExitoSucumbencia)!,
    DesabilitaTipoIntegracao: getTableDefFromEntity(DesabilitaTipoIntegracao)!,
    DocumentoProcessoAdministrativoAcordo: getTableDefFromEntity(DocumentoProcessoAdministrativoAcordo)!,
    CodigoExterno: getTableDefFromEntity(CodigoExterno)!,
    ProvidenciaJuridicaSolicitacao: getTableDefFromEntity(ProvidenciaJuridicaSolicitacao)!,
    PalavraChaveProcessoAdministrativo: getTableDefFromEntity(PalavraChaveProcessoAdministrativo)!,
    ClassificacaoEspecializadaTema: getTableDefFromEntity(ClassificacaoEspecializadaTema)!,
    TipoInteressadoConsultivo: getTableDefFromEntity(TipoInteressadoConsultivo)!,
    PredicaoAssuntoEspecializada: getTableDefFromEntity(PredicaoAssuntoEspecializada)!,
    MovimentacaoJudicial: getTableDefFromEntity(MovimentacaoJudicial)!,
    PreferenciaUsuario: getTableDefFromEntity(PreferenciaUsuario)!,
    TipoDivisaoCargaTrabalho: getTableDefFromEntity(TipoDivisaoCargaTrabalho)!,
    Natureza: getTableDefFromEntity(Natureza)!,
    TipoManifestacao: getTableDefFromEntity(TipoManifestacao)!,
    EstadoSolicitacao: getTableDefFromEntity(EstadoSolicitacao)!,
    NivelSigilo: getTableDefFromEntity(NivelSigilo)!,
    Estado: getTableDefFromEntity(Estado)!,
    ProcessoJudicialOriginario: getTableDefFromEntity(ProcessoJudicialOriginario)!,
    Correicao: getTableDefFromEntity(Correicao)!,
    MarcadorDocumentoProcessoJudicial: getTableDefFromEntity(MarcadorDocumentoProcessoJudicial)!,
    ProcessoAdministrativoTema: getTableDefFromEntity(ProcessoAdministrativoTema)!,
    ProcessoJudicialOutroNumero: getTableDefFromEntity(ProcessoJudicialOutroNumero)!,
    EspecializadaMateria: getTableDefFromEntity(EspecializadaMateria)!,
    ModeloFormularioProcessoAdministrativo: getTableDefFromEntity(ModeloFormularioProcessoAdministrativo)!,
    Pessoa: getTableDefFromEntity(Pessoa)!,
    OutroParametroDocumentoComunicacao: getTableDefFromEntity(OutroParametroDocumentoComunicacao)!,
    RetornoProgramado: getTableDefFromEntity(RetornoProgramado)!,
    Parte: getTableDefFromEntity(Parte)!,
    Manifestacao: getTableDefFromEntity(Manifestacao)!,
    EspecializadaTema: getTableDefFromEntity(EspecializadaTema)!,
    PalavraChaveTema: getTableDefFromEntity(PalavraChaveTema)!,
    ParteRepresentante: getTableDefFromEntity(ParteRepresentante)!,
    TipoMigracaoAcervo: getTableDefFromEntity(TipoMigracaoAcervo)!,
    Tramitacao: getTableDefFromEntity(Tramitacao)!,
    TipoLocalidadeEspecializada: getTableDefFromEntity(TipoLocalidadeEspecializada)!,
    EspecializadaDistribuidor: getTableDefFromEntity(EspecializadaDistribuidor)!,
    ContatoMniTribunal: getTableDefFromEntity(ContatoMniTribunal)!,
    Equipe: getTableDefFromEntity(Equipe)!,
    AcervoEquipeApoio: getTableDefFromEntity(AcervoEquipeApoio)!,
    Materia: getTableDefFromEntity(Materia)!,
    ModeloFormularioProcessoAdministrativoEstadoModeloFormulario: getTableDefFromEntity(ModeloFormularioProcessoAdministrativoEstadoModeloFormulario)!,
    TipoDispensa: getTableDefFromEntity(TipoDispensa)!,
    Publicacao: getTableDefFromEntity(Publicacao)!,
    DocumentoRascunho: getTableDefFromEntity(DocumentoRascunho)!,
    CodigoUnidadeProtocoladora: getTableDefFromEntity(CodigoUnidadeProtocoladora)!,
    AssuntoLocal: getTableDefFromEntity(AssuntoLocal)!,
    Perfil: getTableDefFromEntity(Perfil)!,
    Carga: getTableDefFromEntity(Carga)!,
    DispensaGenerica: getTableDefFromEntity(DispensaGenerica)!,
    TempInformacaoComplementar: getTableDefFromEntity(TempInformacaoComplementar)!,
    Classificacao: getTableDefFromEntity(Classificacao)!,
    ReciboTj: getTableDefFromEntity(ReciboTj)!,
    DocumentoRascunhoEstado: getTableDefFromEntity(DocumentoRascunhoEstado)!,
    ComunicacaoOutroParametro: getTableDefFromEntity(ComunicacaoOutroParametro)!,
    ModeloFormulario: getTableDefFromEntity(ModeloFormulario)!,
    DescricaoSolicitacao: getTableDefFromEntity(DescricaoSolicitacao)!,
    Capitulo: getTableDefFromEntity(Capitulo)!,
    RelacionamentoProcessual: getTableDefFromEntity(RelacionamentoProcessual)!,
    RepresentanteJudicial: getTableDefFromEntity(RepresentanteJudicial)!,
    DocumentoRascunhoProvidenciaJuridica: getTableDefFromEntity(DocumentoRascunhoProvidenciaJuridica)!,
    Tema: getTableDefFromEntity(Tema)!,
    TipoProcessoAdministrativo: getTableDefFromEntity(TipoProcessoAdministrativo)!,
    TipoAcao: getTableDefFromEntity(TipoAcao)!,
    TipoAtividade: getTableDefFromEntity(TipoAtividade)!,
    ConsumoProcesso: getTableDefFromEntity(ConsumoProcesso)!,
    DocumentoAcordoContencioso: getTableDefFromEntity(DocumentoAcordoContencioso)!,
    UsuarioPerfil: getTableDefFromEntity(UsuarioPerfil)!,
    OrgaoJulgador: getTableDefFromEntity(OrgaoJulgador)!,
    TipoComunicacao: getTableDefFromEntity(TipoComunicacao)!,
    TipoAcaoTipoProcessoAdministrativo: getTableDefFromEntity(TipoAcaoTipoProcessoAdministrativo)!,
    TipoDocumentoPessoa: getTableDefFromEntity(TipoDocumentoPessoa)!,
    EstadoProcessoAdministrativo: getTableDefFromEntity(EstadoProcessoAdministrativo)!,
    EspecializadaAssistente: getTableDefFromEntity(EspecializadaAssistente)!,
    DocumentoComunicacao: getTableDefFromEntity(DocumentoComunicacao)!,
    Magistrado: getTableDefFromEntity(Magistrado)!,
    TipoInstancia: getTableDefFromEntity(TipoInstancia)!,
    Despacho: getTableDefFromEntity(Despacho)!,
    RaioXJuridico: getTableDefFromEntity(RaioXJuridico)!,
    TipoLogradouro: getTableDefFromEntity(TipoLogradouro)!,
    PalavraChave: getTableDefFromEntity(PalavraChave)!,
    InteressadoConsultivo: getTableDefFromEntity(InteressadoConsultivo)!,
    OutroParametroComunicacao: getTableDefFromEntity(OutroParametroComunicacao)!,
    TipoModalidadeRelacionamentoPessoal: getTableDefFromEntity(TipoModalidadeRelacionamentoPessoal)!,
    Especializada: getTableDefFromEntity(Especializada)!,
    DocumentoAnexoRascunho: getTableDefFromEntity(DocumentoAnexoRascunho)!,
    TipoSolicitacao: getTableDefFromEntity(TipoSolicitacao)!,
    TipoModalidadeVinculacaoProcessual: getTableDefFromEntity(TipoModalidadeVinculacaoProcessual)!,
    DjeTribunal: getTableDefFromEntity(DjeTribunal)!,
    AcervoDestinatarioPa: getTableDefFromEntity(AcervoDestinatarioPa)!,
    TipoValorAdicional: getTableDefFromEntity(TipoValorAdicional)!,
    TipoAcervo: getTableDefFromEntity(TipoAcervo)!,
    TipoOrgaoJulgador: getTableDefFromEntity(TipoOrgaoJulgador)!,
    ProcessoAdministrativo: getTableDefFromEntity(ProcessoAdministrativo)!,
    TipoEspecializada: getTableDefFromEntity(TipoEspecializada)!,
    EquipeUsuario: getTableDefFromEntity(EquipeUsuario)!,
    TipoPolo: getTableDefFromEntity(TipoPolo)!,
    DecisaoJudicial: getTableDefFromEntity(DecisaoJudicial)!,
    PedidoComplementar: getTableDefFromEntity(PedidoComplementar)!,
    RelatorioDje: getTableDefFromEntity(RelatorioDje)!,
    DocumentoProcessoAdministrativo: getTableDefFromEntity(DocumentoProcessoAdministrativo)!,
    TipoPrazo: getTableDefFromEntity(TipoPrazo)!,
    DocumentoComunicacaoOutroParametro: getTableDefFromEntity(DocumentoComunicacaoOutroParametro)!,
    TipoSolicitacaoTipoProcessoAdministrativo: getTableDefFromEntity(TipoSolicitacaoTipoProcessoAdministrativo)!,
    HistoricoDistribuicaoAcervo: getTableDefFromEntity(HistoricoDistribuicaoAcervo)!,
    TipoRepresentante: getTableDefFromEntity(TipoRepresentante)!,
    FatorCorrecao: getTableDefFromEntity(FatorCorrecao)!,
    TipoRespostaCorreicao: getTableDefFromEntity(TipoRespostaCorreicao)!,
    HistoricoDistribuicaoEspecializada: getTableDefFromEntity(HistoricoDistribuicaoEspecializada)!,
    TipoDocumentoTipoProcessoAdministrativo: getTableDefFromEntity(TipoDocumentoTipoProcessoAdministrativo)!,
    MniTribunal: getTableDefFromEntity(MniTribunal)!,
    HistoricoUsuarioEspecializada: getTableDefFromEntity(HistoricoUsuarioEspecializada)!,
    Quesito: getTableDefFromEntity(Quesito)!,
    AcervoClassificacao: getTableDefFromEntity(AcervoClassificacao)!,
    Indexador: getTableDefFromEntity(Indexador)!,
    AfastamentoPessoa: getTableDefFromEntity(AfastamentoPessoa)!,
    Sysdiagrams: getTableDefFromEntity(Sysdiagrams)!,
    ProcessoJudicialOutroParametro: getTableDefFromEntity(ProcessoJudicialOutroParametro)!,
    Instancia: getTableDefFromEntity(Instancia)!,
    EstadoModeloFormulario: getTableDefFromEntity(EstadoModeloFormulario)!,
    InstanciaMniTribunal: getTableDefFromEntity(InstanciaMniTribunal)!,
    Protocolizacao: getTableDefFromEntity(Protocolizacao)!,
    Acordo: getTableDefFromEntity(Acordo)!,
    TipoDecisao: getTableDefFromEntity(TipoDecisao)!,
    SorteioCorreicao: getTableDefFromEntity(SorteioCorreicao)!,
    Localidade: getTableDefFromEntity(Localidade)!,
    TipoFaseJudicial: getTableDefFromEntity(TipoFaseJudicial)!,
    Competencia: getTableDefFromEntity(Competencia)!,
    AcessoRestritoFuncionalidadePerfil: getTableDefFromEntity(AcessoRestritoFuncionalidadePerfil)!,
    CorreicaoQuesito: getTableDefFromEntity(CorreicaoQuesito)!,
    AcervoMateria: getTableDefFromEntity(AcervoMateria)!,
    EspecializadaUsuarioNotificacao: getTableDefFromEntity(EspecializadaUsuarioNotificacao)!,
    TipoAcaoEstado: getTableDefFromEntity(TipoAcaoEstado)!,
    SorteioCorreicaoProcessoAdministrativo: getTableDefFromEntity(SorteioCorreicaoProcessoAdministrativo)!,
    RegistroTramitacao: getTableDefFromEntity(RegistroTramitacao)!,
    ModeloFormularioValor: getTableDefFromEntity(ModeloFormularioValor)!,
    Abreviatura: getTableDefFromEntity(Abreviatura)!,
    ConsumoTeorAvisoErro: getTableDefFromEntity(ConsumoTeorAvisoErro)!,
    SorteioCorreicaoProcessoAdministrativoQuesito: getTableDefFromEntity(SorteioCorreicaoProcessoAdministrativoQuesito)!,
    AcervoTema: getTableDefFromEntity(AcervoTema)!,
    DocumentoProtocolizacao: getTableDefFromEntity(DocumentoProtocolizacao)!,
    ClasseProcessual: getTableDefFromEntity(ClasseProcessual)!,
    AcessoRestritoFuncionalidadeUsuario: getTableDefFromEntity(AcessoRestritoFuncionalidadeUsuario)!,
    Confidencialidade: getTableDefFromEntity(Confidencialidade)!,
    Justificativa: getTableDefFromEntity(Justificativa)!,
    ElementoFilaCircular: getTableDefFromEntity(ElementoFilaCircular)!,
    RegistroMigracaoSicaj: getTableDefFromEntity(RegistroMigracaoSicaj)!,
    ProcessoVinculado: getTableDefFromEntity(ProcessoVinculado)!,
    PastaCaixaEntrada: getTableDefFromEntity(PastaCaixaEntrada)!,
    TabelaExitoTj: getTableDefFromEntity(TabelaExitoTj)!,
    AfastamentoPessoaUsuario: getTableDefFromEntity(AfastamentoPessoaUsuario)!,
    Feriado: getTableDefFromEntity(Feriado)!,
    AcessoRestritoFuncionalidade: getTableDefFromEntity(AcessoRestritoFuncionalidade)!,
    Acompanhamento: getTableDefFromEntity(Acompanhamento)!,
    Servico: getTableDefFromEntity(Servico)!,
    TipoAssociacao: getTableDefFromEntity(TipoAssociacao)!,
    Arquivo: getTableDefFromEntity(Arquivo)!,
    ProcessoAdministrativoProcessoAdministrativo: getTableDefFromEntity(ProcessoAdministrativoProcessoAdministrativo)!,
    Tribunal: getTableDefFromEntity(Tribunal)!,
    TipoAudiencia: getTableDefFromEntity(TipoAudiencia)!,
    Urgencia: getTableDefFromEntity(Urgencia)!,
    ServicoToken: getTableDefFromEntity(ServicoToken)!,
    HistoricoPrazo: getTableDefFromEntity(HistoricoPrazo)!,
    AssuntoProcessoJudicial: getTableDefFromEntity(AssuntoProcessoJudicial)!,
    RaizCnpjAcervo: getTableDefFromEntity(RaizCnpjAcervo)!,
    Atividade: getTableDefFromEntity(Atividade)!,
    FilaCircular: getTableDefFromEntity(FilaCircular)!,
    MotivoAssociacao: getTableDefFromEntity(MotivoAssociacao)!,
    Usuario: getTableDefFromEntity(Usuario)!,
    ConfidencialidadeEspecializada: getTableDefFromEntity(ConfidencialidadeEspecializada)!,
    TipoDocumentoProvidencia: getTableDefFromEntity(TipoDocumentoProvidencia)!,
    ProvidenciaJuridica: getTableDefFromEntity(ProvidenciaJuridica)!,
    ComplementoMovimentacaoJudicial: getTableDefFromEntity(ComplementoMovimentacaoJudicial)!,
    Audiencia: getTableDefFromEntity(Audiencia)!,
    MotivoArquivamento: getTableDefFromEntity(MotivoArquivamento)!,
    AvisoPendente: getTableDefFromEntity(AvisoPendente)!,
    Comunicacao: getTableDefFromEntity(Comunicacao)!,
    RespostaTj: getTableDefFromEntity(RespostaTj)!,
    CodigoExternoProcessoAdministrativo: getTableDefFromEntity(CodigoExternoProcessoAdministrativo)!,
    NaturezaIncidente: getTableDefFromEntity(NaturezaIncidente)!,
    ClassificacaoRelevancia: getTableDefFromEntity(ClassificacaoRelevancia)!,
    EstadoProcessoAdministrativoMotivoArquivamento: getTableDefFromEntity(EstadoProcessoAdministrativoMotivoArquivamento)!,
    DocumentoMovimentacaoJudicial: getTableDefFromEntity(DocumentoMovimentacaoJudicial)!,
    ItemAjuda: getTableDefFromEntity(ItemAjuda)!,
    SistemaOrigem: getTableDefFromEntity(SistemaOrigem)!,
    TipoProcedimentoSei: getTableDefFromEntity(TipoProcedimentoSei)!,
    DocumentoPessoa: getTableDefFromEntity(DocumentoPessoa)!,
    TipoInteressado: getTableDefFromEntity(TipoInteressado)!,
    ProcessoFisicoAssociado: getTableDefFromEntity(ProcessoFisicoAssociado)!,
    TipoAfastamento: getTableDefFromEntity(TipoAfastamento)!,
    Modelo: getTableDefFromEntity(Modelo)!,
    ProcedimentoSei: getTableDefFromEntity(ProcedimentoSei)!,
    EnderecoPessoa: getTableDefFromEntity(EnderecoPessoa)!,
    Interessado: getTableDefFromEntity(Interessado)!,
    TipoMovimentacaoNacional: getTableDefFromEntity(TipoMovimentacaoNacional)!,
    MemoriaCalculo: getTableDefFromEntity(MemoriaCalculo)!,
    PedidoComplementarProcessoAdministrativo: getTableDefFromEntity(PedidoComplementarProcessoAdministrativo)!,
    TipoDocumento: getTableDefFromEntity(TipoDocumento)!,
    ClassificacaoRecorrencia: getTableDefFromEntity(ClassificacaoRecorrencia)!,
    NotaVersao: getTableDefFromEntity(NotaVersao)!,
    EnderecoRepresentanteJudicial: getTableDefFromEntity(EnderecoRepresentanteJudicial)!,
    ProcessoJudicialHash: getTableDefFromEntity(ProcessoJudicialHash)!,
    MapeamentoAcervoSicaj: getTableDefFromEntity(MapeamentoAcervoSicaj)!,
    UnidadeSei: getTableDefFromEntity(UnidadeSei)!,
    Incidente: getTableDefFromEntity(Incidente)!,
    Entrega: getTableDefFromEntity(Entrega)!,
    TramitacaoAutomaticaAcervoTema: getTableDefFromEntity(TramitacaoAutomaticaAcervoTema)!,
    MapeamentoLocalidadeRegional: getTableDefFromEntity(MapeamentoLocalidadeRegional)!,
    UsuarioSei: getTableDefFromEntity(UsuarioSei)!,
    InstantaneoAvisoPendente: getTableDefFromEntity(InstantaneoAvisoPendente)!,
    TipoProvidenciaJuridica: getTableDefFromEntity(TipoProvidenciaJuridica)!,
    UnidadeSeiUsuarioSei: getTableDefFromEntity(UnidadeSeiUsuarioSei)!,
    ComunicacaoEstado: getTableDefFromEntity(ComunicacaoEstado)!,
    InterpretacaoSentenca: getTableDefFromEntity(InterpretacaoSentenca)!,
    Cda: getTableDefFromEntity(Cda)!,
    TipoIncidente: getTableDefFromEntity(TipoIncidente)!,
    ModeloTema: getTableDefFromEntity(ModeloTema)!,
    UsuarioPermitidoAcessarProcessoAdministrativoSigiloso: getTableDefFromEntity(UsuarioPermitidoAcessarProcessoAdministrativoSigiloso)!,
    TipoDocumentoMni: getTableDefFromEntity(TipoDocumentoMni)!,
    ValorAdicional: getTableDefFromEntity(ValorAdicional)!,
    RegistroEnvioComunicacao: getTableDefFromEntity(RegistroEnvioComunicacao)!,
    PredicaoEspecializadaMachineLearning: getTableDefFromEntity(PredicaoEspecializadaMachineLearning)!,
    AvisoPendenteOutroParametro: getTableDefFromEntity(AvisoPendenteOutroParametro)!,
    Solicitacao: getTableDefFromEntity(Solicitacao)!,
    MagistradoProcesso: getTableDefFromEntity(MagistradoProcesso)!,
    Acervo: getTableDefFromEntity(Acervo)!,
    ManifestacaoEstado: getTableDefFromEntity(ManifestacaoEstado)!,
    ManifestacaoProcessual: getTableDefFromEntity(ManifestacaoProcessual)!,
  };
};

export const allTables = () => bootstrapEntities();