// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { Pessoa } from './Pessoa.js';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';
import { TipoInteressadoConsultivo } from './TipoInteressadoConsultivo.js';

@Entity({ tableName: 'interessado_consultivo' })
export class InteressadoConsultivo {
  /**
   * Identificador do interessado consultivo
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador do processo administrativo
   * @remarks References dbo.processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_administrativo_id!: number;

  /**
   * Identificador da pessoa
   * @remarks References dbo.pessoa.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'pessoa', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  pessoa_id!: number;

  /**
   * @remarks References dbo.tipo_interessado_consultivo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tipo_interessado_consultivo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_interessado_consultivo_id?: number;

  @BelongsTo({ target: () => ProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  processoAdministrativo!: BelongsToReference<ProcessoAdministrativo>;

  @BelongsTo({ target: () => Pessoa, foreignKey: 'pessoa_id' })
  pessoa!: BelongsToReference<Pessoa>;

  @BelongsTo({ target: () => TipoInteressadoConsultivo, foreignKey: 'tipo_interessado_consultivo_id' })
  tipoInteressadoConsultivo!: BelongsToReference<TipoInteressadoConsultivo>;

}
