// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey } from 'metal-orm';

@Entity({ tableName: 'interpretacao_sentenca' })
export class InterpretacaoSentenca {
  /**
   * Identificador da interpretação sentença
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Conclusão de um processo ou julgamento por um Tribunal
   */
  @Column(col.varchar(255))
  sentenca?: string;

  /**
   * Armazena informações sobre o estado de ativação de uma determinada interpretação de sentença.
   */
  @Column(col.varchar(255))
  estado_ativo?: string;

  /**
   * Armazena informações sobre o estado passivo de uma determinada interpretação de sentença.
   */
  @Column(col.varchar(255))
  estado_passivo?: string;

  /**
   * Um código que governe o processo de interpretação de sentenças
   */
  @Column(col.int())
  codigo_movimento?: number;

  /**
   * Código de lei para a interpretação de sentença dentro do Brasil
   */
  @Column(col.int())
  codigo_pai_nacional?: number;

}
