// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column } from 'metal-orm';

@Entity({ tableName: 'item_ajuda' })
export class ItemAjuda {
  /**
   * Identificador do item ajuda
   * @remarks Auto-increment identity column
   */
  @Column(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Armazena um código que identifica cada item de ajuda.
   */
  @Column(col.unique(col.notNull(col.varchar(150))))
  identificador!: string;

  /**
   * Armazena o conteúdo HTML formatado que fornece informações detalhadas.
   */
  @Column(col.notNull(col.text()))
  html!: string;

}
