// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsToMany, ManyToManyCollection } from 'metal-orm';
import { MagistradoProcesso } from './MagistradoProcesso';
import { ProcessoJudicial } from './ProcessoJudicial';

@Entity({ tableName: 'magistrado' })
export class Magistrado {
  /**
   * Identificador do magistrado
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Armazena o nome de um magistrado, que é um termo utilizado para se referir a um juiz ou membro do poder judiciário.
   */
  @Column(col.text())
  nome?: string;

  /**
   * Armazena o número de Cadastro de Pessoa Física
   */
  @Column(col.varchar(11))
  cpf?: string;

  @BelongsToMany({ target: () => ProcessoJudicial, pivotTable: () => MagistradoProcesso, pivotForeignKeyToRoot: 'magistrado_id', pivotForeignKeyToTarget: 'processo_judicial_id' })
  processoJudicials!: ManyToManyCollection<ProcessoJudicial>;

}
