// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, HasManyCollection } from 'metal-orm';
import { Acordo } from './Acordo.js';
import { DocumentoAcordoContencioso } from './DocumentoAcordoContencioso.js';
import { DocumentoProcessoAdministrativo } from './DocumentoProcessoAdministrativo.js';
import { Estado } from './Estado.js';
import { ManifestacaoEstado } from './ManifestacaoEstado.js';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';
import { RegistroTramitacao } from './RegistroTramitacao.js';
import { TipoManifestacao } from './TipoManifestacao.js';

@Entity({ tableName: 'manifestacao' })
export class Manifestacao {
  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * @remarks References dbo.acordo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'acordo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  acordo_id!: number;

  /**
   * @remarks References dbo.tipo_manifestacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'tipo_manifestacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_manifestacao_id!: number;

  @Column(col.notNull(col.varchar(255)))
  remetente!: string;

  /**
   * @remarks References dbo.documento_processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'documento_processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  documento_processo_administrativo_id?: number;

  /**
   * @defaultValue (getdate())
   */
  @Column(col.defaultRaw(col.notNull(col.datetime<Date>()), '(getdate())'))
  created!: Date;

  /**
   * @defaultValue (getdate())
   */
  @Column(col.defaultRaw(col.notNull(col.datetime<Date>()), '(getdate())'))
  modified!: Date;

  /**
   * @remarks References dbo.processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_administrativo_id?: number;

  /**
   * @remarks References dbo.estado.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'estado', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  estado_id?: number;

  /**
   * @remarks References dbo.registro_tramitacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'registro_tramitacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  registro_tramitacao_id?: number;

  /**
   * @remarks References dbo.documento_acordo_contencioso.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'documento_acordo_contencioso', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  documento_acordo_contencioso_id?: number;

  @BelongsTo({ target: () => Acordo, foreignKey: 'acordo_id' })
  acordo?: Acordo;

  @BelongsTo({ target: () => TipoManifestacao, foreignKey: 'tipo_manifestacao_id' })
  tipoManifestacao?: TipoManifestacao;

  @BelongsTo({ target: () => DocumentoProcessoAdministrativo, foreignKey: 'documento_processo_administrativo_id' })
  documentoProcessoAdministrativo?: DocumentoProcessoAdministrativo;

  @BelongsTo({ target: () => ProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  processoAdministrativo?: ProcessoAdministrativo;

  @BelongsTo({ target: () => Estado, foreignKey: 'estado_id' })
  estado?: Estado;

  @BelongsTo({ target: () => RegistroTramitacao, foreignKey: 'registro_tramitacao_id' })
  registroTramitacao?: RegistroTramitacao;

  @BelongsTo({ target: () => DocumentoAcordoContencioso, foreignKey: 'documento_acordo_contencioso_id' })
  documentoAcordoContencioso?: DocumentoAcordoContencioso;

  @HasMany({ target: () => ManifestacaoEstado, foreignKey: 'manifestacao_id' })
  manifestacoesEstado!: HasManyCollection<ManifestacaoEstado>;

}
