// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { Estado } from './Estado.js';
import { Manifestacao } from './Manifestacao.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'manifestacao_estado' })
export class ManifestacaoEstado {
  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * @remarks References dbo.manifestacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'manifestacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  manifestacao_id!: number;

  /**
   * @remarks References dbo.estado.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'estado', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  estado_id!: number;

  @Column(col.notNull(col.datetime<Date>()))
  data_alteracao!: Date;

  @Column(col.text())
  descricao_estado?: string;

  /**
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id?: number;

  @BelongsTo({ target: () => Manifestacao, foreignKey: 'manifestacao_id' })
  manifestacao!: BelongsToReference<Manifestacao>;

  @BelongsTo({ target: () => Estado, foreignKey: 'estado_id' })
  estado!: BelongsToReference<Estado>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario!: BelongsToReference<Usuario>;

}
