// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { Especializada } from './Especializada';
import { Localidade } from './Localidade';

@Entity({ tableName: 'mapeamento_localidade_regional' })
export class MapeamentoLocalidadeRegional {
  /**
   * Identificador do mapeamento localidade regional
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador da localidade
   * @remarks References dbo.localidade.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'localidade', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  localidade_id?: number;

  /**
   * Identificador da especializada regional
   * @remarks References dbo.especializada.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'especializada', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  especializada_regional_id?: number;

  @BelongsTo({ target: () => Localidade, foreignKey: 'localidade_id' })
  localidade!: BelongsToReference<Localidade>;

  @BelongsTo({ target: () => Especializada, foreignKey: 'especializada_regional_id' })
  especializadaRegional!: BelongsToReference<Especializada>;

}
