// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, BelongsToReference, ManyToManyCollection } from 'metal-orm';
import { Acervo } from './Acervo';
import { AcervoMateria } from './AcervoMateria';
import { Especializada } from './Especializada';
import { EspecializadaMateria } from './EspecializadaMateria';
import { ProcessoAdministrativo } from './ProcessoAdministrativo';
import { Tema } from './Tema';
import { TipoProcessoAdministrativo } from './TipoProcessoAdministrativo';

@Entity({ tableName: 'materia' })
export class Materia {
  /**
   * Identificador da matéria
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Armazena o nome associado a uma matéria
   */
  @Column(col.notNull(col.varchar(255)))
  nome!: string;

  /**
   * Identificador do tipo do processo administrativo
   * @defaultValue ((1))
   * @remarks References dbo.tipo_processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.defaultRaw(col.int(), '((1))'), { table: 'tipo_processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_processo_administrativo_id?: number;

  @BelongsToMany({ target: () => Especializada, pivotTable: () => EspecializadaMateria, pivotForeignKeyToRoot: 'materia_id', pivotForeignKeyToTarget: 'especializada_id' })
  especializadas!: ManyToManyCollection<Especializada>;

  @BelongsToMany({ target: () => Tema, pivotTable: () => Tema, pivotForeignKeyToRoot: 'materia_id', pivotForeignKeyToTarget: 'parent_id' })
  temas!: ManyToManyCollection<Tema>;

  @BelongsToMany({ target: () => Acervo, pivotTable: () => AcervoMateria, pivotForeignKeyToRoot: 'materia_id', pivotForeignKeyToTarget: 'acervo_id' })
  acervos!: ManyToManyCollection<Acervo>;

  @HasMany({ target: () => EspecializadaMateria, foreignKey: 'materia_id' })
  especializadaMaterias!: HasManyCollection<EspecializadaMateria>;

  @BelongsTo({ target: () => TipoProcessoAdministrativo, foreignKey: 'tipo_processo_administrativo_id' })
  tipoProcessoAdministrativo!: BelongsToReference<TipoProcessoAdministrativo>;

  @HasMany({ target: () => ProcessoAdministrativo, foreignKey: 'materia_id' })
  processoAdministrativos!: HasManyCollection<ProcessoAdministrativo>;

  @HasMany({ target: () => AcervoMateria, foreignKey: 'materia_id' })
  acervoMaterias!: HasManyCollection<AcervoMateria>;

}
