// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, BelongsToReference, ManyToManyCollection } from 'metal-orm';
import { Capitulo } from './Capitulo';
import { Especializada } from './Especializada';
import { ModeloTema } from './ModeloTema';
import { Tema } from './Tema';
import { TipoAcao } from './TipoAcao';
import { TipoAtividade } from './TipoAtividade';
import { TipoDocumento } from './TipoDocumento';
import { TipoSolicitacao } from './TipoSolicitacao';
import { TramitacaoAutomaticaAcervoTema } from './TramitacaoAutomaticaAcervoTema';
import { Usuario } from './Usuario';

@Entity({ tableName: 'modelo' })
export class Modelo {
  /**
   * Identificador do modelo
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador do usuário
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id!: number;

  /**
   * Armazena o nome associado a um modelo específico
   */
  @Column(col.notNull(col.text()))
  nome!: string;

  /**
   * Identificador da especializada
   * @remarks References dbo.especializada.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'especializada', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  especializada_id?: number;

  /**
   * Identificador do tipo da ação
   * @remarks References dbo.tipo_acao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tipo_acao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_acao_id?: number;

  /**
   * Armazena informações adicionais que descrevem o modelo em detalhes
   */
  @Column(col.notNull(col.text()))
  descricao!: string;

  /**
   * Caracteriza o modelo
   */
  @Column(col.notNull(col.boolean()))
  modelo_sistema!: boolean;

  /**
   * Caracteriza o modelo
   */
  @Column(col.notNull(col.boolean()))
  modelo_geral!: boolean;

  /**
   * Identificador do tipo de solicitação
   * @remarks References dbo.tipo_solicitacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tipo_solicitacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_solicitacao_id?: number;

  /**
   * Identificador do tipo do documento
   * @remarks References dbo.tipo_documento.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tipo_documento', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_documento_id?: number;

  /**
   * Caracteriza o modelo
   */
  @Column(col.notNull(col.boolean()))
  modelo_padrao!: boolean;

  /**
   * Identificador do tipo de atividade
   * @remarks References dbo.tipo_atividade.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tipo_atividade', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_atividade_id?: number;

  /**
   * Caracteriza o modelo
   */
  @Column(col.boolean())
  modelo_proprio?: boolean;

  /**
   * @defaultValue (getdate())
   */
  @Column(col.defaultRaw(col.notNull(col.datetime<Date>()), '(getdate())'))
  created!: Date;

  @Column(col.datetime<Date>())
  modified?: Date;

  @Column(col.boolean())
  modelo_todos_temas?: boolean;

  @BelongsToMany({ target: () => Capitulo, pivotTable: () => Capitulo, pivotForeignKeyToRoot: 'modelo_id', pivotForeignKeyToTarget: 'parent_id' })
  capitulos!: ManyToManyCollection<Capitulo>;

  @BelongsToMany({ target: () => Tema, pivotTable: () => ModeloTema, pivotForeignKeyToRoot: 'modelo_id', pivotForeignKeyToTarget: 'tema_id' })
  temas!: ManyToManyCollection<Tema>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario!: BelongsToReference<Usuario>;

  @BelongsTo({ target: () => Especializada, foreignKey: 'especializada_id' })
  especializada!: BelongsToReference<Especializada>;

  @BelongsTo({ target: () => TipoAcao, foreignKey: 'tipo_acao_id' })
  tipoAcao!: BelongsToReference<TipoAcao>;

  @BelongsTo({ target: () => TipoSolicitacao, foreignKey: 'tipo_solicitacao_id' })
  tipoSolicitacao!: BelongsToReference<TipoSolicitacao>;

  @BelongsTo({ target: () => TipoDocumento, foreignKey: 'tipo_documento_id' })
  tipoDocumento!: BelongsToReference<TipoDocumento>;

  @BelongsTo({ target: () => TipoAtividade, foreignKey: 'tipo_atividade_id' })
  tipoAtividade!: BelongsToReference<TipoAtividade>;

  @HasMany({ target: () => TramitacaoAutomaticaAcervoTema, foreignKey: 'modelo_id' })
  tramitacaoAutomaticaAcervoTemas!: HasManyCollection<TramitacaoAutomaticaAcervoTema>;

  @HasMany({ target: () => ModeloTema, foreignKey: 'modelo_id' })
  modeloTemas!: HasManyCollection<ModeloTema>;

}
