// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, HasManyCollection, BelongsToReference } from 'metal-orm';
import { Especializada } from './Especializada';
import { ModeloFormularioProcessoAdministrativo } from './ModeloFormularioProcessoAdministrativo';
import { Usuario } from './Usuario';

@Entity({ tableName: 'modelo_formulario' })
export class ModeloFormulario {
  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  @Column(col.notNull(col.varchar(255)))
  nome!: string;

  /**
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  criador_id!: number;

  @Column(col.notNull(col.text()))
  json!: string;

  /**
   * @defaultValue ((1))
   */
  @Column(col.defaultRaw(col.notNull(col.boolean()), '((1))'))
  ativo!: boolean;

  /**
   * @defaultValue ((0))
   */
  @Column(col.defaultRaw(col.notNull(col.boolean()), '((0))'))
  importar_valores!: boolean;

  @Column(col.notNull(col.datetime<Date>()))
  created!: Date;

  @Column(col.notNull(col.datetime<Date>()))
  modified!: Date;

  /**
   * @remarks References dbo.especializada.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'especializada', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  especializada_id?: number;

  @HasMany({ target: () => ModeloFormularioProcessoAdministrativo, foreignKey: 'modelo_formulario_id' })
  modelosFormulariosProcessosAdministrativos!: HasManyCollection<ModeloFormularioProcessoAdministrativo>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'criador_id' })
  criador!: BelongsToReference<Usuario>;

  @BelongsTo({ target: () => Especializada, foreignKey: 'especializada_id' })
  especializada!: BelongsToReference<Especializada>;

}
