// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsToMany, HasManyCollection, ManyToManyCollection } from 'metal-orm';
import { EstadoProcessoAdministrativo } from './EstadoProcessoAdministrativo.js';
import { EstadoProcessoAdministrativoMotivoArquivamento } from './EstadoProcessoAdministrativoMotivoArquivamento.js';

@Entity({ tableName: 'motivo_arquivamento' })
export class MotivoArquivamento {
  /**
   * Id do motivo de arquivamento
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Nome do motivo de arquivamento
   */
  @Column(col.notNull(col.varchar(255)))
  nome!: string;

  @BelongsToMany({ target: () => EstadoProcessoAdministrativo, pivotTable: () => EstadoProcessoAdministrativoMotivoArquivamento, pivotForeignKeyToRoot: 'motivo_arquivamento_id', pivotForeignKeyToTarget: 'estado_processo_administrativo_id' })
  estadosProcessosAdministrativos!: ManyToManyCollection<EstadoProcessoAdministrativo>;

  @HasMany({ target: () => EstadoProcessoAdministrativoMotivoArquivamento, foreignKey: 'motivo_arquivamento_id' })
  estadosProcessosAdministrativosMotivosArquivamentos!: HasManyCollection<EstadoProcessoAdministrativoMotivoArquivamento>;

}
