// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey } from 'metal-orm';

@Entity({ tableName: 'movimentacao_judicial' })
export class MovimentacaoJudicial {
  /**
   * Identificador da movimentação judicial
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Data e hora da movimentação judicial
   */
  @Column(col.notNull(col.datetime<Date>()))
  data_hora!: Date;

  /**
   * Armazena uma descrição que detalha uma determinada movimentação judicial em um processo legal
   */
  @Column(col.text())
  descricao?: string;

  /**
   * Código de lei para a movimentação judicial de sentença abrangente ou referência primária dentro do Brasil
   */
  @Column(col.int())
  codigo_pai_nacional?: number;

  /**
   * Armazena um código associado a uma movimentação judicial específica em um processo legal
   */
  @Column(col.int())
  codigo_movimento?: number;

  /**
   * Armazena um código que serve para identificar de maneira exclusiva cada movimentação judicial registrada no sistema
   */
  @Column(col.text())
  identificador_movimento?: string;

  /**
   * Classifica o nível de sigilo
   */
  @Column(col.boolean())
  nivel_sigilo?: boolean;

  /**
   * Cadastro Nacional de Justiça do Tribunal com Movimentação Judicial
   */
  @Column(col.notNull(col.varchar(20)))
  cnj!: string;

  /**
   * Data e hora do download
   */
  @Column(col.datetime<Date>())
  data_hora_download?: Date;

  /**
   * Identificador do processo judicial
   */
  @Column(col.int())
  processo_judicial_id?: number;

  /**
   * Código de lei para a movimentação judicial de sentença dentro do Brasil
   */
  @Column(col.int())
  codigo_nacional?: number;

  /**
   * Tecnologia que transforma dados em uma sequência alfanumérico fixo
   */
  @Column(col.varchar(32))
  hash?: string;

}
