// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column } from 'metal-orm';

@Entity({ tableName: 'natureza' })
export class Natureza {
  /**
   * Identificador da natureza
   */
  @Column(col.notNull(col.int()))
  id!: number;

  /**
   * Armazena uma descrição que identifica uma natureza
   */
  @Column(col.text())
  descricao?: string;

}
