// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, HasManyCollection } from 'metal-orm';
import { Comunicacao } from './Comunicacao';
import { ProcessoJudicial } from './ProcessoJudicial';

@Entity({ tableName: 'nivel_sigilo' })
export class NivelSigilo {
  /**
   * Identificador do nível de sigilo
   */
  @PrimaryKey(col.notNull(col.int()))
  id!: number;

  /**
   * Armazena o nome associado a um nível de sigilo específico
   */
  @Column(col.varchar(50))
  nome?: string;

  /**
   * Armazena uma descrição que fornece informações adicionais sobre um nível de sigilo específico
   */
  @Column(col.text())
  descricao?: string;

  @HasMany({ target: () => ProcessoJudicial, foreignKey: 'nivel_sigilo_id' })
  processosJudiciais!: HasManyCollection<ProcessoJudicial>;

  @HasMany({ target: () => Comunicacao, foreignKey: 'nivel_sigilo_id' })
  comunicacoes!: HasManyCollection<Comunicacao>;

}
