// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, BelongsToReference, ManyToManyCollection } from 'metal-orm';
import { Especializada } from './Especializada';
import { MniTribunal } from './MniTribunal';
import { PredicaoOrgaoJulgadorEspecializada } from './PredicaoOrgaoJulgadorEspecializada';
import { ProcessoJudicial } from './ProcessoJudicial';
import { TipoOrgaoJulgador } from './TipoOrgaoJulgador';

@Entity({ tableName: 'orgao_julgador' })
export class OrgaoJulgador {
  /**
   * Identificador do orgão julgador
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador do local do tribunal
   */
  @Column(col.varchar(50))
  id_local_tribunal?: string;

  /**
   * Identificador do tribunal
   * @remarks References dbo.mni_tribunal.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'mni_tribunal', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tribunal_id?: number;

  /**
   * Nome do orgão
   */
  @Column(col.varchar(500))
  nome_orgao?: string;

  /**
   * Armazena informações relacionadas à instância ou esfera de jurisdição a que um órgão julgador específico pertence
   * @remarks References dbo.tipo_orgao_julgador.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.varchar(4), { table: 'tipo_orgao_julgador', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  instancia?: string;

  /**
   * Número identificador da IBGE do município
   */
  @Column(col.int())
  codigo_municipio_ibge?: number;

  @BelongsToMany({ target: () => Especializada, pivotTable: () => PredicaoOrgaoJulgadorEspecializada, pivotForeignKeyToRoot: 'orgao_julgador_id', pivotForeignKeyToTarget: 'especializada_id' })
  especializadas!: ManyToManyCollection<Especializada>;

  @HasMany({ target: () => PredicaoOrgaoJulgadorEspecializada, foreignKey: 'orgao_julgador_id' })
  predicaoOrgaoJulgadorEspecializadas!: HasManyCollection<PredicaoOrgaoJulgadorEspecializada>;

  @HasMany({ target: () => ProcessoJudicial, foreignKey: 'orgao_julgador_id' })
  processoJudicials!: HasManyCollection<ProcessoJudicial>;

  @BelongsTo({ target: () => MniTribunal, foreignKey: 'tribunal_id' })
  tribunal!: BelongsToReference<MniTribunal>;

  @BelongsTo({ target: () => TipoOrgaoJulgador, foreignKey: 'instancia' })
  dboTipoOrgaoJulgador!: BelongsToReference<TipoOrgaoJulgador>;

}
