// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { DocumentoComunicacao } from './DocumentoComunicacao';

@Entity({ tableName: 'outro_parametro_documento_comunicacao' })
export class OutroParametroDocumentoComunicacao {
  /**
   * Identificador outro parâmetro documento comunicação
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Nome para Parametro documento Comunicação
   */
  @Column(col.text())
  nome?: string;

  /**
   * Armazena o valor.
   */
  @Column(col.text())
  valor?: string;

  /**
   * Identificador do Documento Comunicação vinculado
   * @remarks References dbo.documento_comunicacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'documento_comunicacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  documento_comunicacao_id?: number;

  @BelongsTo({ target: () => DocumentoComunicacao, foreignKey: 'documento_comunicacao_id' })
  documentoComunicacao!: BelongsToReference<DocumentoComunicacao>;

}
