// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsToMany, ManyToManyCollection } from 'metal-orm';
import { PedidoComplementarProcessoAdministrativo } from './PedidoComplementarProcessoAdministrativo';
import { ProcessoAdministrativo } from './ProcessoAdministrativo';

@Entity({ tableName: 'pedido_complementar' })
export class PedidoComplementar {
  /**
   * Identificador do pedido complementar
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Nome do pedido complementar
   */
  @Column(col.notNull(col.varchar(500)))
  nome!: string;

  @BelongsToMany({ target: () => ProcessoAdministrativo, pivotTable: () => PedidoComplementarProcessoAdministrativo, pivotForeignKeyToRoot: 'pedido_complementar_id', pivotForeignKeyToTarget: 'processo_administrativo_id' })
  processosAdministrativos!: ManyToManyCollection<ProcessoAdministrativo>;

}
