// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsToMany, ManyToManyCollection, Tree, TreeParent, TreeChildren } from 'metal-orm';
import { AcessoRestritoFuncionalidade } from './AcessoRestritoFuncionalidade';
import { AcessoRestritoFuncionalidadePerfil } from './AcessoRestritoFuncionalidadePerfil';
import { Usuario } from './Usuario';
import { UsuarioPerfil } from './UsuarioPerfil';

@Tree({ parentKey: 'parent_id', leftKey: 'lft', rightKey: 'rght' })
@Entity({ tableName: 'perfil' })
export class Perfil {
  /**
   * Identificador do perfil
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador parent
   * @remarks References dbo.perfil.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'perfil', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  parent_id?: number;

  /**
   * Nome do perfil
   */
  @Column(col.notNull(col.text()))
  nome!: string;

  /**
   * Valor a esquerda.
   */
  @Column(col.int())
  lft?: number;

  /**
   * Valor a direita.
   */
  @Column(col.int())
  rght?: number;

  @BelongsToMany({ target: () => Usuario, pivotTable: () => UsuarioPerfil, pivotForeignKeyToRoot: 'perfil_id', pivotForeignKeyToTarget: 'usuario_id' })
  usuarios!: ManyToManyCollection<Usuario>;

  @BelongsToMany({ target: () => AcessoRestritoFuncionalidade, pivotTable: () => AcessoRestritoFuncionalidadePerfil, pivotForeignKeyToRoot: 'perfil_id', pivotForeignKeyToTarget: 'acesso_restrito_funcionalidade_id' })
  acessosRestritosFuncionalidades!: ManyToManyCollection<AcessoRestritoFuncionalidade>;

  @TreeParent()
  parent?: Perfil;

  @TreeChildren()
  perfis?: Perfil[];

}
