// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { MotivoAssociacao } from './MotivoAssociacao.js';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';
import { TipoAssociacao } from './TipoAssociacao.js';

@Entity({ tableName: 'processo_administrativo_processo_administrativo' })
export class ProcessoAdministrativoProcessoAdministrativo {
  /**
   * Identificador do processo administrativo
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador do processo administrativo associado
   * @remarks References dbo.processo_administrativo.id (on delete CASCADE, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'processo_administrativo', column: 'id', onDelete: 'CASCADE', onUpdate: 'NO ACTION' }))
  processo_administrativo_associado_id?: number;

  /**
   * Se refere a um código ou número exclusivo atribuído a um processo administrativo específico. Esse ID é usado para identificar e rastrear o processo
   */
  @Column(col.notNull(col.int()))
  processo_administrativo_id!: number;

  /**
   * Identificador do tipo de associação do processo administrativo
   * @remarks References dbo.tipo_associacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'tipo_associacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_associacao_id!: number;

  /**
   * refere-se ao identificador do tipo de associação
   * @remarks References dbo.motivo_associacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'motivo_associacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  motivo_associacao_id?: number;

  /**
   * Número físico representa o valor financeiro associado a perdas tangíveis, como despesas médicas, danos à propriedade ou perda de renda
   */
  @Column(col.varchar(30))
  numero_fisico?: string;

  @BelongsTo({ target: () => ProcessoAdministrativo, foreignKey: 'processo_administrativo_associado_id' })
  processoAdministrativoAssociado?: ProcessoAdministrativo;

  @BelongsTo({ target: () => TipoAssociacao, foreignKey: 'tipo_associacao_id' })
  tipoAssociacao?: TipoAssociacao;

  @BelongsTo({ target: () => MotivoAssociacao, foreignKey: 'motivo_associacao_id' })
  motivoAssociacao?: MotivoAssociacao;

}
