// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { ProcessoJudicial } from './ProcessoJudicial.js';
import { TipoModalidadeVinculacaoProcessual } from './TipoModalidadeVinculacaoProcessual.js';

@Entity({ tableName: 'processo_vinculado' })
export class ProcessoVinculado {
  /**
   * Identificador do processo vinculado
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador do processo judicial
   * @remarks References dbo.processo_judicial.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'processo_judicial', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_judicial_id!: number;

  /**
   * Refere-se ao número do processo administrativo vinculado
   */
  @Column(col.notNull(col.varchar(20)))
  numero_processo!: string;

  /**
   * Identificador do tipo de vinculada ao processo judicial
   * @remarks References dbo.tipo_modalidade_vinculacao_processual.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.varchar(2), { table: 'tipo_modalidade_vinculacao_processual', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_modalidade_vinculacao_processual_id?: string;

  /**
   * Identificador do processo judicial
   * @remarks References dbo.processo_judicial.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'processo_judicial', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_judicial_vinculado_id?: number;

  @BelongsTo({ target: () => ProcessoJudicial, foreignKey: 'processo_judicial_id' })
  processoJudicial?: ProcessoJudicial;

  @BelongsTo({ target: () => TipoModalidadeVinculacaoProcessual, foreignKey: 'tipo_modalidade_vinculacao_processual_id' })
  tipoModalidadeVinculacaoProcessual?: TipoModalidadeVinculacaoProcessual;

  @BelongsTo({ target: () => ProcessoJudicial, foreignKey: 'processo_judicial_vinculado_id' })
  processoJudicialVinculado?: ProcessoJudicial;

}
