// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { MotivoAssociacao } from './MotivoAssociacao';
import { ProcessoAdministrativo } from './ProcessoAdministrativo';
import { TipoAssociacao } from './TipoAssociacao';

@Entity({ tableName: 'processo_fisico_associado' })
export class ProcessoFisicoAssociado {
  /**
   * Identificador do processo físico associado
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador do processo físico associado
   * @remarks References dbo.processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_administrativo_id!: number;

  /**
   * Refere-se ao número do processo físico associado
   */
  @Column(col.notNull(col.varchar(100)))
  numero!: string;

  /**
   * Refere-se identificador do tipo de associação
   * @remarks References dbo.tipo_associacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'tipo_associacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_associacao_id!: number;

  /**
   * identificação do motivo de associação
   * @remarks References dbo.motivo_associacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'motivo_associacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  motivo_associacao_id?: number;

  @BelongsTo({ target: () => ProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  processoAdministrativo!: BelongsToReference<ProcessoAdministrativo>;

  @BelongsTo({ target: () => TipoAssociacao, foreignKey: 'tipo_associacao_id' })
  tipoAssociacao!: BelongsToReference<TipoAssociacao>;

  @BelongsTo({ target: () => MotivoAssociacao, foreignKey: 'motivo_associacao_id' })
  motivoAssociacao!: BelongsToReference<MotivoAssociacao>;

}
