// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { ProcessoJudicial } from './ProcessoJudicial';

@Entity({ tableName: 'processo_judicial_outro_numero' })
export class ProcessoJudicialOutroNumero {
  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Se refere ao outro número exclusivo atribuído a um processo judicial
   */
  @Column(col.notNull(col.text()))
  numero!: string;

  /**
   * @remarks References dbo.processo_judicial.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'processo_judicial', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_judicial_id!: number;

  @BelongsTo({ target: () => ProcessoJudicial, foreignKey: 'processo_judicial_id' })
  processoJudicial!: BelongsToReference<ProcessoJudicial>;

}
