// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { ProvidenciaJuridica } from './ProvidenciaJuridica.js';
import { Solicitacao } from './Solicitacao.js';

@Entity({ tableName: 'providencia_juridica_solicitacao' })
export class ProvidenciaJuridicaSolicitacao {
  /**
   * Identificador da providência jurídica
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador da solitação
   * @remarks References dbo.solicitacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'solicitacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  solicitacao_id!: number;

  /**
   * Identificador da providência jurídica
   * @remarks References dbo.providencia_juridica.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'providencia_juridica', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  providencia_juridica_id!: number;

  @BelongsTo({ target: () => Solicitacao, foreignKey: 'solicitacao_id' })
  solicitacao?: Solicitacao;

  @BelongsTo({ target: () => ProvidenciaJuridica, foreignKey: 'providencia_juridica_id' })
  providenciaJuridica?: ProvidenciaJuridica;

}
