// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, BelongsToReference, ManyToManyCollection } from 'metal-orm';
import { Comunicacao } from './Comunicacao';
import { DocumentoAnexoRascunho } from './DocumentoAnexoRascunho';
import { DocumentoProcessoAdministrativo } from './DocumentoProcessoAdministrativo';
import { DocumentoRascunho } from './DocumentoRascunho';
import { DocumentoRascunhoProvidenciaJuridica } from './DocumentoRascunhoProvidenciaJuridica';
import { Estado } from './Estado';
import { HistoricoPrazo } from './HistoricoPrazo';
import { ProvidenciaJuridicaSolicitacao } from './ProvidenciaJuridicaSolicitacao';
import { Solicitacao } from './Solicitacao';
import { TipoProvidenciaJuridica } from './TipoProvidenciaJuridica';
import { Usuario } from './Usuario';

@Entity({ tableName: 'providencia_juridica' })
export class ProvidenciaJuridica {
  /**
   * Identificador providência jurídica
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * É a comuniacão da providencia jurídica
   * @remarks References dbo.comunicacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'comunicacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  comunicacao_id?: number;

  /**
   * São medidas que o juiz, eventualmente, deve tomar logo após a resposta do réu e que se destinam a encerrar a fase postulatória do processo e a preparar a fase saneadora.
   */
  @Column(col.text())
  descricao?: string;

  /**
   * Identificador do tipo de providência jurídica
   * @remarks References dbo.tipo_providencia_juridica.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'tipo_providencia_juridica', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_providencia_juridica_id!: number;

  /**
   * Se refere a um código ou número exclusivo atribuído a um processo administrativo específico.
   */
  @Column(col.int())
  processo_administrativo_id?: number;

  /**
   * Algo que está em funcionamento, operação ou está em um estado de atividade
   * @defaultValue ((1))
   */
  @Column(col.defaultRaw(col.boolean(), '((1))'))
  ativa?: boolean;

  /**
   * ID do estado
   * @remarks References dbo.estado.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'estado', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  estado_id?: number;

  /**
   * Identificador do usuário
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id?: number;

  /**
   * Momento específico em que algo foi originado, produzido ou criado
   */
  @Column(col.datetime<Date>())
  data_criacao?: Date;

  /**
   * Se refere ao momento em que uma ação, decisão ou transação entra em vigor ou se torna efetiva
   */
  @Column(col.date<Date>())
  data_efetivacao?: Date;

  /**
   * É o período de tempo definido para a realização de uma tarefa
   */
  @Column(col.date<Date>())
  prazo?: Date;

  @BelongsToMany({ target: () => Solicitacao, pivotTable: () => ProvidenciaJuridicaSolicitacao, pivotForeignKeyToRoot: 'providencia_juridica_id', pivotForeignKeyToTarget: 'solicitacao_id' })
  solicitacaos!: ManyToManyCollection<Solicitacao>;

  @BelongsToMany({ target: () => DocumentoRascunho, pivotTable: () => DocumentoRascunhoProvidenciaJuridica, pivotForeignKeyToRoot: 'providencia_juridica_id', pivotForeignKeyToTarget: 'documento_rascunho_id' })
  documentoRascunhos!: ManyToManyCollection<DocumentoRascunho>;

  @HasMany({ target: () => DocumentoAnexoRascunho, foreignKey: 'providencia_juridica_id' })
  documentoAnexoRascunhos!: HasManyCollection<DocumentoAnexoRascunho>;

  @HasMany({ target: () => DocumentoProcessoAdministrativo, foreignKey: 'providencia_juridica_id' })
  documentoProcessoAdministrativos!: HasManyCollection<DocumentoProcessoAdministrativo>;

  @HasMany({ target: () => HistoricoPrazo, foreignKey: 'providencia_juridica_id' })
  historicoPrazos!: HasManyCollection<HistoricoPrazo>;

  @BelongsTo({ target: () => Comunicacao, foreignKey: 'comunicacao_id' })
  comunicacao!: BelongsToReference<Comunicacao>;

  @BelongsTo({ target: () => TipoProvidenciaJuridica, foreignKey: 'tipo_providencia_juridica_id' })
  tipoProvidenciaJuridica!: BelongsToReference<TipoProvidenciaJuridica>;

  @BelongsTo({ target: () => Estado, foreignKey: 'estado_id' })
  estado!: BelongsToReference<Estado>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario!: BelongsToReference<Usuario>;

}
