// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, BelongsToReference, ManyToManyCollection } from 'metal-orm';
import { Correicao } from './Correicao';
import { CorreicaoQuesito } from './CorreicaoQuesito';
import { SorteioCorreicaoProcessoAdministrativoQuesito } from './SorteioCorreicaoProcessoAdministrativoQuesito';
import { Usuario } from './Usuario';

@Entity({ tableName: 'quesito' })
export class Quesito {
  /**
   * Id do quesito
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Quesito é uma questão sobre a qual se espera uma resposta ou esclarecimento. É uma indagação que pede uma opinião ou um juízo
   */
  @Column(col.notNull(col.varchar(255)))
  descricao!: string;

  /**
   * Id do usuário
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id!: number;

  /**
   * Criado
   * @defaultValue (getdate())
   */
  @Column(col.defaultRaw(col.notNull(col.datetime<Date>()), '(getdate())'))
  created!: Date;

  /**
   * Modificado
   * @defaultValue (getdate())
   */
  @Column(col.defaultRaw(col.notNull(col.datetime<Date>()), '(getdate())'))
  modified!: Date;

  @BelongsToMany({ target: () => Correicao, pivotTable: () => CorreicaoQuesito, pivotForeignKeyToRoot: 'quesito_id', pivotForeignKeyToTarget: 'correicao_id' })
  correicaos!: ManyToManyCollection<Correicao>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario!: BelongsToReference<Usuario>;

  @HasMany({ target: () => CorreicaoQuesito, foreignKey: 'quesito_id' })
  correicaoQuesitos!: HasManyCollection<CorreicaoQuesito>;

  @HasMany({ target: () => SorteioCorreicaoProcessoAdministrativoQuesito, foreignKey: 'quesito_id' })
  sorteioCorreicaoProcessoAdministrativoQuesitos!: HasManyCollection<SorteioCorreicaoProcessoAdministrativoQuesito>;

}
