// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { ProcessoJudicial } from './ProcessoJudicial';

@Entity({ tableName: 'raio_x_juridico' })
export class RaioXJuridico {
  /**
   * Identificador do raio x jurídico
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Resultado no Json
   */
  @Column(col.text())
  resultado_json?: string;

  /**
   * Referem-se ao registro combinado de uma data específica e do horário correspondente em que um evento, ação ou atividade ocorre ou ocorreu
   */
  @Column(col.notNull(col.datetime<Date>()))
  data_hora!: Date;

  /**
   * identificador do processo judicial
   * @remarks References dbo.processo_judicial.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'processo_judicial', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_judicial_id!: number;

  @BelongsTo({ target: () => ProcessoJudicial, foreignKey: 'processo_judicial_id' })
  processoJudicial!: BelongsToReference<ProcessoJudicial>;

}
