// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { RespostaTj } from './RespostaTj.js';

@Entity({ tableName: 'recibo_tj' })
export class ReciboTj {
  /**
   * Identificador do recibo TJ
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Refere-se ao identificado no qual tem a resposta do TJ
   * @remarks References dbo.resposta_tj.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'resposta_tj', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  resposta_tj_id?: number;

  /**
   * sistema numérico que usa apenas dois dígitos, 0 e 1, para representar informações.
   */
  @Column(col.blob())
  binario?: Buffer;

  @BelongsTo({ target: () => RespostaTj, foreignKey: 'resposta_tj_id' })
  respostaTj!: BelongsToReference<RespostaTj>;

}
