// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { ProcessoJudicial } from './ProcessoJudicial';

@Entity({ tableName: 'registro_migracao_sicaj' })
export class RegistroMigracaoSicaj {
  /**
   * Id do registro migração sicaj
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador do processo judicial
   * @remarks References dbo.processo_judicial.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'processo_judicial', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_judicial_id?: number;

  /**
   * Referem-se ao registro combinado de uma data específica e do horário correspondente em que um evento, ação ou atividade ocorre ou ocorreu.
   */
  @Column(col.datetime<Date>())
  data_hora?: Date;

  /**
   * Dados do Json
   */
  @Column(col.text())
  dados_json?: string;

  @BelongsTo({ target: () => ProcessoJudicial, foreignKey: 'processo_judicial_id' })
  processoJudicial!: BelongsToReference<ProcessoJudicial>;

}
