// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey } from 'metal-orm';

@Entity({ tableName: 'relatorio_dje' })
export class RelatorioDje {
  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  @Column(col.varchar(50))
  numero_comunicacao?: string;

  @Column(col.notNull(col.varchar(20)))
  numero_processo!: string;

  @Column(col.notNull(col.varchar(50)))
  instancia!: string;

  @Column(col.notNull(col.varchar(200)))
  tribunal_origem!: string;

  @Column(col.varchar(20))
  tipo_comunicacao?: string;

  @Column(col.datetime<Date>())
  data_comunicacao?: Date;

  @Column(col.datetime<Date>())
  data_final_ciencia?: Date;

  @Column(col.datetime<Date>())
  data_ciente?: Date;

  @Column(col.varchar(150))
  sistema_processo?: string;

  @Column(col.varchar(30))
  id_aviso?: string;

  @Column(col.varchar(3))
  jtr?: string;

  @Column(col.boolean())
  ciente?: boolean;

  @Column(col.int())
  aviso_pendente_id?: number;

  @Column(col.int())
  processo_judicial_id?: number;

  @Column(col.int())
  mni_tribunal_id?: number;

  /**
   * @defaultValue (getdate())
   */
  @Column(col.defaultRaw(col.datetime<Date>(), '(getdate())'))
  created_at?: Date;

}
