// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, ManyToManyCollection } from 'metal-orm';
import { EnderecoRepresentanteJudicial } from './EnderecoRepresentanteJudicial.js';
import { Parte } from './Parte.js';
import { ParteRepresentante } from './ParteRepresentante.js';
import { TipoRepresentante } from './TipoRepresentante.js';

@Entity({ tableName: 'representante_judicial' })
export class RepresentanteJudicial {
  /**
   * Id do representante judicial
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * É o código ou identificador exclusivo atribuído ao documento principal em um conjunto de documentos relacionados.
   */
  @Column(col.varchar(50))
  numero_documento_principal?: string;

  /**
   * Termo para identificar representante judicial
   */
  @Column(col.varchar(500))
  nome?: string;

  /**
   * É um ato legal em que uma pessoa é oficialmente notificada ou convocada para comparecer a um tribunal
   */
  @Column(col.boolean())
  intimacao?: boolean;

  /**
   * Id do representante
   * @remarks References dbo.tipo_representante.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.varchar(1), { table: 'tipo_representante', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_representante_id?: string;

  /**
   * Refere-se ao ato de registrar o representante judicial
   */
  @Column(col.text())
  inscricao?: string;

  @BelongsToMany({ target: () => Parte, pivotTable: () => ParteRepresentante, pivotForeignKeyToRoot: 'representante_judicial_id', pivotForeignKeyToTarget: 'parte_id' })
  partes!: ManyToManyCollection<Parte>;

  @HasMany({ target: () => ParteRepresentante, foreignKey: 'representante_judicial_id' })
  partesRepresentante!: HasManyCollection<ParteRepresentante>;

  @BelongsTo({ target: () => TipoRepresentante, foreignKey: 'tipo_representante_id' })
  tipoRepresentante?: TipoRepresentante;

  @HasMany({ target: () => EnderecoRepresentanteJudicial, foreignKey: 'representante_judicial_id' })
  enderecosRepresentanteJudicial!: HasManyCollection<EnderecoRepresentanteJudicial>;

}
