// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { Equipe } from './Equipe.js';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'retorno_programado' })
export class RetornoProgramado {
  /**
   * Id do retorno programado
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * A data de retorno é a data em que alguém ou algo é esperado ou planejado para voltar a um estado anterior ou a um local específico após um período de ausência
   */
  @Column(col.notNull(col.date<Date>()))
  data_retorno!: Date;

  /**
   * descrição do identificador do processo administrativo
   * @remarks References dbo.processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_administrativo_id!: number;

  /**
   * Refere-se ao identificador do criador
   */
  @Column(col.notNull(col.int()))
  criador_id!: number;

  /**
   * Id do destinátario
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  destinatario_id?: number;

  /**
   * É o id da equipe
   * @remarks References dbo.equipe.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'equipe', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  equipe_id?: number;

  /**
   * sistema ou processo em que uma ação ou evento é agendado para ocorrer automaticamente em um momento específico no futuro.
   * @defaultValue ((1))
   */
  @Column(col.defaultRaw(col.notNull(col.boolean()), '((1))'))
  ativo!: boolean;

  @BelongsTo({ target: () => ProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  processoAdministrativo?: ProcessoAdministrativo;

  @BelongsTo({ target: () => Usuario, foreignKey: 'destinatario_id' })
  destinatario?: Usuario;

  @BelongsTo({ target: () => Equipe, foreignKey: 'equipe_id' })
  equipe?: Equipe;

}
