// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey } from 'metal-orm';

@Entity({ tableName: 'servico' })
export class Servico {
  /**
   * Identificador do serviço
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Nome do serviço
   */
  @Column(col.varchar(255))
  nome?: string;

  /**
   * URL do serviço
   */
  @Column(col.varchar(255))
  url?: string;

  /**
   * Tipo do serviço
   */
  @Column(col.varchar(10))
  tipo?: string;

  /**
   * Login para acessar o serviço
   */
  @Column(col.varchar(255))
  login?: string;

  /**
   * Senha do serviço
   */
  @Column(col.varchar(500))
  senha?: string;

  @Column(col.varchar(255))
  client_id?: string;

  @Column(col.varchar(255))
  client_secret?: string;

  @Column(col.varchar(255))
  token_url?: string;

}
