// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey } from 'metal-orm';

@Entity({ tableName: 'servico_token' })
export class ServicoToken {
  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  @Column(col.notNull(col.int()))
  servico_id!: number;

  @Column(col.notNull(col.text()))
  access_token!: string;

  @Column(col.text())
  refresh_token?: string;

  @Column(col.notNull(col.datetime<Date>()))
  expires_at!: Date;

  @Column(col.datetime<Date>())
  refresh_expires_at?: Date;

  @Column(col.notNull(col.int()))
  expires_in!: number;

  @Column(col.int())
  refresh_expires_in?: number;

  @Column(col.varchar(36))
  tenantid?: string;

  /**
   * @defaultValue (sysdatetime())
   */
  @Column(col.defaultRaw(col.datetime<Date>(), '(sysdatetime())'))
  created?: Date;

  /**
   * @defaultValue (sysdatetime())
   */
  @Column(col.defaultRaw(col.datetime<Date>(), '(sysdatetime())'))
  modified?: Date;

}
