// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsToMany, HasManyCollection, ManyToManyCollection } from 'metal-orm';
import { CodigoExterno } from './CodigoExterno.js';
import { ProcedimentoSei } from './ProcedimentoSei.js';

@Entity({ tableName: 'sistema_origem' })
export class SistemaOrigem {
  /**
   * Identificador do sistema de origem
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Nome do sistema de origem
   */
  @Column(col.notNull(col.text()))
  nome!: string;

  @BelongsToMany({ target: () => ProcedimentoSei, pivotTable: () => CodigoExterno, pivotForeignKeyToRoot: 'sistema_origem_id', pivotForeignKeyToTarget: 'procedimento_sei_id' })
  procedimentosSeis!: ManyToManyCollection<ProcedimentoSei>;

  @HasMany({ target: () => CodigoExterno, foreignKey: 'sistema_origem_id' })
  codigosExternos!: HasManyCollection<CodigoExterno>;

}
