// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { Quesito } from './Quesito';
import { SorteioCorreicaoProcessoAdministrativo } from './SorteioCorreicaoProcessoAdministrativo';
import { TipoRespostaCorreicao } from './TipoRespostaCorreicao';
import { Usuario } from './Usuario';

@Entity({ tableName: 'sorteio_correicao_processo_administrativo_quesito' })
export class SorteioCorreicaoProcessoAdministrativoQuesito {
  /**
   * Id do quesito do sorteio correição do processo administrativo
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * identificador do sorteio do processo administrativo
   * @remarks References dbo.sorteio_correicao_processo_administrativo.id (on delete CASCADE, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'sorteio_correicao_processo_administrativo', column: 'id', onDelete: 'CASCADE', onUpdate: 'NO ACTION' }))
  sorteio_correicao_processo_administrativo_id!: number;

  /**
   * Identificador do quesito
   * @remarks References dbo.quesito.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'quesito', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  quesito_id!: number;

  /**
   * Identificador da resposta da correição
   * @remarks References dbo.tipo_resposta_correicao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tipo_resposta_correicao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_resposta_correicao_id?: number;

  /**
   * Observação sobre o sorteio
   */
  @Column(col.varchar(255))
  observacao?: string;

  /**
   * Id do usuário
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id?: number;

  /**
   * Criado
   * @defaultValue (getdate())
   */
  @Column(col.defaultRaw(col.notNull(col.datetime<Date>()), '(getdate())'))
  created!: Date;

  /**
   * Modificado
   * @defaultValue (getdate())
   */
  @Column(col.defaultRaw(col.notNull(col.datetime<Date>()), '(getdate())'))
  modified!: Date;

  @BelongsTo({ target: () => SorteioCorreicaoProcessoAdministrativo, foreignKey: 'sorteio_correicao_processo_administrativo_id' })
  sorteioCorreicaoProcessoAdministrativo!: BelongsToReference<SorteioCorreicaoProcessoAdministrativo>;

  @BelongsTo({ target: () => Quesito, foreignKey: 'quesito_id' })
  quesito!: BelongsToReference<Quesito>;

  @BelongsTo({ target: () => TipoRespostaCorreicao, foreignKey: 'tipo_resposta_correicao_id' })
  tipoRespostaCorreicao!: BelongsToReference<TipoRespostaCorreicao>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario!: BelongsToReference<Usuario>;

}
