// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey } from 'metal-orm';

@Entity()
export class Sysdiagrams {
  @Column(col.notNull(col.varchar(255) /* TODO: review type sysname */))
  name!: any;

  @Column(col.notNull(col.int()))
  principal_id!: number;

  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  diagram_id!: number;

  @Column(col.int())
  version?: number;

  @Column(col.blob())
  definition?: Buffer;

}
