// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column } from 'metal-orm';

@Entity({ tableName: 'tabela_exito_tj' })
export class TabelaExitoTj {
  @Column(col.varchar(255))
  CNJ?: string;

  @Column(col.varchar(255))
  codigo_processo_antigo?: string;

  @Column(col.varchar(255))
  poloRJ?: string;

  @Column(col.float())
  dta_sentenca?: number;

  @Column(col.varchar(255))
  tp_sentenca?: string;

  @Column(col.float())
  codclasse?: number;

  @Column(col.varchar(255))
  descr_classe?: string;

  @Column(col.float())
  cod_assunto?: number;

  @Column(col.varchar(255))
  desc_ Assunto?: string;

  @Column(col.float())
  mes?: number;

  @Column(col.float())
  ano?: number;

  @Column(col.datetime<Date>())
  data_processamento?: Date;

  @Column(col.varchar(20))
  numero?: string;

}
