// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, ManyToManyCollection } from 'metal-orm';
import { Acervo } from './Acervo.js';
import { AcervoTema } from './AcervoTema.js';
import { ClassificacaoEspecializadaTema } from './ClassificacaoEspecializadaTema.js';
import { EspecializadaTema } from './EspecializadaTema.js';
import { Materia } from './Materia.js';
import { Modelo } from './Modelo.js';
import { ModeloTema } from './ModeloTema.js';
import { PalavraChave } from './PalavraChave.js';
import { PalavraChaveTema } from './PalavraChaveTema.js';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';
import { ProcessoAdministrativoTema } from './ProcessoAdministrativoTema.js';

@Entity({ tableName: 'tema' })
export class Tema {
  /**
   * Identificador do tema
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Nome do tema
   */
  @Column(col.notNull(col.varchar(255)))
  nome!: string;

  /**
   * Identificador do parente do tema
   * @remarks References dbo.tema.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tema', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  parent_id?: number;

  /**
   * Id da máteria
   * @remarks References dbo.materia.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'materia', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  materia_id!: number;

  /**
   * Usado para manter a estrutura em árvore. Esta coluna deve ser indexada.
   */
  @Column(col.int())
  lft?: number;

  /**
   * Usado para manter a estrutura em árvore.
   */
  @Column(col.int())
  rght?: number;

  /**
   * prefixo utilizado pra definição dos temas
   */
  @Column(col.varchar(50))
  cod_nivel?: string;

  /**
   * Refere-se ao peso do tema
   * @defaultValue ((1))
   */
  @Column(col.defaultRaw(col.int(), '((1))'))
  peso?: number;

  @BelongsToMany({ target: () => ProcessoAdministrativo, pivotTable: () => ProcessoAdministrativoTema, pivotForeignKeyToRoot: 'tema_id', pivotForeignKeyToTarget: 'processo_administrativo_id' })
  processosAdministrativo!: ManyToManyCollection<ProcessoAdministrativo>;

  @BelongsToMany({ target: () => PalavraChave, pivotTable: () => PalavraChaveTema, pivotForeignKeyToRoot: 'tema_id', pivotForeignKeyToTarget: 'palavra_chave_id' })
  palavrasChave!: ManyToManyCollection<PalavraChave>;

  @BelongsToMany({ target: () => Materia, pivotTable: () => Tema, pivotForeignKeyToRoot: 'parent_id', pivotForeignKeyToTarget: 'materia_id' })
  materias!: ManyToManyCollection<Materia>;

  @BelongsToMany({ target: () => Acervo, pivotTable: () => AcervoTema, pivotForeignKeyToRoot: 'tema_id', pivotForeignKeyToTarget: 'acervo_id' })
  acervos!: ManyToManyCollection<Acervo>;

  @BelongsToMany({ target: () => Modelo, pivotTable: () => ModeloTema, pivotForeignKeyToRoot: 'tema_id', pivotForeignKeyToTarget: 'modelo_id' })
  modelos!: ManyToManyCollection<Modelo>;

  @HasMany({ target: () => ClassificacaoEspecializadaTema, foreignKey: 'tema_id' })
  classificacoesEspecializadaTema!: HasManyCollection<ClassificacaoEspecializadaTema>;

  @HasMany({ target: () => ProcessoAdministrativoTema, foreignKey: 'tema_id' })
  processosAdministrativoTema!: HasManyCollection<ProcessoAdministrativoTema>;

  @HasMany({ target: () => EspecializadaTema, foreignKey: 'tema_id' })
  especializadasTema!: HasManyCollection<EspecializadaTema>;

  @HasMany({ target: () => PalavraChaveTema, foreignKey: 'tema_id' })
  palavrasChaveTema!: HasManyCollection<PalavraChaveTema>;

  @BelongsTo({ target: () => Tema, foreignKey: 'parent_id' })
  parent?: Tema;

  @HasMany({ target: () => Tema, foreignKey: 'parent_id' })
  temas!: HasManyCollection<Tema>;

  @BelongsTo({ target: () => Materia, foreignKey: 'materia_id' })
  materia?: Materia;

  @HasMany({ target: () => AcervoTema, foreignKey: 'tema_id' })
  acervosTema!: HasManyCollection<AcervoTema>;

  @HasMany({ target: () => ModeloTema, foreignKey: 'tema_id' })
  modelosTema!: HasManyCollection<ModeloTema>;

}
