// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsToMany, ManyToManyCollection } from 'metal-orm';
import { DocumentoPessoa } from './DocumentoPessoa';
import { Pessoa } from './Pessoa';

@Entity({ tableName: 'tipo_documento_pessoa' })
export class TipoDocumentoPessoa {
  /**
   * Identificador do documento pessoa
   */
  @PrimaryKey(col.notNull(col.varchar(10)))
  id!: string;

  /**
   * Refere-se ao documento da pessoa
   */
  @Column(col.notNull(col.varchar(80)))
  descricao!: string;

  @BelongsToMany({ target: () => Pessoa, pivotTable: () => DocumentoPessoa, pivotForeignKeyToRoot: 'tipo_documento_pessoa_id', pivotForeignKeyToTarget: 'pessoa_id' })
  pessoas!: ManyToManyCollection<Pessoa>;

}
