// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { TipoAcao } from './TipoAcao';
import { TipoProcessoAdministrativo } from './TipoProcessoAdministrativo';

@Entity({ tableName: 'tipo_acao_tipo_processo_administrativo' })
export class TipoAcaoTipoProcessoAdministrativo {
  /**
   * Id da ação do processo administrativo
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Tipo id da ação
   * @remarks References dbo.tipo_acao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'tipo_acao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_acao_id!: number;

  /**
   * Id do tipo do processo administrativo
   * @remarks References dbo.tipo_processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'tipo_processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_processo_administrativo_id!: number;

  @BelongsTo({ target: () => TipoAcao, foreignKey: 'tipo_acao_id' })
  tipoAcao!: BelongsToReference<TipoAcao>;

  @BelongsTo({ target: () => TipoProcessoAdministrativo, foreignKey: 'tipo_processo_administrativo_id' })
  tipoProcessoAdministrativo!: BelongsToReference<TipoProcessoAdministrativo>;

}
