// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { TipoDocumento } from './TipoDocumento.js';
import { TipoProcessoAdministrativo } from './TipoProcessoAdministrativo.js';

@Entity({ tableName: 'tipo_documento_tipo_processo_administrativo' })
export class TipoDocumentoTipoProcessoAdministrativo {
  /**
   * Id do tipo do processo administrativo
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Id do documento
   * @remarks References dbo.tipo_documento.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'tipo_documento', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_documento_id!: number;

  /**
   * Tipo processo administrativo
   * @remarks References dbo.tipo_processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'tipo_processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_processo_administrativo_id!: number;

  @BelongsTo({ target: () => TipoDocumento, foreignKey: 'tipo_documento_id' })
  tipoDocumento!: BelongsToReference<TipoDocumento>;

  @BelongsTo({ target: () => TipoProcessoAdministrativo, foreignKey: 'tipo_processo_administrativo_id' })
  tipoProcessoAdministrativo!: BelongsToReference<TipoProcessoAdministrativo>;

}
