// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, HasManyCollection } from 'metal-orm';
import { InteressadoConsultivo } from './InteressadoConsultivo';

@Entity({ tableName: 'tipo_interessado_consultivo' })
export class TipoInteressadoConsultivo {
  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  @Column(col.notNull(col.varchar(255)))
  nome!: string;

  @HasMany({ target: () => InteressadoConsultivo, foreignKey: 'tipo_interessado_consultivo_id' })
  interessadosConsultivos!: HasManyCollection<InteressadoConsultivo>;

}
