// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, HasManyCollection } from 'metal-orm';
import { Acervo } from './Acervo.js';

@Entity({ tableName: 'tipo_migracao_acervo' })
export class TipoMigracaoAcervo {
  /**
   * identificador do tipo de migração de acervo
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * status do tipo de migração de acervo. Ex: Sim(Todas), Não(Nenhuma) ou Parcialmente (Somente de PAs Digitais)
   */
  @Column(col.notNull(col.text()))
  nome!: string;

  /**
   * sigla do tipo de migração de acervo, Ex: S(Sim), N(Não) e P(Parcialmente)
   */
  @Column(col.notNull(col.varchar(1)))
  sigla!: string;

  @HasMany({ target: () => Acervo, foreignKey: 'tipo_migracao_acervo_id' })
  acervos!: HasManyCollection<Acervo>;

}
