// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, HasManyCollection } from 'metal-orm';
import { Especializada } from './Especializada';

@Entity({ tableName: 'tipo_especializada' })
export class TipoEspecializada {
  /**
   * Id da especializada
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Nome da especializada
   */
  @Column(col.varchar(50))
  nome?: string;

  /**
   * Descrição da especializada
   */
  @Column(col.text())
  descricao?: string;

  @HasMany({ target: () => Especializada, foreignKey: 'tipo_especializada_id' })
  especializadas!: HasManyCollection<Especializada>;

}
