// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, HasManyCollection } from 'metal-orm';
import { Parte } from './Parte.js';

@Entity({ tableName: 'tipo_modalidade_relacionamento_pessoal' })
export class TipoModalidadeRelacionamentoPessoal {
  /**
   * identificador do tipo de modalidade de relacionamento pessoal
   */
  @PrimaryKey(col.notNull(col.varchar(2)))
  id!: string;

  /**
   * descrição sobre o tipo de modalidade de relacionamento pessoal
   */
  @Column(col.varchar(120))
  descricao?: string;

  @HasMany({ target: () => Parte, foreignKey: 'tipo_modalidade_relacionamento_pessoal_id' })
  partes!: HasManyCollection<Parte>;

}
