// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column } from 'metal-orm';

@Entity({ tableName: 'tipo_logradouro' })
export class TipoLogradouro {
  /**
   * identificador do tipo de logradouro
   */
  @Column(col.notNull(col.varchar(50)))
  id!: string;

  /**
   * descrição do tipo de logradouro
   */
  @Column(col.text())
  descricao?: string;

}
