// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, HasManyCollection } from 'metal-orm';
import { AfastamentoPessoa } from './AfastamentoPessoa';

@Entity({ tableName: 'tipo_afastamento' })
export class TipoAfastamento {
  /**
   * Id do afastamento
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Nome do tipo de afastamento
   */
  @Column(col.notNull(col.text()))
  nome!: string;

  @HasMany({ target: () => AfastamentoPessoa, foreignKey: 'tipo_afastamento_id' })
  afastamentosPessoas!: HasManyCollection<AfastamentoPessoa>;

}
