// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, HasManyCollection } from 'metal-orm';
import { ProcessoAdministrativoProcessoAdministrativo } from './ProcessoAdministrativoProcessoAdministrativo.js';
import { ProcessoFisicoAssociado } from './ProcessoFisicoAssociado.js';

@Entity({ tableName: 'tipo_associacao' })
export class TipoAssociacao {
  /**
   * Identificador da associação
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Nome do tipo de associação
   */
  @Column(col.notNull(col.text()))
  nome!: string;

  @HasMany({ target: () => ProcessoAdministrativoProcessoAdministrativo, foreignKey: 'tipo_associacao_id' })
  processosAdministrativosProcessosAdministrativos!: HasManyCollection<ProcessoAdministrativoProcessoAdministrativo>;

  @HasMany({ target: () => ProcessoFisicoAssociado, foreignKey: 'tipo_associacao_id' })
  processosFisicosAssociados!: HasManyCollection<ProcessoFisicoAssociado>;

}
