// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { MniTribunal } from './MniTribunal';
import { TipoDocumentoMni } from './TipoDocumentoMni';
import { TipoProvidenciaJuridica } from './TipoProvidenciaJuridica';

@Entity({ tableName: 'tipo_documento_providencia' })
export class TipoDocumentoProvidencia {
  /**
   * Id da providência
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Documento mni id, é o identificador do documento MNI
   * @remarks References dbo.tipo_documento_mni.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tipo_documento_mni', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_documento_mni_id?: number;

  /**
   * Providencia jurídica id
   * @remarks References dbo.tipo_providencia_juridica.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tipo_providencia_juridica', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_providencia_juridica_id?: number;

  /**
   * Id do Tribunal
   * @remarks References dbo.mni_tribunal.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'mni_tribunal', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  mni_tribunal_id?: number;

  @BelongsTo({ target: () => TipoDocumentoMni, foreignKey: 'tipo_documento_mni_id' })
  tipoDocumentoMni!: BelongsToReference<TipoDocumentoMni>;

  @BelongsTo({ target: () => TipoProvidenciaJuridica, foreignKey: 'tipo_providencia_juridica_id' })
  tipoProvidenciaJuridica!: BelongsToReference<TipoProvidenciaJuridica>;

  @BelongsTo({ target: () => MniTribunal, foreignKey: 'mni_tribunal_id' })
  mniTribunal!: BelongsToReference<MniTribunal>;

}
