// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, HasManyCollection } from 'metal-orm';
import { Acervo } from './Acervo';
import { AfastamentoPessoa } from './AfastamentoPessoa';
import { Especializada } from './Especializada';

@Entity({ tableName: 'tipo_divisao_carga_trabalho' })
export class TipoDivisaoCargaTrabalho {
  /**
   * Identificador da divisão da carga de trabalho
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Nome da divisão de carga de carga de trabalho
   */
  @Column(col.notNull(col.varchar(500)))
  nome!: string;

  @HasMany({ target: () => Especializada, foreignKey: 'tipo_divisao_carga_trabalho_id' })
  especializadas!: HasManyCollection<Especializada>;

  @HasMany({ target: () => AfastamentoPessoa, foreignKey: 'tipo_divisao_carga_trabalho_id' })
  afastamentosPessoas!: HasManyCollection<AfastamentoPessoa>;

  @HasMany({ target: () => Acervo, foreignKey: 'tipo_divisao_carga_trabalho_id' })
  acervos!: HasManyCollection<Acervo>;

}
