// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey } from 'metal-orm';

@Entity({ tableName: 'tipo_movimentacao_nacional' })
export class TipoMovimentacaoNacional {
  /**
   * identificador do tipo de movimentação nacional
   */
  @PrimaryKey(col.notNull(col.int()))
  id!: number;

  /**
   * descrição do tipo de movimentação nacional. Ex:Abandono da causa, Acolhimento
   */
  @Column(col.notNull(col.text()))
  descricao!: string;

}
