// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, BelongsToReference, ManyToManyCollection } from 'metal-orm';
import { DocumentoAcordoContencioso } from './DocumentoAcordoContencioso';
import { DocumentoAnexoRascunho } from './DocumentoAnexoRascunho';
import { DocumentoProcessoAdministrativo } from './DocumentoProcessoAdministrativo';
import { DocumentoProtocolizacao } from './DocumentoProtocolizacao';
import { DocumentoRascunho } from './DocumentoRascunho';
import { Modelo } from './Modelo';
import { Protocolizacao } from './Protocolizacao';
import { TipoAcao } from './TipoAcao';
import { TipoDocumentoTipoProcessoAdministrativo } from './TipoDocumentoTipoProcessoAdministrativo';
import { TipoProcessoAdministrativo } from './TipoProcessoAdministrativo';

@Entity({ tableName: 'tipo_documento' })
export class TipoDocumento {
  /**
   * Id do tipo do documendo
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Nome do tipo de documento
   */
  @Column(col.notNull(col.varchar(63)))
  nome!: string;

  /**
   * Tipo do identificador do documento
   * @remarks References dbo.tipo_acao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tipo_acao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_acao_id?: number;

  @BelongsToMany({ target: () => TipoProcessoAdministrativo, pivotTable: () => TipoDocumentoTipoProcessoAdministrativo, pivotForeignKeyToRoot: 'tipo_documento_id', pivotForeignKeyToTarget: 'tipo_processo_administrativo_id' })
  tiposProcessosAdministrativos!: ManyToManyCollection<TipoProcessoAdministrativo>;

  @HasMany({ target: () => DocumentoRascunho, foreignKey: 'tipo_documento_id' })
  documentosRascunhos!: HasManyCollection<DocumentoRascunho>;

  @HasMany({ target: () => DocumentoAcordoContencioso, foreignKey: 'tipo_documento_id' })
  documentosAcordosContenciosos!: HasManyCollection<DocumentoAcordoContencioso>;

  @HasMany({ target: () => DocumentoAnexoRascunho, foreignKey: 'tipo_documento_id' })
  documentosAnexosRascunhos!: HasManyCollection<DocumentoAnexoRascunho>;

  @HasMany({ target: () => DocumentoProcessoAdministrativo, foreignKey: 'tipo_documento_id' })
  documentosProcessosAdministrativos!: HasManyCollection<DocumentoProcessoAdministrativo>;

  @HasMany({ target: () => Protocolizacao, foreignKey: 'tipo_documento_id' })
  protocolizacoes!: HasManyCollection<Protocolizacao>;

  @HasMany({ target: () => DocumentoProtocolizacao, foreignKey: 'tipo_documento_id' })
  documentosProtocolizacoes!: HasManyCollection<DocumentoProtocolizacao>;

  @HasMany({ target: () => Modelo, foreignKey: 'tipo_documento_id' })
  modelos!: HasManyCollection<Modelo>;

  @BelongsTo({ target: () => TipoAcao, foreignKey: 'tipo_acao_id' })
  tipoAcao!: BelongsToReference<TipoAcao>;

}
