// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsToMany, ManyToManyCollection } from 'metal-orm';
import { MniTribunal } from './MniTribunal';
import { OrgaoJulgador } from './OrgaoJulgador';

@Entity({ tableName: 'tipo_orgao_julgador' })
export class TipoOrgaoJulgador {
  /**
   * identificador do tipo do orgão julgador, pode ser uma sigla ou um número
   */
  @PrimaryKey(col.notNull(col.varchar(4)))
  id!: string;

  /**
   * nome do tipo do orgão julgador
   */
  @Column(col.varchar(40))
  nome?: string;

  /**
   * descrição do tipo do orgão julgador
   */
  @Column(col.varchar(255))
  descricao?: string;

  @BelongsToMany({ target: () => MniTribunal, pivotTable: () => OrgaoJulgador, pivotForeignKeyToRoot: 'instancia', pivotForeignKeyToTarget: 'tribunal_id' })
  mniTribunals!: ManyToManyCollection<MniTribunal>;

}
