// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, BelongsToReference, ManyToManyCollection } from 'metal-orm';
import { DocumentoRascunho } from './DocumentoRascunho';
import { Estado } from './Estado';
import { Modelo } from './Modelo';
import { TipoAcaoEstado } from './TipoAcaoEstado';
import { TipoAcaoTipoProcessoAdministrativo } from './TipoAcaoTipoProcessoAdministrativo';
import { TipoDocumento } from './TipoDocumento';
import { TipoProcessoAdministrativo } from './TipoProcessoAdministrativo';

@Entity({ tableName: 'tipo_acao' })
export class TipoAcao {
  /**
   * Id da ação
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Campo que contém nomes concisos de diferentes tipos de ações. Ela é usada para identificar e categorizar as ações.
   */
  @Column(col.notNull(col.varchar(500)))
  nome!: string;

  /**
   * RRefere-se à relevância ou importância da ação no contexto legal ou jurídico
   * @defaultValue ((1))
   */
  @Column(col.defaultRaw(col.int(), '((1))'))
  peso?: number;

  /**
   * Ação possui modelo
   * @defaultValue ((1))
   */
  @Column(col.defaultRaw(col.notNull(col.boolean()), '((1))'))
  possui_modelo!: boolean;

  /**
   * Refere ao código da ação
   */
  @Column(col.unique(col.notNull(col.varchar(3))))
  codigo!: string;

  /**
   * @remarks References dbo.tipo_acao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tipo_acao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  parent_id?: number;

  @Column(col.int())
  lft?: number;

  @Column(col.int())
  rght?: number;

  @BelongsToMany({ target: () => TipoProcessoAdministrativo, pivotTable: () => TipoAcaoTipoProcessoAdministrativo, pivotForeignKeyToRoot: 'tipo_acao_id', pivotForeignKeyToTarget: 'tipo_processo_administrativo_id' })
  tipoProcessoAdministrativos!: ManyToManyCollection<TipoProcessoAdministrativo>;

  @BelongsToMany({ target: () => Estado, pivotTable: () => TipoAcaoEstado, pivotForeignKeyToRoot: 'tipo_acao_id', pivotForeignKeyToTarget: 'estado_id' })
  estados!: ManyToManyCollection<Estado>;

  @HasMany({ target: () => DocumentoRascunho, foreignKey: 'tipo_acao_id' })
  documentoRascunhos!: HasManyCollection<DocumentoRascunho>;

  @BelongsTo({ target: () => TipoAcao, foreignKey: 'parent_id' })
  parent!: BelongsToReference<TipoAcao>;

  @HasMany({ target: () => TipoAcao, foreignKey: 'parent_id' })
  tipoAcaos!: HasManyCollection<TipoAcao>;

  @HasMany({ target: () => Modelo, foreignKey: 'tipo_acao_id' })
  modelos!: HasManyCollection<Modelo>;

  @HasMany({ target: () => TipoDocumento, foreignKey: 'tipo_acao_id' })
  tipoDocumentos!: HasManyCollection<TipoDocumento>;

}
