// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsToMany, HasManyCollection, ManyToManyCollection } from 'metal-orm';
import { Modelo } from './Modelo';
import { Solicitacao } from './Solicitacao';
import { TipoProcessoAdministrativo } from './TipoProcessoAdministrativo';
import { TipoSolicitacaoTipoProcessoAdministrativo } from './TipoSolicitacaoTipoProcessoAdministrativo';

@Entity({ tableName: 'tipo_solicitacao' })
export class TipoSolicitacao {
  /**
   * identificador do tipo de solicitação
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * nome do tipo de solicitação. Ex: Expedir Ofício
   */
  @Column(col.notNull(col.text()))
  nome!: string;

  /**
   * flag que indica se solicitação é externa
   */
  @Column(col.boolean())
  solicitacao_externa?: boolean;

  @BelongsToMany({ target: () => TipoProcessoAdministrativo, pivotTable: () => TipoSolicitacaoTipoProcessoAdministrativo, pivotForeignKeyToRoot: 'tipo_solicitacao_id', pivotForeignKeyToTarget: 'tipo_processo_administrativo_id' })
  tipoProcessoAdministrativos!: ManyToManyCollection<TipoProcessoAdministrativo>;

  @HasMany({ target: () => TipoSolicitacaoTipoProcessoAdministrativo, foreignKey: 'tipo_solicitacao_id' })
  tipoSolicitacaoTipoProcessoAdministrativos!: HasManyCollection<TipoSolicitacaoTipoProcessoAdministrativo>;

  @HasMany({ target: () => Modelo, foreignKey: 'tipo_solicitacao_id' })
  modelos!: HasManyCollection<Modelo>;

  @HasMany({ target: () => Solicitacao, foreignKey: 'tipo_solicitacao_id' })
  solicitacaos!: HasManyCollection<Solicitacao>;

}
