// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, HasManyCollection, BelongsToReference } from 'metal-orm';
import { Audiencia } from './Audiencia';
import { TipoProcessoAdministrativo } from './TipoProcessoAdministrativo';

@Entity({ tableName: 'tipo_audiencia' })
export class TipoAudiencia {
  /**
   * Id da audiencia
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * informações descritivas relacionadas às audiências
   */
  @Column(col.varchar(50))
  descricao?: string;

  /**
   * Identificador do processo administrativo
   * @remarks References dbo.tipo_processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'tipo_processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_processo_administrativo_id!: number;

  @BelongsTo({ target: () => TipoProcessoAdministrativo, foreignKey: 'tipo_processo_administrativo_id' })
  tipoProcessoAdministrativo!: BelongsToReference<TipoProcessoAdministrativo>;

  @HasMany({ target: () => Audiencia, foreignKey: 'tipo_audiencia_id' })
  audiencias!: HasManyCollection<Audiencia>;

}
