// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, HasManyCollection } from 'metal-orm';
import { Interessado } from './Interessado';

@Entity({ tableName: 'tipo_interessado' })
export class TipoInteressado {
  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  @Column(col.notNull(col.varchar(255)))
  nome!: string;

  @HasMany({ target: () => Interessado, foreignKey: 'tipo_interessado_id' })
  interessados!: HasManyCollection<Interessado>;

}
