// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { AcervoTema } from './AcervoTema';
import { Equipe } from './Equipe';
import { Instancia } from './Instancia';
import { Modelo } from './Modelo';
import { TipoProvidenciaJuridica } from './TipoProvidenciaJuridica';
import { Tramitacao } from './Tramitacao';

@Entity({ tableName: 'tramitacao_automatica_acervo_tema' })
export class TramitacaoAutomaticaAcervoTema {
  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * @remarks References dbo.tramitacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'tramitacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_tramitacao_id!: number;

  /**
   * @remarks References dbo.modelo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'modelo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  modelo_id!: number;

  /**
   * @remarks References dbo.equipe.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'equipe', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  equipe_id!: number;

  /**
   * @remarks References dbo.acervo_tema.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'acervo_tema', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  acervo_tema_id!: number;

  /**
   * @remarks References dbo.tipo_providencia_juridica.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'tipo_providencia_juridica', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_providencia_juridica_id!: number;

  @Column(col.int())
  prazo?: number;

  /**
   * @defaultValue (NULL)
   * @remarks References dbo.instancia.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.defaultRaw(col.int(), '(NULL)'), { table: 'instancia', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  instancia_id?: number;

  @BelongsTo({ target: () => Tramitacao, foreignKey: 'tipo_tramitacao_id' })
  tipoTramitacao!: BelongsToReference<Tramitacao>;

  @BelongsTo({ target: () => Modelo, foreignKey: 'modelo_id' })
  modelo!: BelongsToReference<Modelo>;

  @BelongsTo({ target: () => Equipe, foreignKey: 'equipe_id' })
  equipe!: BelongsToReference<Equipe>;

  @BelongsTo({ target: () => AcervoTema, foreignKey: 'acervo_tema_id' })
  acervoTema!: BelongsToReference<AcervoTema>;

  @BelongsTo({ target: () => TipoProvidenciaJuridica, foreignKey: 'tipo_providencia_juridica_id' })
  tipoProvidenciaJuridica!: BelongsToReference<TipoProvidenciaJuridica>;

  @BelongsTo({ target: () => Instancia, foreignKey: 'instancia_id' })
  instancia!: BelongsToReference<Instancia>;

}
