// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, HasManyCollection } from 'metal-orm';
import { RegistroTramitacao } from './RegistroTramitacao';
import { TramitacaoAutomaticaAcervoTema } from './TramitacaoAutomaticaAcervoTema';

@Entity({ tableName: 'tramitacao' })
export class Tramitacao {
  /**
   * identificador da tramitação
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * nome da tramitação
   */
  @Column(col.notNull(col.varchar(127)))
  nome!: string;

  /**
   * código da tramitação.Ex:ENC(Encaminhamento)
   */
  @Column(col.notNull(col.varchar(3)))
  codigo!: string;

  /**
   * flag que indica o bloqueio da comunicação
   */
  @Column(col.boolean())
  bloqueio_comunicacao?: boolean;

  /**
   * flag que indica o bloqueio da entrada
   */
  @Column(col.boolean())
  bloqueio_entrada?: boolean;

  @HasMany({ target: () => RegistroTramitacao, foreignKey: 'tramitacao_id' })
  registrosTramitacoes!: HasManyCollection<RegistroTramitacao>;

  @HasMany({ target: () => TramitacaoAutomaticaAcervoTema, foreignKey: 'tipo_tramitacao_id' })
  tramitacoesAutomaticasAcervosTemas!: HasManyCollection<TramitacaoAutomaticaAcervoTema>;

}
