// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey } from 'metal-orm';

@Entity({ tableName: 'tribunal' })
export class Tribunal {
  /**
   * identificador do tribunal
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * sigla do tribunal.Ex:TJRJ
   */
  @Column(col.varchar(10))
  sigla?: string;

  /**
   * descrição do tribunal.Ex:Tribunal de Justiça do Estado do RJ
   */
  @Column(col.notNull(col.varchar(255)))
  descricao!: string;

}
