// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { UnidadeSei } from './UnidadeSei.js';
import { UsuarioSei } from './UsuarioSei.js';

@Entity({ tableName: 'unidade_sei_usuario_sei' })
export class UnidadeSeiUsuarioSei {
  /**
   * identificador da relação entre unidade sei e usuário sei
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * chave estrangeira que aponta para unidade sei
   * @remarks References dbo.unidade_sei.id (on delete CASCADE, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'unidade_sei', column: 'id', onDelete: 'CASCADE', onUpdate: 'NO ACTION' }))
  unidade_sei_id?: number;

  /**
   * chave estrangeira que aponta para usuário sei
   * @remarks References dbo.usuario_sei.id (on delete CASCADE, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario_sei', column: 'id', onDelete: 'CASCADE', onUpdate: 'NO ACTION' }))
  usuario_sei_id?: number;

  @BelongsTo({ target: () => UnidadeSei, foreignKey: 'unidade_sei_id' })
  unidadeSei!: BelongsToReference<UnidadeSei>;

  @BelongsTo({ target: () => UsuarioSei, foreignKey: 'usuario_sei_id' })
  usuarioSei!: BelongsToReference<UsuarioSei>;

}
