// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsToMany, HasManyCollection, ManyToManyCollection } from 'metal-orm';
import { UnidadeSeiUsuarioSei } from './UnidadeSeiUsuarioSei';
import { UsuarioSei } from './UsuarioSei';

@Entity({ tableName: 'unidade_sei' })
export class UnidadeSei {
  /**
   * identificador da unidade sei
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * identificador da unidade
   */
  @Column(col.notNull(col.int()))
  id_unidade!: number;

  /**
   * sigla da unidade sei
   */
  @Column(col.notNull(col.varchar(30)))
  sigla!: string;

  /**
   * descrição da unidade sei
   */
  @Column(col.notNull(col.varchar(250)))
  descricao!: string;

  /**
   * flag que indica se foi protocolado
   */
  @Column(col.notNull(col.varchar(1)))
  sin_protocolo!: string;

  /**
   * flag que indica se foi arquivado
   */
  @Column(col.notNull(col.varchar(1)))
  sin_arquivamento!: string;

  /**
   * flag que indica se passou pela ouvidoria
   */
  @Column(col.notNull(col.varchar(1)))
  sin_ouvidoria!: string;

  @BelongsToMany({ target: () => UsuarioSei, pivotTable: () => UnidadeSeiUsuarioSei, pivotForeignKeyToRoot: 'unidade_sei_id', pivotForeignKeyToTarget: 'usuario_sei_id' })
  usuarioSeis!: ManyToManyCollection<UsuarioSei>;

  @HasMany({ target: () => UnidadeSeiUsuarioSei, foreignKey: 'unidade_sei_id' })
  unidadeSeiUsuarioSeis!: HasManyCollection<UnidadeSeiUsuarioSei>;

}
