// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, HasManyCollection } from 'metal-orm';
import { ProcessoAdministrativo } from './ProcessoAdministrativo';

@Entity({ tableName: 'urgencia' })
export class Urgencia {
  /**
   * identificador da urgência
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * nome da urgência.Ex:Normal, Urgente
   */
  @Column(col.notNull(col.text()))
  nome!: string;

  @HasMany({ target: () => ProcessoAdministrativo, foreignKey: 'urgencia_id' })
  processosAdministrativos!: HasManyCollection<ProcessoAdministrativo>;

}
