// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, BelongsToReference, ManyToManyCollection } from 'metal-orm';
import { Acervo } from './Acervo';
import { AcervoDestinatarioPa } from './AcervoDestinatarioPa';
import { AcessoRestritoFuncionalidade } from './AcessoRestritoFuncionalidade';
import { AcessoRestritoFuncionalidadeUsuario } from './AcessoRestritoFuncionalidadeUsuario';
import { Acordo } from './Acordo';
import { AfastamentoPessoa } from './AfastamentoPessoa';
import { AfastamentoPessoaUsuario } from './AfastamentoPessoaUsuario';
import { Audiencia } from './Audiencia';
import { Carga } from './Carga';
import { Comunicacao } from './Comunicacao';
import { ComunicacaoEstado } from './ComunicacaoEstado';
import { Correicao } from './Correicao';
import { Despacho } from './Despacho';
import { DocumentoAcordoContencioso } from './DocumentoAcordoContencioso';
import { DocumentoAnexoRascunho } from './DocumentoAnexoRascunho';
import { DocumentoProcessoAdministrativo } from './DocumentoProcessoAdministrativo';
import { DocumentoProcessoAdministrativoAcordo } from './DocumentoProcessoAdministrativoAcordo';
import { DocumentoRascunho } from './DocumentoRascunho';
import { DocumentoRascunhoEstado } from './DocumentoRascunhoEstado';
import { Entrega } from './Entrega';
import { Equipe } from './Equipe';
import { EquipeUsuario } from './EquipeUsuario';
import { Especializada } from './Especializada';
import { EspecializadaDistribuidor } from './EspecializadaDistribuidor';
import { EstadoProcessoAdministrativo } from './EstadoProcessoAdministrativo';
import { EstadoSolicitacao } from './EstadoSolicitacao';
import { HistoricoDistribuicaoAcervo } from './HistoricoDistribuicaoAcervo';
import { HistoricoDistribuicaoEspecializada } from './HistoricoDistribuicaoEspecializada';
import { HistoricoPrazo } from './HistoricoPrazo';
import { HistoricoUsuarioEspecializada } from './HistoricoUsuarioEspecializada';
import { ManifestacaoEstado } from './ManifestacaoEstado';
import { MarcadorDocumentoProcessoJudicial } from './MarcadorDocumentoProcessoJudicial';
import { Modelo } from './Modelo';
import { ModeloFormularioProcessoAdministrativo } from './ModeloFormularioProcessoAdministrativo';
import { ModeloFormularioProcessoAdministrativoEstadoModeloFormulario } from './ModeloFormularioProcessoAdministrativoEstadoModeloFormulario';
import { PastaCaixaEntrada } from './PastaCaixaEntrada';
import { Perfil } from './Perfil';
import { PreferenciaUsuario } from './PreferenciaUsuario';
import { ProcessoAdministrativo } from './ProcessoAdministrativo';
import { Protocolizacao } from './Protocolizacao';
import { ProvidenciaJuridica } from './ProvidenciaJuridica';
import { Quesito } from './Quesito';
import { RegistroTramitacao } from './RegistroTramitacao';
import { RetornoProgramado } from './RetornoProgramado';
import { Solicitacao } from './Solicitacao';
import { SorteioCorreicao } from './SorteioCorreicao';
import { SorteioCorreicaoProcessoAdministrativo } from './SorteioCorreicaoProcessoAdministrativo';
import { SorteioCorreicaoProcessoAdministrativoQuesito } from './SorteioCorreicaoProcessoAdministrativoQuesito';
import { UsuarioPerfil } from './UsuarioPerfil';
import { UsuarioPermitidoAcessarProcessoAdministrativoSigiloso } from './UsuarioPermitidoAcessarProcessoAdministrativoSigiloso';
import { ValorAdicional } from './ValorAdicional';

@Entity({ tableName: 'usuario' })
export class Usuario {
  /**
   * identificador do usuário
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * chave esrangeira que aponta para a especializada do usuário, pode não ter especializada pois o usuário acabou de ser criado no sistema
   * @remarks References dbo.especializada.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'especializada', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  especializada_id?: number;

  /**
   * nome completo do usuário
   */
  @Column(col.notNull(col.varchar(127)))
  nome!: string;

  /**
   * nome de login do usuário
   */
  @Column(col.unique(col.notNull(col.varchar(200))))
  login!: string;

  /**
   * cargo do usuário
   */
  @Column(col.notNull(col.varchar(127)))
  cargo!: string;

  /**
   * flag que mostra se o usuário é ativo ou não
   */
  @Column(col.notNull(col.boolean()))
  estado_inatividade!: boolean;

  /**
   * vînculo do usuário
   */
  @Column(col.varchar(63))
  vinculo?: string;

  /**
   * flag que mostra se cargo pode ser exibido
   */
  @Column(col.boolean())
  exibe_cargo?: boolean;

  /**
   * flag que mostra se vínculo pode ser exibido
   */
  @Column(col.boolean())
  exibe_vinculo?: boolean;

  /**
   * flag que mostra se matrícula pode ser exibida
   */
  @Column(col.boolean())
  exibe_matricula?: boolean;

  /**
   * flag que mostra se função pode ser exibida
   */
  @Column(col.boolean())
  exibe_funcao?: boolean;

  /**
   * função exercida pelo usuário
   */
  @Column(col.varchar(200))
  funcao?: string;

  /**
   * matrícula administrativa do usuário
   */
  @Column(col.varchar(200))
  matricula?: string;

  /**
   * abreviatura do nome do usuário
   */
  @Column(col.varchar(5))
  abreviatura?: string;

  /**
   * flag que indica que usuário é o ponto focal da especializada
   */
  @Column(col.boolean())
  ponto_focal?: boolean;

  @BelongsToMany({ target: () => Especializada, pivotTable: () => EspecializadaDistribuidor, pivotForeignKeyToRoot: 'distribuidor_id', pivotForeignKeyToTarget: 'especializada_id' })
  especializadas!: ManyToManyCollection<Especializada>;

  @BelongsToMany({ target: () => Perfil, pivotTable: () => UsuarioPerfil, pivotForeignKeyToRoot: 'usuario_id', pivotForeignKeyToTarget: 'perfil_id' })
  perfils!: ManyToManyCollection<Perfil>;

  @BelongsToMany({ target: () => RegistroTramitacao, pivotTable: () => Despacho, pivotForeignKeyToRoot: 'usuario_id', pivotForeignKeyToTarget: 'registro_tramitacao_id' })
  registroTramitacaos!: ManyToManyCollection<RegistroTramitacao>;

  @BelongsToMany({ target: () => Acervo, pivotTable: () => AcervoDestinatarioPa, pivotForeignKeyToRoot: 'destinatario_pa_id', pivotForeignKeyToTarget: 'acervo_id' })
  acervos!: ManyToManyCollection<Acervo>;

  @BelongsToMany({ target: () => Equipe, pivotTable: () => EquipeUsuario, pivotForeignKeyToRoot: 'usuario_id', pivotForeignKeyToTarget: 'equipe_id' })
  equipes!: ManyToManyCollection<Equipe>;

  @BelongsToMany({ target: () => AcessoRestritoFuncionalidade, pivotTable: () => AcessoRestritoFuncionalidadeUsuario, pivotForeignKeyToRoot: 'usuario_id', pivotForeignKeyToTarget: 'acesso_restrito_funcionalidade_id' })
  acessoRestritoFuncionalidades!: ManyToManyCollection<AcessoRestritoFuncionalidade>;

  @BelongsToMany({ target: () => AfastamentoPessoa, pivotTable: () => AfastamentoPessoaUsuario, pivotForeignKeyToRoot: 'usuario_id', pivotForeignKeyToTarget: 'afastamento_pessoa_id' })
  afastamentoPessoas!: ManyToManyCollection<AfastamentoPessoa>;

  @BelongsToMany({ target: () => ProcessoAdministrativo, pivotTable: () => UsuarioPermitidoAcessarProcessoAdministrativoSigiloso, pivotForeignKeyToRoot: 'usuario_id', pivotForeignKeyToTarget: 'processo_administrativo_id' })
  processoAdministrativos!: ManyToManyCollection<ProcessoAdministrativo>;

  @HasMany({ target: () => DocumentoProcessoAdministrativoAcordo, foreignKey: 'usuario_id' })
  documentoProcessoAdministrativoAcordos!: HasManyCollection<DocumentoProcessoAdministrativoAcordo>;

  @HasMany({ target: () => PreferenciaUsuario, foreignKey: 'usuario_id' })
  preferenciaUsuarios!: HasManyCollection<PreferenciaUsuario>;

  @HasMany({ target: () => EstadoSolicitacao, foreignKey: 'usuario_id' })
  estadoSolicitacaos!: HasManyCollection<EstadoSolicitacao>;

  @HasMany({ target: () => Correicao, foreignKey: 'usuario_id' })
  correicaos!: HasManyCollection<Correicao>;

  @HasMany({ target: () => MarcadorDocumentoProcessoJudicial, foreignKey: 'usuario_id' })
  marcadorDocumentoProcessoJudicials!: HasManyCollection<MarcadorDocumentoProcessoJudicial>;

  @HasMany({ target: () => ModeloFormularioProcessoAdministrativo, foreignKey: 'usuario_id' })
  modeloFormularioProcessoAdministrativos!: HasManyCollection<ModeloFormularioProcessoAdministrativo>;

  @HasMany({ target: () => RetornoProgramado, foreignKey: 'destinatario_id' })
  retornoProgramados!: HasManyCollection<RetornoProgramado>;

  @HasMany({ target: () => ModeloFormularioProcessoAdministrativoEstadoModeloFormulario, foreignKey: 'usuario_id' })
  modeloFormularioProcessoAdministrativoEstadoModeloFormularios!: HasManyCollection<ModeloFormularioProcessoAdministrativoEstadoModeloFormulario>;

  @HasMany({ target: () => DocumentoRascunho, foreignKey: 'usuario_id' })
  documentoRascunhos!: HasManyCollection<DocumentoRascunho>;

  @HasMany({ target: () => Carga, foreignKey: 'usuario_id' })
  cargas!: HasManyCollection<Carga>;

  @HasMany({ target: () => DocumentoRascunhoEstado, foreignKey: 'usuario_id' })
  documentoRascunhoEstados!: HasManyCollection<DocumentoRascunhoEstado>;

  @HasMany({ target: () => DocumentoAcordoContencioso, foreignKey: 'usuario_id' })
  documentoAcordoContenciosos!: HasManyCollection<DocumentoAcordoContencioso>;

  @HasMany({ target: () => EstadoProcessoAdministrativo, foreignKey: 'usuario_id' })
  estadoProcessoAdministrativos!: HasManyCollection<EstadoProcessoAdministrativo>;

  @HasMany({ target: () => DocumentoAnexoRascunho, foreignKey: 'usuario_id' })
  documentoAnexoRascunhos!: HasManyCollection<DocumentoAnexoRascunho>;

  @HasMany({ target: () => DocumentoProcessoAdministrativo, foreignKey: 'usuario_id' })
  documentoProcessoAdministrativos!: HasManyCollection<DocumentoProcessoAdministrativo>;

  @HasMany({ target: () => HistoricoDistribuicaoAcervo, foreignKey: 'usuario_acao_id' })
  historicoDistribuicaoAcervos!: HasManyCollection<HistoricoDistribuicaoAcervo>;

  @HasMany({ target: () => HistoricoDistribuicaoEspecializada, foreignKey: 'usuario_acao_id' })
  historicoDistribuicaoEspecializadas!: HasManyCollection<HistoricoDistribuicaoEspecializada>;

  @HasMany({ target: () => HistoricoUsuarioEspecializada, foreignKey: 'usuario_acao_id' })
  historicoUsuarioEspecializadas!: HasManyCollection<HistoricoUsuarioEspecializada>;

  @HasMany({ target: () => Quesito, foreignKey: 'usuario_id' })
  quesitos!: HasManyCollection<Quesito>;

  @HasMany({ target: () => Protocolizacao, foreignKey: 'usuario_id' })
  protocolizacaos!: HasManyCollection<Protocolizacao>;

  @HasMany({ target: () => Acordo, foreignKey: 'mediador_id' })
  acordos!: HasManyCollection<Acordo>;

  @HasMany({ target: () => SorteioCorreicao, foreignKey: 'usuario_id' })
  sorteioCorreicaos!: HasManyCollection<SorteioCorreicao>;

  @HasMany({ target: () => SorteioCorreicaoProcessoAdministrativo, foreignKey: 'avaliador_id' })
  sorteioCorreicaoProcessoAdministrativos!: HasManyCollection<SorteioCorreicaoProcessoAdministrativo>;

  @HasMany({ target: () => SorteioCorreicaoProcessoAdministrativoQuesito, foreignKey: 'usuario_id' })
  sorteioCorreicaoProcessoAdministrativoQuesitos!: HasManyCollection<SorteioCorreicaoProcessoAdministrativoQuesito>;

  @HasMany({ target: () => PastaCaixaEntrada, foreignKey: 'usuario_id' })
  pastaCaixaEntradas!: HasManyCollection<PastaCaixaEntrada>;

  @HasMany({ target: () => HistoricoPrazo, foreignKey: 'usuario_id' })
  historicoPrazos!: HasManyCollection<HistoricoPrazo>;

  @BelongsTo({ target: () => Especializada, foreignKey: 'especializada_id' })
  especializada!: BelongsToReference<Especializada>;

  @HasMany({ target: () => ProvidenciaJuridica, foreignKey: 'usuario_id' })
  providenciaJuridicas!: HasManyCollection<ProvidenciaJuridica>;

  @HasMany({ target: () => Audiencia, foreignKey: 'usuario_criador_id' })
  audiencias!: HasManyCollection<Audiencia>;

  @HasMany({ target: () => Comunicacao, foreignKey: 'responsavel_id' })
  comunicacaos!: HasManyCollection<Comunicacao>;

  @HasMany({ target: () => Modelo, foreignKey: 'usuario_id' })
  modelos!: HasManyCollection<Modelo>;

  @HasMany({ target: () => Entrega, foreignKey: 'usuario_id' })
  entregas!: HasManyCollection<Entrega>;

  @HasMany({ target: () => ComunicacaoEstado, foreignKey: 'usuario_id' })
  comunicacaoEstados!: HasManyCollection<ComunicacaoEstado>;

  @HasMany({ target: () => ValorAdicional, foreignKey: 'usuario_id' })
  valorAdicionals!: HasManyCollection<ValorAdicional>;

  @HasMany({ target: () => Solicitacao, foreignKey: 'solicitante_id' })
  solicitacaos!: HasManyCollection<Solicitacao>;

  @HasMany({ target: () => ManifestacaoEstado, foreignKey: 'usuario_id' })
  manifestacaoEstados!: HasManyCollection<ManifestacaoEstado>;

}
