// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { Perfil } from './Perfil';
import { Usuario } from './Usuario';

@Entity({ tableName: 'usuario_perfil' })
export class UsuarioPerfil {
  /**
   * identificador da relação entre usuário e perfil
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * chave estrangeira que aponta para o usuário
   * @remarks References dbo.usuario.id (on delete CASCADE, on update CASCADE)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'usuario', column: 'id', onDelete: 'CASCADE', onUpdate: 'CASCADE' }))
  usuario_id!: number;

  /**
   * chave estrangeira que aponta para o perfil
   * @remarks References dbo.perfil.id (on delete CASCADE, on update CASCADE)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'perfil', column: 'id', onDelete: 'CASCADE', onUpdate: 'CASCADE' }))
  perfil_id!: number;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario!: BelongsToReference<Usuario>;

  @BelongsTo({ target: () => Perfil, foreignKey: 'perfil_id' })
  perfil!: BelongsToReference<Perfil>;

}
