// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, BelongsToReference, ManyToManyCollection } from 'metal-orm';
import { Acervo } from './Acervo.js';
import { AcervoDestinatarioPa } from './AcervoDestinatarioPa.js';
import { AcessoRestritoFuncionalidade } from './AcessoRestritoFuncionalidade.js';
import { AcessoRestritoFuncionalidadeUsuario } from './AcessoRestritoFuncionalidadeUsuario.js';
import { Acordo } from './Acordo.js';
import { AfastamentoPessoa } from './AfastamentoPessoa.js';
import { AfastamentoPessoaUsuario } from './AfastamentoPessoaUsuario.js';
import { Audiencia } from './Audiencia.js';
import { Carga } from './Carga.js';
import { Comunicacao } from './Comunicacao.js';
import { ComunicacaoEstado } from './ComunicacaoEstado.js';
import { Correicao } from './Correicao.js';
import { Despacho } from './Despacho.js';
import { DocumentoAcordoContencioso } from './DocumentoAcordoContencioso.js';
import { DocumentoAnexoRascunho } from './DocumentoAnexoRascunho.js';
import { DocumentoProcessoAdministrativo } from './DocumentoProcessoAdministrativo.js';
import { DocumentoProcessoAdministrativoAcordo } from './DocumentoProcessoAdministrativoAcordo.js';
import { DocumentoRascunho } from './DocumentoRascunho.js';
import { DocumentoRascunhoEstado } from './DocumentoRascunhoEstado.js';
import { Entrega } from './Entrega.js';
import { Equipe } from './Equipe.js';
import { EquipeUsuario } from './EquipeUsuario.js';
import { Especializada } from './Especializada.js';
import { EspecializadaAssistente } from './EspecializadaAssistente.js';
import { EspecializadaDistribuidor } from './EspecializadaDistribuidor.js';
import { EspecializadaUsuarioNotificacao } from './EspecializadaUsuarioNotificacao.js';
import { EstadoProcessoAdministrativo } from './EstadoProcessoAdministrativo.js';
import { EstadoSolicitacao } from './EstadoSolicitacao.js';
import { HistoricoDistribuicaoAcervo } from './HistoricoDistribuicaoAcervo.js';
import { HistoricoDistribuicaoEspecializada } from './HistoricoDistribuicaoEspecializada.js';
import { HistoricoPrazo } from './HistoricoPrazo.js';
import { HistoricoUsuarioEspecializada } from './HistoricoUsuarioEspecializada.js';
import { ManifestacaoEstado } from './ManifestacaoEstado.js';
import { MarcadorDocumentoProcessoJudicial } from './MarcadorDocumentoProcessoJudicial.js';
import { Modelo } from './Modelo.js';
import { ModeloFormulario } from './ModeloFormulario.js';
import { ModeloFormularioProcessoAdministrativo } from './ModeloFormularioProcessoAdministrativo.js';
import { ModeloFormularioProcessoAdministrativoEstadoModeloFormulario } from './ModeloFormularioProcessoAdministrativoEstadoModeloFormulario.js';
import { PastaCaixaEntrada } from './PastaCaixaEntrada.js';
import { Perfil } from './Perfil.js';
import { PreferenciaUsuario } from './PreferenciaUsuario.js';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';
import { Protocolizacao } from './Protocolizacao.js';
import { ProvidenciaJuridica } from './ProvidenciaJuridica.js';
import { Quesito } from './Quesito.js';
import { RegistroTramitacao } from './RegistroTramitacao.js';
import { RetornoProgramado } from './RetornoProgramado.js';
import { Solicitacao } from './Solicitacao.js';
import { SorteioCorreicao } from './SorteioCorreicao.js';
import { SorteioCorreicaoProcessoAdministrativo } from './SorteioCorreicaoProcessoAdministrativo.js';
import { SorteioCorreicaoProcessoAdministrativoQuesito } from './SorteioCorreicaoProcessoAdministrativoQuesito.js';
import { UsuarioPerfil } from './UsuarioPerfil.js';
import { UsuarioPermitidoAcessarProcessoAdministrativoSigiloso } from './UsuarioPermitidoAcessarProcessoAdministrativoSigiloso.js';
import { ValorAdicional } from './ValorAdicional.js';

@Entity({ tableName: 'usuario' })
export class Usuario {
  /**
   * identificador do usuário
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * chave esrangeira que aponta para a especializada do usuário, pode não ter especializada pois o usuário acabou de ser criado no sistema
   * @remarks References dbo.especializada.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'especializada', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  especializada_id?: number;

  /**
   * nome completo do usuário
   */
  @Column(col.notNull(col.varchar(127)))
  nome!: string;

  /**
   * nome de login do usuário
   */
  @Column(col.unique(col.notNull(col.varchar(200))))
  login!: string;

  /**
   * cargo do usuário
   */
  @Column(col.notNull(col.varchar(127)))
  cargo!: string;

  /**
   * flag que mostra se o usuário é ativo ou não
   */
  @Column(col.notNull(col.boolean()))
  estado_inatividade!: boolean;

  /**
   * vînculo do usuário
   */
  @Column(col.varchar(63))
  vinculo?: string;

  /**
   * flag que mostra se cargo pode ser exibido
   */
  @Column(col.boolean())
  exibe_cargo?: boolean;

  /**
   * flag que mostra se vínculo pode ser exibido
   */
  @Column(col.boolean())
  exibe_vinculo?: boolean;

  /**
   * flag que mostra se matrícula pode ser exibida
   */
  @Column(col.boolean())
  exibe_matricula?: boolean;

  /**
   * flag que mostra se função pode ser exibida
   */
  @Column(col.boolean())
  exibe_funcao?: boolean;

  /**
   * função exercida pelo usuário
   */
  @Column(col.varchar(200))
  funcao?: string;

  /**
   * matrícula administrativa do usuário
   */
  @Column(col.varchar(200))
  matricula?: string;

  /**
   * abreviatura do nome do usuário
   */
  @Column(col.varchar(5))
  abreviatura?: string;

  /**
   * flag que indica que usuário é o ponto focal da especializada
   */
  @Column(col.boolean())
  ponto_focal?: boolean;

  @BelongsToMany({ target: () => Especializada, pivotTable: () => EspecializadaDistribuidor, pivotForeignKeyToRoot: 'distribuidor_id', pivotForeignKeyToTarget: 'especializada_id' })
  especializadas!: ManyToManyCollection<Especializada>;

  @BelongsToMany({ target: () => Perfil, pivotTable: () => UsuarioPerfil, pivotForeignKeyToRoot: 'usuario_id', pivotForeignKeyToTarget: 'perfil_id' })
  perfis!: ManyToManyCollection<Perfil>;

  @BelongsToMany({ target: () => RegistroTramitacao, pivotTable: () => Despacho, pivotForeignKeyToRoot: 'usuario_id', pivotForeignKeyToTarget: 'registro_tramitacao_id' })
  registrosTramitacoes!: ManyToManyCollection<RegistroTramitacao>;

  @BelongsToMany({ target: () => Acervo, pivotTable: () => AcervoDestinatarioPa, pivotForeignKeyToRoot: 'destinatario_pa_id', pivotForeignKeyToTarget: 'acervo_id' })
  acervos!: ManyToManyCollection<Acervo>;

  @BelongsToMany({ target: () => Equipe, pivotTable: () => EquipeUsuario, pivotForeignKeyToRoot: 'usuario_id', pivotForeignKeyToTarget: 'equipe_id' })
  equipes!: ManyToManyCollection<Equipe>;

  @BelongsToMany({ target: () => AcessoRestritoFuncionalidade, pivotTable: () => AcessoRestritoFuncionalidadeUsuario, pivotForeignKeyToRoot: 'usuario_id', pivotForeignKeyToTarget: 'acesso_restrito_funcionalidade_id' })
  acessosRestritosFuncionalidades!: ManyToManyCollection<AcessoRestritoFuncionalidade>;

  @BelongsToMany({ target: () => AfastamentoPessoa, pivotTable: () => AfastamentoPessoaUsuario, pivotForeignKeyToRoot: 'usuario_id', pivotForeignKeyToTarget: 'afastamento_pessoa_id' })
  afastamentosPessoas!: ManyToManyCollection<AfastamentoPessoa>;

  @BelongsToMany({ target: () => ProcessoAdministrativo, pivotTable: () => UsuarioPermitidoAcessarProcessoAdministrativoSigiloso, pivotForeignKeyToRoot: 'usuario_id', pivotForeignKeyToTarget: 'processo_administrativo_id' })
  processosAdministrativos!: ManyToManyCollection<ProcessoAdministrativo>;

  @HasMany({ target: () => DocumentoProcessoAdministrativoAcordo, foreignKey: 'usuario_id' })
  documentosProcessosAdministrativosAcordos!: HasManyCollection<DocumentoProcessoAdministrativoAcordo>;

  @HasMany({ target: () => PreferenciaUsuario, foreignKey: 'usuario_id' })
  preferenciasUsuarios!: HasManyCollection<PreferenciaUsuario>;

  @HasMany({ target: () => EstadoSolicitacao, foreignKey: 'usuario_id' })
  estadosSolicitacao!: HasManyCollection<EstadoSolicitacao>;

  @HasMany({ target: () => Correicao, foreignKey: 'usuario_id' })
  correicoes!: HasManyCollection<Correicao>;

  @HasMany({ target: () => MarcadorDocumentoProcessoJudicial, foreignKey: 'usuario_id' })
  marcadoresDocumentosProcessosJudiciais!: HasManyCollection<MarcadorDocumentoProcessoJudicial>;

  @HasMany({ target: () => ModeloFormularioProcessoAdministrativo, foreignKey: 'usuario_id' })
  modelosFormulariosProcessosAdministrativos!: HasManyCollection<ModeloFormularioProcessoAdministrativo>;

  @HasMany({ target: () => RetornoProgramado, foreignKey: 'destinatario_id' })
  retornosProgramados!: HasManyCollection<RetornoProgramado>;

  @HasMany({ target: () => EspecializadaDistribuidor, foreignKey: 'distribuidor_id' })
  especializadasDistribuidores!: HasManyCollection<EspecializadaDistribuidor>;

  @HasMany({ target: () => ModeloFormularioProcessoAdministrativoEstadoModeloFormulario, foreignKey: 'usuario_id' })
  modelosFormulariosProcessosAdministrativosEstadosModelosFormularios!: HasManyCollection<ModeloFormularioProcessoAdministrativoEstadoModeloFormulario>;

  @HasMany({ target: () => DocumentoRascunho, foreignKey: 'usuario_id' })
  documentosRascunhos!: HasManyCollection<DocumentoRascunho>;

  @HasMany({ target: () => Carga, foreignKey: 'usuario_id' })
  cargas!: HasManyCollection<Carga>;

  @HasMany({ target: () => DocumentoRascunhoEstado, foreignKey: 'usuario_id' })
  documentosRascunhosEstados!: HasManyCollection<DocumentoRascunhoEstado>;

  @HasMany({ target: () => ModeloFormulario, foreignKey: 'criador_id' })
  modelosFormularios!: HasManyCollection<ModeloFormulario>;

  @HasMany({ target: () => DocumentoAcordoContencioso, foreignKey: 'usuario_id' })
  documentosAcordosContenciosos!: HasManyCollection<DocumentoAcordoContencioso>;

  @HasMany({ target: () => UsuarioPerfil, foreignKey: 'usuario_id' })
  usuariosPerfis!: HasManyCollection<UsuarioPerfil>;

  @HasMany({ target: () => EstadoProcessoAdministrativo, foreignKey: 'usuario_id' })
  estadosProcessosAdministrativos!: HasManyCollection<EstadoProcessoAdministrativo>;

  @HasMany({ target: () => EspecializadaAssistente, foreignKey: 'assistente_id' })
  especializadasAssistentes!: HasManyCollection<EspecializadaAssistente>;

  @HasMany({ target: () => Despacho, foreignKey: 'usuario_id' })
  despachos!: HasManyCollection<Despacho>;

  @HasMany({ target: () => DocumentoAnexoRascunho, foreignKey: 'usuario_id' })
  documentosAnexosRascunhos!: HasManyCollection<DocumentoAnexoRascunho>;

  @HasMany({ target: () => AcervoDestinatarioPa, foreignKey: 'destinatario_pa_id' })
  acervosDestinatariosPas!: HasManyCollection<AcervoDestinatarioPa>;

  @HasMany({ target: () => EquipeUsuario, foreignKey: 'usuario_id' })
  equipesUsuarios!: HasManyCollection<EquipeUsuario>;

  @HasMany({ target: () => DocumentoProcessoAdministrativo, foreignKey: 'usuario_id' })
  documentosProcessosAdministrativos!: HasManyCollection<DocumentoProcessoAdministrativo>;

  @HasMany({ target: () => HistoricoDistribuicaoAcervo, foreignKey: 'usuario_acao_id' })
  historicosDistribuicoesAcervos!: HasManyCollection<HistoricoDistribuicaoAcervo>;

  @HasMany({ target: () => HistoricoDistribuicaoEspecializada, foreignKey: 'usuario_acao_id' })
  historicosDistribuicoesEspecializadas!: HasManyCollection<HistoricoDistribuicaoEspecializada>;

  @HasMany({ target: () => HistoricoUsuarioEspecializada, foreignKey: 'usuario_acao_id' })
  historicosUsuariosEspecializadas!: HasManyCollection<HistoricoUsuarioEspecializada>;

  @HasMany({ target: () => Quesito, foreignKey: 'usuario_id' })
  quesitos!: HasManyCollection<Quesito>;

  @HasMany({ target: () => Protocolizacao, foreignKey: 'usuario_id' })
  protocolizacoes!: HasManyCollection<Protocolizacao>;

  @HasMany({ target: () => Acordo, foreignKey: 'mediador_id' })
  acordos!: HasManyCollection<Acordo>;

  @HasMany({ target: () => SorteioCorreicao, foreignKey: 'usuario_id' })
  sorteiosCorreicoes!: HasManyCollection<SorteioCorreicao>;

  @HasMany({ target: () => EspecializadaUsuarioNotificacao, foreignKey: 'usuario_id' })
  especializadasUsuariosNotificacoes!: HasManyCollection<EspecializadaUsuarioNotificacao>;

  @HasMany({ target: () => SorteioCorreicaoProcessoAdministrativo, foreignKey: 'avaliador_id' })
  sorteiosCorreicoesProcessosAdministrativos!: HasManyCollection<SorteioCorreicaoProcessoAdministrativo>;

  @HasMany({ target: () => SorteioCorreicaoProcessoAdministrativoQuesito, foreignKey: 'usuario_id' })
  sorteiosCorreicoesProcessosAdministrativosQuesitos!: HasManyCollection<SorteioCorreicaoProcessoAdministrativoQuesito>;

  @HasMany({ target: () => AcessoRestritoFuncionalidadeUsuario, foreignKey: 'usuario_id' })
  acessosRestritosFuncionalidadesUsuarios!: HasManyCollection<AcessoRestritoFuncionalidadeUsuario>;

  @HasMany({ target: () => PastaCaixaEntrada, foreignKey: 'usuario_id' })
  pastasCaixasEntradas!: HasManyCollection<PastaCaixaEntrada>;

  @HasMany({ target: () => AfastamentoPessoaUsuario, foreignKey: 'usuario_id' })
  afastamentosPessoasUsuarios!: HasManyCollection<AfastamentoPessoaUsuario>;

  @HasMany({ target: () => HistoricoPrazo, foreignKey: 'usuario_id' })
  historicosPrazos!: HasManyCollection<HistoricoPrazo>;

  @BelongsTo({ target: () => Especializada, foreignKey: 'especializada_id' })
  especializada!: BelongsToReference<Especializada>;

  @HasMany({ target: () => ProvidenciaJuridica, foreignKey: 'usuario_id' })
  providenciasJuridicas!: HasManyCollection<ProvidenciaJuridica>;

  @HasMany({ target: () => Audiencia, foreignKey: 'usuario_criador_id' })
  audiencias!: HasManyCollection<Audiencia>;

  @HasMany({ target: () => Comunicacao, foreignKey: 'responsavel_id' })
  comunicacoes!: HasManyCollection<Comunicacao>;

  @HasMany({ target: () => Modelo, foreignKey: 'usuario_id' })
  modelos!: HasManyCollection<Modelo>;

  @HasMany({ target: () => Entrega, foreignKey: 'usuario_id' })
  entregas!: HasManyCollection<Entrega>;

  @HasMany({ target: () => ComunicacaoEstado, foreignKey: 'usuario_id' })
  comunicacoesEstados!: HasManyCollection<ComunicacaoEstado>;

  @HasMany({ target: () => UsuarioPermitidoAcessarProcessoAdministrativoSigiloso, foreignKey: 'usuario_id' })
  usuariosPermitidosAcessaresProcessosAdministrativosSigilosos!: HasManyCollection<UsuarioPermitidoAcessarProcessoAdministrativoSigiloso>;

  @HasMany({ target: () => ValorAdicional, foreignKey: 'usuario_id' })
  valoresAdicionais!: HasManyCollection<ValorAdicional>;

  @HasMany({ target: () => Solicitacao, foreignKey: 'solicitante_id' })
  solicitacoes!: HasManyCollection<Solicitacao>;

  @HasMany({ target: () => ManifestacaoEstado, foreignKey: 'usuario_id' })
  manifestacoesEstados!: HasManyCollection<ManifestacaoEstado>;

}
