// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { Usuario } from './Usuario';

@Entity({ tableName: 'usuario_thumbnail' })
export class UsuarioThumbnail {
  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.unique(col.notNull(col.int())), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id!: number;

  @Column(col.blob())
  thumbnail?: Buffer;

  /**
   * @defaultValue (getdate())
   */
  @Column(col.defaultRaw(col.datetime<Date>(), '(getdate())'))
  data_atualizacao?: Date;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario!: BelongsToReference<Usuario>;

}
