// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsToMany, ManyToManyCollection } from 'metal-orm';
import { UnidadeSei } from './UnidadeSei';
import { UnidadeSeiUsuarioSei } from './UnidadeSeiUsuarioSei';

@Entity({ tableName: 'usuario_sei' })
export class UsuarioSei {
  /**
   * identificador do usuário SEI
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * identificador de usuário na API SEI
   */
  @Column(col.int())
  id_usuario?: number;

  /**
   * sigla do usuário SEI
   */
  @Column(col.varchar(30))
  sigla?: string;

  /**
   * nome do usuário SEI
   */
  @Column(col.varchar(100))
  nome?: string;

  @BelongsToMany({ target: () => UnidadeSei, pivotTable: () => UnidadeSeiUsuarioSei, pivotForeignKeyToRoot: 'usuario_sei_id', pivotForeignKeyToTarget: 'unidade_sei_id' })
  unidadesSeis!: ManyToManyCollection<UnidadeSei>;

}
