// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column } from 'metal-orm';

@Entity({ tableName: 'vw_afastamento_pessoa', type: 'view' })
export class VwAfastamentoPessoa {
  @Column(col.notNull(col.int()))
  readonly id!: number;

  @Column(col.notNull(col.date<Date>()))
  readonly data_inicio!: Date;

  @Column(col.date<Date>())
  readonly data_inicio_comunicacao?: Date;

  @Column(col.notNull(col.date<Date>()))
  readonly data_fim!: Date;

  @Column(col.date<Date>())
  readonly data_fim_comunicacao?: Date;

  @Column(col.notNull(col.date<Date>()))
  readonly menor_data_inicio!: Date;

  @Column(col.notNull(col.date<Date>()))
  readonly maior_data_fim!: Date;

  @Column(col.notNull(col.int()))
  readonly usuario_id!: number;

}
