// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column } from 'metal-orm';

@Entity({ tableName: 'vw_ultimo_estado_comunicacao', type: 'view' })
export class VwUltimoEstadoComunicacao {
  @Column(col.notNull(col.int()))
  readonly id!: number;

  @Column(col.notNull(col.int()))
  readonly estado_id!: number;

  @Column(col.notNull(col.int()))
  readonly comunicacao_id!: number;

  @Column(col.notNull(col.datetime<Date>()))
  readonly data_alteracao!: Date;

  @Column(col.varchar(255))
  readonly descricao_estado?: string;

  @Column(col.int())
  readonly usuario_id?: number;

}
