// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column } from 'metal-orm';

@Entity({ tableName: 'vw_ultima_tramitacao', type: 'view' })
export class VwUltimaTramitacao {
  @Column(col.notNull(col.int()))
  readonly id!: number;

  @Column(col.datetime<Date>())
  readonly data_hora_ultima_tramitacao?: Date;

}
