// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { Acervo } from './Acervo.js';
import { Classificacao } from './Classificacao.js';

@Entity({ tableName: 'acervo_classificacao' })
export class AcervoClassificacao {
  /**
   * Armazena um identificador único para cada registro na tabela.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Informa a classificação relacionada ao acervo em questão.
   * @remarks References dbo.classificacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'classificacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  classificacao_id!: number;

  /**
   * Informa se o mesmo está em distribuição automática.
   */
  @Column(col.boolean())
  distribuicao_automatica?: boolean;

  /**
   * Armazena um identificador ou código que está relacionado a um item específico no acervo, permitindo a vinculação desse item a uma determinada classificação ou categoria na tabela.
   * @remarks References dbo.acervo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'acervo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  acervo_id!: number;

  @BelongsTo({ target: () => Classificacao, foreignKey: 'classificacao_id' })
  classificacao?: Classificacao;

  @BelongsTo({ target: () => Acervo, foreignKey: 'acervo_id' })
  acervo?: Acervo;

}
