// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { ProcessoJudicial } from './ProcessoJudicial.js';
import { TipoAtividade } from './TipoAtividade.js';

@Entity({ tableName: 'atividade' })
export class Atividade {
  /**
   * Identificador da atividade
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador do processo judicial
   * @remarks References dbo.processo_judicial.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'processo_judicial', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_judicial_id?: number;

  /**
   * O processo administrativo consiste na sequência de atividades realizadas pela Administração Pública com o objetivo final de dar efeito a algo previsto em lei
   */
  @Column(col.varchar(20))
  processo_adminstrativo?: string;

  /**
   * O termo "prazo interno" refere-se ao período de tempo estabelecido dentro de uma organização, empresa ou equipe para a conclusão de uma determinada atividade
   */
  @Column(col.datetime<Date>())
  prazo_interno?: Date;

  /**
   * "Prazo judicial" refere-se ao prazo estabelecido pela lei para a prática de atos processuais no âmbito judicial.
   */
  @Column(col.datetime<Date>())
  prazo_judicial?: Date;

  /**
   * É o responsável pela pela LDAP
   */
  @Column(col.varchar(50))
  responsavel_ldap?: string;

  /**
   * Usuário de autentificação  deLDAP
   */
  @Column(col.varchar(50))
  user_ldap?: string;

  /**
   * Refere-se ao id do tipo de atividade
   * @remarks References dbo.tipo_atividade.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'tipo_atividade', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_atividade_id!: number;

  /**
   * Refere-se ao período no qual se tem a conclusão da atividade
   */
  @Column(col.datetime<Date>())
  data_conclusao?: Date;

  /**
   * Refere-se observação da atividade
   */
  @Column(col.text())
  observacao?: string;

  @BelongsTo({ target: () => ProcessoJudicial, foreignKey: 'processo_judicial_id' })
  processoJudicial?: ProcessoJudicial;

  @BelongsTo({ target: () => TipoAtividade, foreignKey: 'tipo_atividade_id' })
  tipoAtividade?: TipoAtividade;

}
