// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsToMany, HasManyCollection, ManyToManyCollection } from 'metal-orm';
import { Classificacao } from './Classificacao.js';
import { ClassificacaoRelevancia } from './ClassificacaoRelevancia.js';

@Entity({ tableName: 'classificacao_recorrencia' })
export class ClassificacaoRecorrencia {
  /**
   * Identificador único.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Nome dado à classificação de recorrência: Padrão ou Singular.
   */
  @Column(col.notNull(col.varchar(63)))
  nome!: string;

  @BelongsToMany({ target: () => ClassificacaoRelevancia, pivotTable: () => Classificacao, pivotForeignKeyToRoot: 'classificacao_recorrencia_id', pivotForeignKeyToTarget: 'classificacao_relevancia_id' })
  classificacaoRelevancias!: ManyToManyCollection<ClassificacaoRelevancia>;

  @HasMany({ target: () => Classificacao, foreignKey: 'classificacao_recorrencia_id' })
  classificacaos!: HasManyCollection<Classificacao>;

}
