// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, BelongsToReference, ManyToManyCollection } from 'metal-orm';
import { Acervo } from './Acervo.js';
import { AcervoClassificacao } from './AcervoClassificacao.js';
import { ClassificacaoEspecializadaTema } from './ClassificacaoEspecializadaTema.js';
import { ClassificacaoRecorrencia } from './ClassificacaoRecorrencia.js';
import { ClassificacaoRelevancia } from './ClassificacaoRelevancia.js';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';

@Entity({ tableName: 'classificacao' })
export class Classificacao {
  /**
   * Id da classificação
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Nome da classificação
   */
  @Column(col.notNull(col.varchar(63)))
  nome!: string;

  /**
   * Refere-se ao peso da classificação
   * @defaultValue ((1))
   */
  @Column(col.defaultRaw(col.int(), '((1))'))
  peso?: number;

  /**
   * Identificador da relevância da classificação
   * @remarks References dbo.classificacao_relevancia.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'classificacao_relevancia', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  classificacao_relevancia_id?: number;

  /**
   * Identificador da classificação recorrencia
   * @remarks References dbo.classificacao_recorrencia.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'classificacao_recorrencia', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  classificacao_recorrencia_id?: number;

  @BelongsToMany({ target: () => Acervo, pivotTable: () => AcervoClassificacao, pivotForeignKeyToRoot: 'classificacao_id', pivotForeignKeyToTarget: 'acervo_id' })
  acervos!: ManyToManyCollection<Acervo>;

  @HasMany({ target: () => ClassificacaoEspecializadaTema, foreignKey: 'classificacao_id' })
  classificacaoEspecializadaTemas!: HasManyCollection<ClassificacaoEspecializadaTema>;

  @BelongsTo({ target: () => ClassificacaoRelevancia, foreignKey: 'classificacao_relevancia_id' })
  classificacaoRelevancia!: BelongsToReference<ClassificacaoRelevancia>;

  @BelongsTo({ target: () => ClassificacaoRecorrencia, foreignKey: 'classificacao_recorrencia_id' })
  classificacaoRecorrencia!: BelongsToReference<ClassificacaoRecorrencia>;

  @HasMany({ target: () => ProcessoAdministrativo, foreignKey: 'classificacao_id' })
  processoAdministrativos!: HasManyCollection<ProcessoAdministrativo>;

  @HasMany({ target: () => AcervoClassificacao, foreignKey: 'classificacao_id' })
  acervoClassificacaos!: HasManyCollection<AcervoClassificacao>;

}
