// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { CodigoExterno } from './CodigoExterno.js';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';

@Entity({ tableName: 'codigo_externo_processo_administrativo' })
export class CodigoExternoProcessoAdministrativo {
  /**
   * Identificador único da relação de processo administrativo com código externo.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador que informa o processo administrativo.
   * @remarks References dbo.processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_administrativo_id!: number;

  /**
   * Identificador que informa o código externo relacionado ao pa.
   * @remarks References dbo.codigo_externo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'codigo_externo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  codigo_externo_id!: number;

  @BelongsTo({ target: () => ProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  processoAdministrativo?: ProcessoAdministrativo;

  @BelongsTo({ target: () => CodigoExterno, foreignKey: 'codigo_externo_id' })
  codigoExterno?: CodigoExterno;

}
