// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, BelongsToReference, ManyToManyCollection } from 'metal-orm';
import { CodigoExternoProcessoAdministrativo } from './CodigoExternoProcessoAdministrativo.js';
import { ProcedimentoSei } from './ProcedimentoSei.js';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';
import { SistemaOrigem } from './SistemaOrigem.js';

@Entity({ tableName: 'codigo_externo' })
export class CodigoExterno {
  /**
   * Identificador único.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Número do código.
   */
  @Column(col.notNull(col.text()))
  numero!: string;

  /**
   * Informa a data de geração.
   */
  @Column(col.date<Date>())
  data_geracao?: Date;

  /**
   * Identificador que informa o sistema de origem.
   * @remarks References dbo.sistema_origem.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'sistema_origem', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  sistema_origem_id?: number;

  /**
   * Identificador que informa o procedimento SEI.
   * @remarks References dbo.procedimento_sei.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'procedimento_sei', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  procedimento_sei_id?: number;

  @BelongsToMany({ target: () => ProcessoAdministrativo, pivotTable: () => CodigoExternoProcessoAdministrativo, pivotForeignKeyToRoot: 'codigo_externo_id', pivotForeignKeyToTarget: 'processo_administrativo_id' })
  processosAdministrativos!: ManyToManyCollection<ProcessoAdministrativo>;

  @BelongsTo({ target: () => SistemaOrigem, foreignKey: 'sistema_origem_id' })
  sistemaOrigem!: BelongsToReference<SistemaOrigem>;

  @BelongsTo({ target: () => ProcedimentoSei, foreignKey: 'procedimento_sei_id' })
  procedimentoSei!: BelongsToReference<ProcedimentoSei>;

  @HasMany({ target: () => CodigoExternoProcessoAdministrativo, foreignKey: 'codigo_externo_id' })
  codigosExternosProcessosAdministrativos!: HasManyCollection<CodigoExternoProcessoAdministrativo>;

}
