// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, BelongsToReference, ManyToManyCollection } from 'metal-orm';
import { ConfidencialidadeEspecializada } from './ConfidencialidadeEspecializada.js';
import { Especializada } from './Especializada.js';

@Entity({ tableName: 'confidencialidade' })
export class Confidencialidade {
  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * @remarks References dbo.especializada.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'especializada', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  especializada_id!: number;

  /**
   * @defaultValue ((0))
   */
  @Column(col.defaultRaw(col.notNull(col.boolean()), '((0))'))
  padrao_sigilo_interno!: boolean;

  /**
   * @defaultValue ((0))
   */
  @Column(col.defaultRaw(col.notNull(col.boolean()), '((0))'))
  permitir_sigilo_interno_procurador!: boolean;

  /**
   * @defaultValue ((0))
   */
  @Column(col.defaultRaw(col.notNull(col.boolean()), '((0))'))
  permitir_sigilo_interno_servidor!: boolean;

  /**
   * @defaultValue ((0))
   */
  @Column(col.defaultRaw(col.notNull(col.boolean()), '((0))'))
  permitir_acesso_individual_procurador!: boolean;

  /**
   * @defaultValue ((0))
   */
  @Column(col.defaultRaw(col.notNull(col.boolean()), '((0))'))
  permitir_acesso_individual_servidor!: boolean;

  /**
   * @defaultValue (getdate())
   */
  @Column(col.defaultRaw(col.notNull(col.datetime<Date>()), '(getdate())'))
  created!: Date;

  /**
   * @defaultValue (getdate())
   */
  @Column(col.defaultRaw(col.notNull(col.datetime<Date>()), '(getdate())'))
  modified!: Date;

  /**
   * @defaultValue ((0))
   */
  @Column(col.defaultRaw(col.notNull(col.boolean()), '((0))'))
  permitir_acesso_dados_procurador!: boolean;

  /**
   * @defaultValue ((0))
   */
  @Column(col.defaultRaw(col.notNull(col.boolean()), '((0))'))
  permitir_acesso_dados_servidor!: boolean;

  /**
   * @defaultValue ((0))
   */
  @Column(col.defaultRaw(col.notNull(col.boolean()), '((0))'))
  permitir_acesso_dados_residente!: boolean;

  /**
   * @defaultValue ((0))
   */
  @Column(col.defaultRaw(col.notNull(col.boolean()), '((0))'))
  permitir_acesso_dados_estagiario!: boolean;

  @BelongsToMany({ target: () => Especializada, pivotTable: () => ConfidencialidadeEspecializada, pivotForeignKeyToRoot: 'confidencialidade_id', pivotForeignKeyToTarget: 'especializada_id' })
  especializadas!: ManyToManyCollection<Especializada>;

  @BelongsTo({ target: () => Especializada, foreignKey: 'especializada_id' })
  especializada!: BelongsToReference<Especializada>;

  @HasMany({ target: () => ConfidencialidadeEspecializada, foreignKey: 'confidencialidade_id' })
  confidencialidadeEspecializadas!: HasManyCollection<ConfidencialidadeEspecializada>;

}
