// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsToMany, HasManyCollection, ManyToManyCollection } from 'metal-orm';
import { Incidente } from './Incidente.js';
import { TipoIncidente } from './TipoIncidente.js';

@Entity({ tableName: 'desabilita_tipo_integracao' })
export class DesabilitaTipoIntegracao {
  /**
   * Identificador único.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Informa o tipo da integração.
   */
  @Column(col.notNull(col.text()))
  tipo!: string;

  @BelongsToMany({ target: () => TipoIncidente, pivotTable: () => Incidente, pivotForeignKeyToRoot: 'desabilita_tipo_integracao_id', pivotForeignKeyToTarget: 'tipo_incidente_id' })
  tipoIncidentes!: ManyToManyCollection<TipoIncidente>;

  @HasMany({ target: () => Incidente, foreignKey: 'desabilita_tipo_integracao_id' })
  incidentes!: HasManyCollection<Incidente>;

}
