// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { Comunicacao } from './Comunicacao.js';
import { TipoDispensa } from './TipoDispensa.js';

@Entity({ tableName: 'dispensa_generica' })
export class DispensaGenerica {
  /**
   * Identificador único.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador que informa a comunicação vinculada.
   * @remarks References dbo.comunicacao.id (on delete CASCADE, on update CASCADE)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'comunicacao', column: 'id', onDelete: 'CASCADE', onUpdate: 'CASCADE' }))
  comunicacao_id!: number;

  /**
   * Breve descrição da dispensa genérica.
   */
  @Column(col.notNull(col.text()))
  descricao_dispensa!: string;

  /**
   * Identificador que informa o tipo da dispensa genérica.
   * @remarks References dbo.tipo_dispensa.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'tipo_dispensa', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_dispensa_id!: number;

  @BelongsTo({ target: () => Comunicacao, foreignKey: 'comunicacao_id' })
  comunicacao!: BelongsToReference<Comunicacao>;

  @BelongsTo({ target: () => TipoDispensa, foreignKey: 'tipo_dispensa_id' })
  tipoDispensa!: BelongsToReference<TipoDispensa>;

}
