// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { DocumentoRascunho } from './DocumentoRascunho.js';
import { ProvidenciaJuridica } from './ProvidenciaJuridica.js';

@Entity({ tableName: 'documento_rascunho_providencia_juridica' })
export class DocumentoRascunhoProvidenciaJuridica {
  /**
   * Identificador único.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Providência jurídica.
   * @remarks References dbo.providencia_juridica.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'providencia_juridica', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  providencia_juridica_id!: number;

  /**
   * Identificador do documento rascunho vinculado.
   * @remarks References dbo.documento_rascunho.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'documento_rascunho', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  documento_rascunho_id!: number;

  @BelongsTo({ target: () => ProvidenciaJuridica, foreignKey: 'providencia_juridica_id' })
  providenciaJuridica?: ProvidenciaJuridica;

  @BelongsTo({ target: () => DocumentoRascunho, foreignKey: 'documento_rascunho_id' })
  documentoRascunho?: DocumentoRascunho;

}
