// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { DocumentoRascunho } from './DocumentoRascunho.js';
import { Estado } from './Estado.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'documento_rascunho_estado' })
export class DocumentoRascunhoEstado {
  /**
   * Identificador único.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador do documento rascunho relacionado.
   * @remarks References dbo.documento_rascunho.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'documento_rascunho', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  documento_rascunho_id?: number;

  /**
   * Estado relacionado.
   * @remarks References dbo.estado.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'estado', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  estado_id?: number;

  /**
   * Data de troca.
   */
  @Column(col.datetime<Date>())
  data_troca?: Date;

  /**
   * Usuario vinculado ao documento rascunho.
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id!: number;

  /**
   * Descrição do rascunho.
   */
  @Column(col.text())
  descricao?: string;

  @BelongsTo({ target: () => DocumentoRascunho, foreignKey: 'documento_rascunho_id' })
  documentoRascunho!: BelongsToReference<DocumentoRascunho>;

  @BelongsTo({ target: () => Estado, foreignKey: 'estado_id' })
  estado!: BelongsToReference<Estado>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario!: BelongsToReference<Usuario>;

}
