// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, ManyToManyCollection } from 'metal-orm';
import { Comunicacao } from './Comunicacao.js';
import { DocumentoComunicacaoOutroParametro } from './DocumentoComunicacaoOutroParametro.js';
import { DocumentoProcessoAdministrativo } from './DocumentoProcessoAdministrativo.js';
import { OutroParametroDocumentoComunicacao } from './OutroParametroDocumentoComunicacao.js';

@Entity({ tableName: 'documento_comunicacao' })
export class DocumentoComunicacao {
  /**
   * Identificador único.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador que informa o documento vinculado.
   */
  @Column(col.text())
  id_documento?: string;

  /**
   * Armazena o nome específico do documento.
   */
  @Column(col.text())
  nome?: string;

  /**
   * Armazena o binário do arquivo.
   */
  @Column(col.blob())
  binario?: Buffer;

  /**
   * descrição do tipo de conteúdo do arquivo, geralmente indicado por uma combinação de letras e números.
   */
  @Column(col.varchar(50))
  mimetype?: string;

  /**
   * Armazena uma breve descrição do documento.
   */
  @Column(col.text())
  descricao?: string;

  /**
   * Informa a comunicação vinculada ao documento.
   * @remarks References dbo.comunicacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'comunicacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  comunicacao_id?: number;

  /**
   * Informa o documento pai na árvore de documentos.
   * @remarks References dbo.documento_comunicacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'documento_comunicacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  parent_id?: number;

  /**
   * Identificador que informa o tipo do documento.
   */
  @Column(col.int())
  tipo_documento_id?: number;

  /**
   * Identificador que armazena a comunicação física vinculada.
   */
  @Column(col.int())
  comunicacao_fisica_id?: number;

  /**
   * Informa se documento é original.
   */
  @Column(col.boolean())
  confere_original?: boolean;

  /**
   * Armazena a data de registro do documento.
   * @defaultValue (getdate())
   */
  @Column(col.defaultRaw(col.datetime<Date>(), '(getdate())'))
  data_registro?: Date;

  /**
   * Informações temporárias.
   * @defaultValue ((0))
   */
  @Column(col.defaultRaw(col.boolean(), '((0))'))
  dummy?: boolean;

  @BelongsToMany({ target: () => Comunicacao, pivotTable: () => DocumentoComunicacao, pivotForeignKeyToRoot: 'parent_id', pivotForeignKeyToTarget: 'comunicacao_id' })
  comunicacaos!: ManyToManyCollection<Comunicacao>;

  @HasMany({ target: () => OutroParametroDocumentoComunicacao, foreignKey: 'documento_comunicacao_id' })
  outroParametroDocumentoComunicacaos!: HasManyCollection<OutroParametroDocumentoComunicacao>;

  @BelongsTo({ target: () => Comunicacao, foreignKey: 'comunicacao_id' })
  comunicacao?: Comunicacao;

  @BelongsTo({ target: () => DocumentoComunicacao, foreignKey: 'parent_id' })
  parent?: DocumentoComunicacao;

  @HasMany({ target: () => DocumentoComunicacao, foreignKey: 'parent_id' })
  documentoComunicacaos!: HasManyCollection<DocumentoComunicacao>;

  @HasMany({ target: () => DocumentoProcessoAdministrativo, foreignKey: 'documento_comunicacao_id' })
  documentoProcessoAdministrativos!: HasManyCollection<DocumentoProcessoAdministrativo>;

  @HasMany({ target: () => DocumentoComunicacaoOutroParametro, foreignKey: 'documento_comunicacao_id' })
  documentoComunicacaoOutroParametros!: HasManyCollection<DocumentoComunicacaoOutroParametro>;

}
