// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, HasManyCollection, BelongsToReference } from 'metal-orm';
import { Manifestacao } from './Manifestacao.js';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';
import { TipoDocumento } from './TipoDocumento.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'documento_acordo_contencioso' })
export class DocumentoAcordoContencioso {
  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  @Column(col.text())
  nome?: string;

  @Column(col.text())
  descricao?: string;

  /**
   * @remarks References dbo.processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_contencioso_id!: number;

  /**
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id?: number;

  /**
   * @remarks References dbo.tipo_documento.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tipo_documento', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_documento_id?: number;

  @Column(col.blob())
  binario?: Buffer;

  @Column(col.varchar(50))
  mimetype?: string;

  @Column(col.varchar(5))
  extensao?: string;

  @Column(col.datetime<Date>())
  created?: Date;

  /**
   * @remarks References dbo.documento_acordo_contencioso.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'documento_acordo_contencioso', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  parent_id?: number;

  @Column(col.int())
  lft?: number;

  @Column(col.int())
  rght?: number;

  @HasMany({ target: () => Manifestacao, foreignKey: 'documento_acordo_contencioso_id' })
  manifestacaos!: HasManyCollection<Manifestacao>;

  @BelongsTo({ target: () => ProcessoAdministrativo, foreignKey: 'processo_contencioso_id' })
  processoContencioso!: BelongsToReference<ProcessoAdministrativo>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario!: BelongsToReference<Usuario>;

  @BelongsTo({ target: () => TipoDocumento, foreignKey: 'tipo_documento_id' })
  tipoDocumento!: BelongsToReference<TipoDocumento>;

  @BelongsTo({ target: () => DocumentoAcordoContencioso, foreignKey: 'parent_id' })
  parent!: BelongsToReference<DocumentoAcordoContencioso>;

  @HasMany({ target: () => DocumentoAcordoContencioso, foreignKey: 'parent_id' })
  documentoAcordoContenciosos!: HasManyCollection<DocumentoAcordoContencioso>;

}
