// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { FilaCircular } from './FilaCircular.js';

@Entity({ tableName: 'elemento_fila_circular' })
export class ElementoFilaCircular {
  /**
   * Armazena um identificador único para cada registro na tabela.
   */
  @PrimaryKey(col.notNull(col.int()))
  id!: number;

  /**
   * Armazena um identificador ou código que está relacionado a uma fila circular específica. Essa coluna é usada para associar cada elemento à fila circular à qual pertence.
   * @remarks References dbo.fila_circular.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'fila_circular', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  fila_circular_id!: number;

  /**
   * Armazena informações sobre os elementos que fazem parte de uma fila circular.
   */
  @Column(col.notNull(col.int()))
  elemento!: number;

  @BelongsTo({ target: () => FilaCircular, foreignKey: 'fila_circular_id' })
  filaCircular!: BelongsToReference<FilaCircular>;

}
