// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, HasManyCollection } from 'metal-orm';
import { RespostaTj } from './RespostaTj.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'entrega' })
export class Entrega {
  /**
   * Armazena um identificador único para cada registro na tabela.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Armazena a data em que ocorreu/ocorre uma entrega específica.
   */
  @Column(col.datetime<Date>())
  data?: Date;

  /**
   * Armazena informações relacionadas ao nome de usuário ou identificação do responsável pela entrega de algum item ou serviço.
   */
  @Column(col.text())
  login?: string;

  /**
   * Armazena o endereço IP associado à entrega de algum item ou serviço.
   */
  @Column(col.varchar(50))
  ip?: string;

  /**
   * Armazena um identificador ou código que está relacionado a um usuário específico envolvido na entrega de algum item ou serviço.
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id?: number;

  @HasMany({ target: () => RespostaTj, foreignKey: 'entrega_id' })
  respostaTjs!: HasManyCollection<RespostaTj>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario?: Usuario;

}
