// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, ManyToManyCollection } from 'metal-orm';
import { Acervo } from './Acervo.js';
import { AcervoEquipeApoio } from './AcervoEquipeApoio.js';
import { EquipeUsuario } from './EquipeUsuario.js';
import { Especializada } from './Especializada.js';
import { FilaCircular } from './FilaCircular.js';
import { RetornoProgramado } from './RetornoProgramado.js';
import { TramitacaoAutomaticaAcervoTema } from './TramitacaoAutomaticaAcervoTema.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'equipe' })
export class Equipe {
  /**
   * Identificador único.
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Nome da equipe.
   */
  @Column(col.notNull(col.text()))
  nome!: string;

  /**
   * Especializada em que a equipe se encontra.
   * @remarks References dbo.especializada.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'especializada', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  especializada_id!: number;

  /**
   * Informa a fila circular.
   * @remarks References dbo.fila_circular.id (on delete CASCADE, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'fila_circular', column: 'id', onDelete: 'CASCADE', onUpdate: 'NO ACTION' }))
  fila_circular_id?: number;

  @BelongsToMany({ target: () => Acervo, pivotTable: () => AcervoEquipeApoio, pivotForeignKeyToRoot: 'equipe_apoio_id', pivotForeignKeyToTarget: 'acervo_id' })
  acervos!: ManyToManyCollection<Acervo>;

  @BelongsToMany({ target: () => Usuario, pivotTable: () => EquipeUsuario, pivotForeignKeyToRoot: 'equipe_id', pivotForeignKeyToTarget: 'usuario_id' })
  usuarios!: ManyToManyCollection<Usuario>;

  @HasMany({ target: () => RetornoProgramado, foreignKey: 'equipe_id' })
  retornoProgramados!: HasManyCollection<RetornoProgramado>;

  @BelongsTo({ target: () => Especializada, foreignKey: 'especializada_id' })
  especializada?: Especializada;

  @BelongsTo({ target: () => FilaCircular, foreignKey: 'fila_circular_id' })
  filaCircular?: FilaCircular;

  @HasMany({ target: () => AcervoEquipeApoio, foreignKey: 'equipe_apoio_id' })
  acervoEquipeApoios!: HasManyCollection<AcervoEquipeApoio>;

  @HasMany({ target: () => Especializada, foreignKey: 'equipe_triagem_id' })
  especializadas!: HasManyCollection<Especializada>;

  @HasMany({ target: () => EquipeUsuario, foreignKey: 'equipe_id' })
  equipeUsuarios!: HasManyCollection<EquipeUsuario>;

  @HasMany({ target: () => TramitacaoAutomaticaAcervoTema, foreignKey: 'equipe_id' })
  tramitacaoAutomaticaAcervoTemas!: HasManyCollection<TramitacaoAutomaticaAcervoTema>;

}
