// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, HasManyCollection } from 'metal-orm';
import { ModeloFormularioProcessoAdministrativo } from './ModeloFormularioProcessoAdministrativo.js';
import { ModeloFormularioProcessoAdministrativoEstadoModeloFormulario } from './ModeloFormularioProcessoAdministrativoEstadoModeloFormulario.js';

@Entity({ tableName: 'estado_modelo_formulario' })
export class EstadoModeloFormulario {
  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  @Column(col.notNull(col.varchar(255)))
  nome!: string;

  @Column(col.varchar(3))
  codigo?: string;

  @HasMany({ target: () => ModeloFormularioProcessoAdministrativo, foreignKey: 'ultimo_estado_modelo_formulario_id' })
  modelosFormularioProcessoAdministrativo!: HasManyCollection<ModeloFormularioProcessoAdministrativo>;

  @HasMany({ target: () => ModeloFormularioProcessoAdministrativoEstadoModeloFormulario, foreignKey: 'estado_modelo_formulario_id' })
  modelosFormularioProcessoAdministrativoEstadoModeloFormulario!: HasManyCollection<ModeloFormularioProcessoAdministrativoEstadoModeloFormulario>;

}
