// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, BelongsToReference, ManyToManyCollection } from 'metal-orm';
import { Estado } from './Estado.js';
import { EstadoProcessoAdministrativoMotivoArquivamento } from './EstadoProcessoAdministrativoMotivoArquivamento.js';
import { MotivoArquivamento } from './MotivoArquivamento.js';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'estado_processo_administrativo' })
export class EstadoProcessoAdministrativo {
  /**
   * Identificador do estado processo administrativo
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador do processo administrativo
   * @remarks References dbo.processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_administrativo_id!: number;

  /**
   * Identificador do estado
   * @remarks References dbo.estado.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'estado', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  estado_id!: number;

  /**
   * Representa o momento específico em que ocorreu uma determinada mudança de estado em um processo administrativo.
   */
  @Column(col.notNull(col.datetime<Date>()))
  data_hora!: Date;

  /**
   * Identificador do usuário
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id?: number;

  /**
   * Se refere à data em que um processo administrativo foi retornado de um estado anterior para um estado subsequente.
   */
  @Column(col.date<Date>())
  data_retorno?: Date;

  @BelongsToMany({ target: () => MotivoArquivamento, pivotTable: () => EstadoProcessoAdministrativoMotivoArquivamento, pivotForeignKeyToRoot: 'estado_processo_administrativo_id', pivotForeignKeyToTarget: 'motivo_arquivamento_id' })
  motivoArquivamentos!: ManyToManyCollection<MotivoArquivamento>;

  @BelongsTo({ target: () => ProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  processoAdministrativo!: BelongsToReference<ProcessoAdministrativo>;

  @BelongsTo({ target: () => Estado, foreignKey: 'estado_id' })
  estado!: BelongsToReference<Estado>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario!: BelongsToReference<Usuario>;

  @HasMany({ target: () => EstadoProcessoAdministrativoMotivoArquivamento, foreignKey: 'estado_processo_administrativo_id' })
  estadoProcessoAdministrativoMotivoArquivamentos!: HasManyCollection<EstadoProcessoAdministrativoMotivoArquivamento>;

}
