// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { Acervo } from './Acervo.js';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'historico_distribuicao_acervo' })
export class HistoricoDistribuicaoAcervo {
  /**
   * Identificador do histórico distribuição acervo
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador do processo administrativo
   * @remarks References dbo.processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_administrativo_id!: number;

  /**
   * Identificador do acervo
   * @remarks References dbo.acervo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'acervo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  acervo_id!: number;

  /**
   * Identificador da ação do usuário
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_acao_id!: number;

  /**
   * Identificador do titular do acervo
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  titular_acervo_id!: number;

  /**
   * Identificador do destinatário
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  destinatario_id!: number;

  /**
   * Registra o horário exato em que a distribuição para o acervo ocorreu.
   */
  @Column(col.notNull(col.datetime<Date>()))
  horario_distribuicao!: Date;

  /**
   * Registra o endereço IP associado ao evento de distribuição a um acervo.
   */
  @Column(col.notNull(col.varchar(15)))
  ip!: string;

  @BelongsTo({ target: () => ProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  processoAdministrativo!: BelongsToReference<ProcessoAdministrativo>;

  @BelongsTo({ target: () => Acervo, foreignKey: 'acervo_id' })
  acervo!: BelongsToReference<Acervo>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_acao_id' })
  usuarioAcao!: BelongsToReference<Usuario>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'titular_acervo_id' })
  titularAcervo!: BelongsToReference<Usuario>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'destinatario_id' })
  destinatario!: BelongsToReference<Usuario>;

}
