// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { AvisoPendente } from './AvisoPendente.js';

@Entity({ tableName: 'instantaneo_aviso_pendente' })
export class InstantaneoAvisoPendente {
  /**
   * Identificador do instantâneo aviso pendente
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador do aviso pendente
   * @remarks References dbo.aviso_pendente.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'aviso_pendente', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  aviso_pendente_id!: number;

  /**
   * Armazena o número associado a um processo judicial específico que está pendente de alguma ação ou notificação.
   */
  @Column(col.notNull(col.varchar(20)))
  numero_processo_judicial!: string;

  /**
   * Armazena o número associado a um processo específico que tem uma notificação ou aviso pendente.
   */
  @Column(col.varchar(20))
  numero_processo?: string;

  /**
   * Armazena informações sobre a tabela de domínio ou entidade que contém os detalhes do processo relacionado a um aviso pendente.
   */
  @Column(col.text())
  tabela_dominio_processo?: string;

  /**
   * Armazena informações sobre a coluna específica na tabela de domínio ou entidade que contém os detalhes do processo relacionado a um aviso pendente.
   */
  @Column(col.text())
  coluna_dominio_processo?: string;

  /**
   * Armazena um código ou identificador único que representa uma unidade ou departamento específico relacionado a um aviso pendente.
   */
  @Column(col.varchar(8))
  codigo_unidade?: string;

  /**
   * Armazena o nome da unidade ou departamento específico relacionado a um aviso pendente.
   */
  @Column(col.varchar(70))
  nome_unidade?: string;

  /**
   * Armazena um código que representa um servidor específico relacionado a um aviso pendente.
   */
  @Column(col.varchar(4))
  codigo_servidor?: string;

  /**
   * Armazena o nome do servidor específico relacionado a um aviso pendente.
   */
  @Column(col.varchar(60))
  nome_servidor?: string;

  /**
   * Armazena informações relacionadas ao despacho em relação a um aviso pendente.
   */
  @Column(col.text())
  despacho?: string;

  /**
   * Armazena informações sobre a tabela de domínio que contém os detalhes do despacho relacionado a um aviso pendente.
   */
  @Column(col.text())
  tabela_dominio_despacho?: string;

  /**
   * Registra a pessoa responsável pela última distribuição de um aviso pendente.
   */
  @Column(col.varchar(60))
  ultima_distribuicao?: string;

  /**
   * Armazena o nome do autor associado a um aviso pendente.
   */
  @Column(col.varchar(170))
  nome_autor?: string;

  /**
   * Armazena um códig associado ao autor de um aviso pendente.
   */
  @Column(col.varchar(10))
  codigo_autor?: string;

  /**
   * Registra a data e hora em que um aviso pendente foi gerado, criado ou recebido.
   */
  @Column(col.notNull(col.datetime<Date>()))
  data_hora!: Date;

  /**
   * Armazena informações sobre a classificação do aviso pendente.
   */
  @Column(col.varchar(30))
  classificacao?: string;

  /**
   * Armazena informações sobre a presença de outros processos administrativos relacionados que foram encontrados em conjunto com o aviso pendente.
   */
  @Column(col.text())
  outros_administrativos_encontrados?: string;

  @BelongsTo({ target: () => AvisoPendente, foreignKey: 'aviso_pendente_id' })
  avisoPendente!: BelongsToReference<AvisoPendente>;

}
