// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, BelongsToReference, ManyToManyCollection } from 'metal-orm';
import { Especializada } from './Especializada.js';
import { MapeamentoLocalidadeRegional } from './MapeamentoLocalidadeRegional.js';
import { MniTribunal } from './MniTribunal.js';
import { ProcessoJudicial } from './ProcessoJudicial.js';

@Entity({ tableName: 'localidade' })
export class Localidade {
  /**
   * Identificador da localidade
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador do local do tribunal
   */
  @Column(col.varchar(50))
  id_local_tribunal?: string;

  /**
   * Identificador do tribunal
   * @remarks References dbo.mni_tribunal.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'mni_tribunal', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tribunal_id?: number;

  /**
   * Armazena uma descrição textual que descreve uma localidade específica.
   */
  @Column(col.notNull(col.text()))
  descricao!: string;

  /**
   * Informa a localidade pai entre as localidades
   * @remarks References dbo.localidade.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'localidade', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  parent_id?: number;

  @BelongsToMany({ target: () => MniTribunal, pivotTable: () => Localidade, pivotForeignKeyToRoot: 'parent_id', pivotForeignKeyToTarget: 'tribunal_id' })
  mnisTribunal!: ManyToManyCollection<MniTribunal>;

  @BelongsToMany({ target: () => Especializada, pivotTable: () => MapeamentoLocalidadeRegional, pivotForeignKeyToRoot: 'localidade_id', pivotForeignKeyToTarget: 'especializada_regional_id' })
  especializadas!: ManyToManyCollection<Especializada>;

  @HasMany({ target: () => ProcessoJudicial, foreignKey: 'localidade_id' })
  processosJudicial!: HasManyCollection<ProcessoJudicial>;

  @BelongsTo({ target: () => MniTribunal, foreignKey: 'tribunal_id' })
  tribunal!: BelongsToReference<MniTribunal>;

  @BelongsTo({ target: () => Localidade, foreignKey: 'parent_id' })
  parent!: BelongsToReference<Localidade>;

  @HasMany({ target: () => Localidade, foreignKey: 'parent_id' })
  localidades!: HasManyCollection<Localidade>;

  @HasMany({ target: () => MapeamentoLocalidadeRegional, foreignKey: 'localidade_id' })
  mapeamentosLocalidadeRegional!: HasManyCollection<MapeamentoLocalidadeRegional>;

}
