// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'marcador_documento_processo_judicial' })
export class MarcadorDocumentoProcessoJudicial {
  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * @remarks References dbo.usuario.id (on delete CASCADE, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'CASCADE', onUpdate: 'NO ACTION' }))
  usuario_id?: number;

  @Column(col.varchar(128))
  documento_processo_judicial_id?: string;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario?: Usuario;

}
