// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { Modelo } from './Modelo.js';
import { Tema } from './Tema.js';

@Entity({ tableName: 'modelo_tema' })
export class ModeloTema {
  /**
   * Identificador do modelo tema
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador do modelo
   * @remarks References dbo.modelo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'modelo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  modelo_id!: number;

  /**
   * Identificador do tema
   * @remarks References dbo.tema.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'tema', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tema_id!: number;

  /**
   * Distribuição automática do modelo de tema
   * @defaultValue ((0))
   */
  @Column(col.defaultRaw(col.boolean(), '((0))'))
  distribuicao_automatica?: boolean;

  @BelongsTo({ target: () => Modelo, foreignKey: 'modelo_id' })
  modelo?: Modelo;

  @BelongsTo({ target: () => Tema, foreignKey: 'tema_id' })
  tema?: Tema;

}
