// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, HasManyCollection } from 'metal-orm';
import { ProcessoAdministrativoProcessoAdministrativo } from './ProcessoAdministrativoProcessoAdministrativo.js';
import { ProcessoFisicoAssociado } from './ProcessoFisicoAssociado.js';

@Entity({ tableName: 'motivo_associacao' })
export class MotivoAssociacao {
  /**
   * Identificador do motivo associação
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Descreve o motivo da associação
   */
  @Column(col.notNull(col.text()))
  nome!: string;

  @HasMany({ target: () => ProcessoAdministrativoProcessoAdministrativo, foreignKey: 'motivo_associacao_id' })
  processoAdministrativoProcessoAdministrativos!: HasManyCollection<ProcessoAdministrativoProcessoAdministrativo>;

  @HasMany({ target: () => ProcessoFisicoAssociado, foreignKey: 'motivo_associacao_id' })
  processoFisicoAssociados!: HasManyCollection<ProcessoFisicoAssociado>;

}
