// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, HasManyCollection } from 'metal-orm';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';

@Entity({ tableName: 'natureza_incidente' })
export class NaturezaIncidente {
  /**
   * Identificador da natureza incidente
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Armazena o nome da natureza de um incidente específico.
   */
  @Column(col.notNull(col.varchar(255)))
  nome!: string;

  @HasMany({ target: () => ProcessoAdministrativo, foreignKey: 'natureza_incidente_id' })
  processosAdministrativo!: HasManyCollection<ProcessoAdministrativo>;

}
