// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { Comunicacao } from './Comunicacao.js';

@Entity({ tableName: 'outro_parametro_comunicacao' })
export class OutroParametroComunicacao {
  /**
   * Identificador outro parâmetro comunicação
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Nome do outro parâmetro comunicação
   */
  @Column(col.text())
  nome?: string;

  /**
   * Armazena o valor.
   */
  @Column(col.text())
  valor?: string;

  /**
   * Identificador da comunicação
   * @remarks References dbo.comunicacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'comunicacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  comunicacao_id!: number;

  @BelongsTo({ target: () => Comunicacao, foreignKey: 'comunicacao_id' })
  comunicacao?: Comunicacao;

}
