// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsToMany, HasManyCollection, ManyToManyCollection } from 'metal-orm';
import { PalavraChaveProcessoAdministrativo } from './PalavraChaveProcessoAdministrativo.js';
import { PalavraChaveTema } from './PalavraChaveTema.js';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';
import { Tema } from './Tema.js';

@Entity({ tableName: 'palavra_chave' })
export class PalavraChave {
  /**
   * Identificador da palavra-chave
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Palavra a ser usada
   */
  @Column(col.unique(col.varchar(127)))
  palavra?: string;

  /**
   * Controlar o formato de uma palavra-chave
   */
  @Column(col.varchar(300))
  mascara?: string;

  /**
   * Se a Palavra chave possui alguma obrigatoridade
   */
  @Column(col.notNull(col.boolean()))
  obrigatoriedade!: boolean;

  @BelongsToMany({ target: () => ProcessoAdministrativo, pivotTable: () => PalavraChaveProcessoAdministrativo, pivotForeignKeyToRoot: 'palavra_chave_id', pivotForeignKeyToTarget: 'processo_administrativo_id' })
  processoAdministrativos!: ManyToManyCollection<ProcessoAdministrativo>;

  @BelongsToMany({ target: () => Tema, pivotTable: () => PalavraChaveTema, pivotForeignKeyToRoot: 'palavra_chave_id', pivotForeignKeyToTarget: 'tema_id' })
  temas!: ManyToManyCollection<Tema>;

  @HasMany({ target: () => PalavraChaveProcessoAdministrativo, foreignKey: 'palavra_chave_id' })
  palavraChaveProcessoAdministrativos!: HasManyCollection<PalavraChaveProcessoAdministrativo>;

  @HasMany({ target: () => PalavraChaveTema, foreignKey: 'palavra_chave_id' })
  palavraChaveTemas!: HasManyCollection<PalavraChaveTema>;

}
