// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { Parte } from './Parte.js';
import { RepresentanteJudicial } from './RepresentanteJudicial.js';

@Entity({ tableName: 'parte_representante' })
export class ParteRepresentante {
  /**
   * Identificador parte representante
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador da parte
   * @remarks References dbo.parte.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'parte', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  parte_id?: number;

  /**
   * Identificador do representante judicial
   * @remarks References dbo.representante_judicial.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'representante_judicial', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  representante_judicial_id?: number;

  @BelongsTo({ target: () => Parte, foreignKey: 'parte_id' })
  parte?: Parte;

  @BelongsTo({ target: () => RepresentanteJudicial, foreignKey: 'representante_judicial_id' })
  representanteJudicial?: RepresentanteJudicial;

}
