// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, HasManyCollection, BelongsToReference } from 'metal-orm';
import { Carga } from './Carga.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'pasta_caixa_entrada' })
export class PastaCaixaEntrada {
  /**
   * Identificador pasta caixa entrada
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Nome da pasta
   */
  @Column(col.notNull(col.text()))
  nome!: string;

  /**
   * Cor da pasta
   */
  @Column(col.varchar(50))
  cor?: string;

  /**
   * Login do usuário responsável pela pasta na Caixa de Entrada
   */
  @Column(col.varchar(50))
  ldap_user?: string;

  /**
   * Identificador do usuário
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id?: number;

  @HasMany({ target: () => Carga, foreignKey: 'pasta_id' })
  cargas!: HasManyCollection<Carga>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario!: BelongsToReference<Usuario>;

}
