// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { PedidoComplementar } from './PedidoComplementar.js';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';

@Entity({ tableName: 'pedido_complementar_processo_administrativo' })
export class PedidoComplementarProcessoAdministrativo {
  /**
   * Identificador do pedido complementar processo administrativo
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador do pedido complementar
   * @remarks References dbo.pedido_complementar.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'pedido_complementar', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  pedido_complementar_id!: number;

  /**
   * Identificador do processo administrativo
   * @remarks References dbo.processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_administrativo_id!: number;

  @BelongsTo({ target: () => PedidoComplementar, foreignKey: 'pedido_complementar_id' })
  pedidoComplementar?: PedidoComplementar;

  @BelongsTo({ target: () => ProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  processoAdministrativo?: ProcessoAdministrativo;

}
