// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { Especializada } from './Especializada.js';
import { OrgaoJulgador } from './OrgaoJulgador.js';

@Entity({ tableName: 'predicao_orgao_julgador_especializada' })
export class PredicaoOrgaoJulgadorEspecializada {
  /**
   * Identificador orgão julgador especializada
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador do orgão julgador
   * @remarks References dbo.orgao_julgador.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'orgao_julgador', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  orgao_julgador_id!: number;

  /**
   * Identificador da especializada
   * @remarks References dbo.especializada.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'especializada', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  especializada_id!: number;

  @BelongsTo({ target: () => OrgaoJulgador, foreignKey: 'orgao_julgador_id' })
  orgaoJulgador!: BelongsToReference<OrgaoJulgador>;

  @BelongsTo({ target: () => Especializada, foreignKey: 'especializada_id' })
  especializada!: BelongsToReference<Especializada>;

}
