// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey } from 'metal-orm';

@Entity({ tableName: 'processo_judicial_outro_parametro' })
export class ProcessoJudicialOutroParametro {
  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Refere-se ao nome do processo judicial
   */
  @Column(col.varchar(255))
  nome?: string;

  /**
   * Valor do processo judicial
   */
  @Column(col.text())
  valor?: string;

  /**
   * É identificador  do processo judicial, no qual conseguimos localizar o processo pelo mesmo
   */
  @Column(col.int())
  processo_judicial_id?: number;

}
