// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';
import { Tema } from './Tema.js';

@Entity({ tableName: 'processo_administrativo_tema' })
export class ProcessoAdministrativoTema {
  /**
   * Identificador do tema do processo administrativo
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador do processo administrativo
   * @remarks References dbo.processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_administrativo_id!: number;

  /**
   * Identificador do tema
   * @remarks References dbo.tema.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'tema', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tema_id!: number;

  @BelongsTo({ target: () => ProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  processoAdministrativo?: ProcessoAdministrativo;

  @BelongsTo({ target: () => Tema, foreignKey: 'tema_id' })
  tema?: Tema;

}
