// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, HasOne, BelongsTo, BelongsToMany, HasManyCollection, HasOneReference, ManyToManyCollection } from 'metal-orm';
import { Acompanhamento } from './Acompanhamento.js';
import { AssuntoLocal } from './AssuntoLocal.js';
import { AssuntoProcessoJudicial } from './AssuntoProcessoJudicial.js';
import { Atividade } from './Atividade.js';
import { Cda } from './Cda.js';
import { Competencia } from './Competencia.js';
import { Comunicacao } from './Comunicacao.js';
import { DecisaoJudicial } from './DecisaoJudicial.js';
import { Especializada } from './Especializada.js';
import { Localidade } from './Localidade.js';
import { Magistrado } from './Magistrado.js';
import { MagistradoProcesso } from './MagistradoProcesso.js';
import { MemoriaCalculo } from './MemoriaCalculo.js';
import { MniTribunal } from './MniTribunal.js';
import { NivelSigilo } from './NivelSigilo.js';
import { OrgaoJulgador } from './OrgaoJulgador.js';
import { Parte } from './Parte.js';
import { PredicaoEspecializadaMachineLearning } from './PredicaoEspecializadaMachineLearning.js';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';
import { ProcessoJudicialHash } from './ProcessoJudicialHash.js';
import { ProcessoJudicialOriginario } from './ProcessoJudicialOriginario.js';
import { ProcessoJudicialOutroNumero } from './ProcessoJudicialOutroNumero.js';
import { ProcessoVinculado } from './ProcessoVinculado.js';
import { RaioXJuridico } from './RaioXJuridico.js';
import { RegistroMigracaoSicaj } from './RegistroMigracaoSicaj.js';
import { TipoAtividade } from './TipoAtividade.js';

@Entity({ tableName: 'processo_judicial' })
export class ProcessoJudicial {
  /**
   * Identificador do processo judicial
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * É um código único atribuído a um caso legal específico perante um tribunal. Esse número serve para identificar e acompanhar o processo ao longo de suas etapas
   */
  @Column(col.notNull(col.varchar(20)))
  numero!: string;

  /**
   * Identificador do tribunal
   * @remarks References dbo.mni_tribunal.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'mni_tribunal', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tribunal_id?: number;

  /**
   * Atribuição de importância ao processo judicial
   */
  @Column(col.text())
  prioridade?: string;

  /**
   * Se refere à quantia financeira associada a um processo judicial.
   */
  @Column(col.decimal(18, 2))
  valor_causa?: number;

  /**
   * Identificador do orgão julgador
   * @remarks References dbo.orgao_julgador.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'orgao_julgador', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  orgao_julgador_id?: number;

  /**
   * identificador da competência jurídica
   * @remarks References dbo.competencia.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'competencia', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  competencia_id?: number;

  /**
   * Refere-se a um identificador único atribuído a uma classe processual
   */
  @Column(col.int())
  classe_processual_id?: number;

  /**
   * Quantidade de informações, documentos ou conteúdo geral contido em um processo legal
   */
  @Column(col.bigint())
  tamanho_processo?: number;

  /**
   * Se refere à data em que um processo legal é oficialmente apresentado a um tribunal
   */
  @Column(col.datetime<Date>())
  data_ajuizamento?: Date;

  /**
   * identificador do nível de sigilo
   * @remarks References dbo.nivel_sigilo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'nivel_sigilo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  nivel_sigilo_id?: number;

  /**
   * identificador do parent
   * @remarks References dbo.processo_judicial.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'processo_judicial', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  parent_id?: number;

  /**
   * Refere-se à participação do Ministério Público em um processo judicial como parte interessada
   */
  @Column(col.boolean())
  intervencao_mp?: boolean;

  /**
   * Refere-se ao identificador de localidade do processo judicial
   * @remarks References dbo.localidade.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'localidade', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  localidade_id?: number;

  /**
   * Refere-se à data em que um documento, pedido, processo ou objeto é oficialmente apresentado
   */
  @Column(col.datetime<Date>())
  data_entrada?: Date;

  /**
   * processo judicial originario
   * @remarks References dbo.processo_judicial.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'processo_judicial', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  originario_id?: number;

  @BelongsToMany({ target: () => AssuntoLocal, pivotTable: () => AssuntoProcessoJudicial, pivotForeignKeyToRoot: 'processo_judicial_id', pivotForeignKeyToTarget: 'assunto_local_id' })
  assuntoLocals!: ManyToManyCollection<AssuntoLocal>;

  @BelongsToMany({ target: () => TipoAtividade, pivotTable: () => Atividade, pivotForeignKeyToRoot: 'processo_judicial_id', pivotForeignKeyToTarget: 'tipo_atividade_id' })
  tipoAtividades!: ManyToManyCollection<TipoAtividade>;

  @BelongsToMany({ target: () => Especializada, pivotTable: () => PredicaoEspecializadaMachineLearning, pivotForeignKeyToRoot: 'processo_judicial_id', pivotForeignKeyToTarget: 'especializada_id' })
  especializadas!: ManyToManyCollection<Especializada>;

  @BelongsToMany({ target: () => Magistrado, pivotTable: () => MagistradoProcesso, pivotForeignKeyToRoot: 'processo_judicial_id', pivotForeignKeyToTarget: 'magistrado_id' })
  magistrados!: ManyToManyCollection<Magistrado>;

  @BelongsTo({ target: () => MniTribunal, foreignKey: 'tribunal_id' })
  tribunal?: MniTribunal;

  @BelongsTo({ target: () => OrgaoJulgador, foreignKey: 'orgao_julgador_id' })
  orgaoJulgador?: OrgaoJulgador;

  @BelongsTo({ target: () => Competencia, foreignKey: 'competencia_id' })
  competencia?: Competencia;

  @BelongsTo({ target: () => NivelSigilo, foreignKey: 'nivel_sigilo_id' })
  nivelSigilo?: NivelSigilo;

  @BelongsTo({ target: () => ProcessoJudicial, foreignKey: 'parent_id' })
  parent?: ProcessoJudicial;

  @HasMany({ target: () => ProcessoJudicial, foreignKey: 'parent_id' })
  processoJudicials!: HasManyCollection<ProcessoJudicial>;

  @BelongsTo({ target: () => Localidade, foreignKey: 'localidade_id' })
  localidade?: Localidade;

  @BelongsTo({ target: () => ProcessoJudicial, foreignKey: 'originario_id' })
  originario?: ProcessoJudicial;

  @HasMany({ target: () => ProcessoJudicialOriginario, foreignKey: 'processo_judicial_id' })
  processoJudicialOriginarios!: HasManyCollection<ProcessoJudicialOriginario>;

  @HasMany({ target: () => ProcessoJudicialOutroNumero, foreignKey: 'processo_judicial_id' })
  processoJudicialOutroNumeros!: HasManyCollection<ProcessoJudicialOutroNumero>;

  @HasMany({ target: () => Parte, foreignKey: 'processo_judicial_id' })
  partes!: HasManyCollection<Parte>;

  @HasMany({ target: () => RaioXJuridico, foreignKey: 'processo_judicial_id' })
  raioXJuridicos!: HasManyCollection<RaioXJuridico>;

  @HasMany({ target: () => ProcessoAdministrativo, foreignKey: 'processo_judicial_id' })
  processoAdministrativos!: HasManyCollection<ProcessoAdministrativo>;

  @HasMany({ target: () => DecisaoJudicial, foreignKey: 'processo_judicial_id' })
  decisaoJudicials!: HasManyCollection<DecisaoJudicial>;

  @HasMany({ target: () => RegistroMigracaoSicaj, foreignKey: 'processo_judicial_id' })
  registroMigracaoSicajs!: HasManyCollection<RegistroMigracaoSicaj>;

  @HasMany({ target: () => ProcessoVinculado, foreignKey: 'processo_judicial_id' })
  processoVinculados!: HasManyCollection<ProcessoVinculado>;

  @HasMany({ target: () => Acompanhamento, foreignKey: 'processo_judicial_id' })
  acompanhamentos!: HasManyCollection<Acompanhamento>;

  @HasMany({ target: () => AssuntoProcessoJudicial, foreignKey: 'processo_judicial_id' })
  assuntoProcessoJudicials!: HasManyCollection<AssuntoProcessoJudicial>;

  @HasMany({ target: () => Atividade, foreignKey: 'processo_judicial_id' })
  atividades!: HasManyCollection<Atividade>;

  @HasMany({ target: () => Comunicacao, foreignKey: 'processo_judicial_id' })
  comunicacaos!: HasManyCollection<Comunicacao>;

  @HasMany({ target: () => MemoriaCalculo, foreignKey: 'processo_judicial_id' })
  memoriaCalculos!: HasManyCollection<MemoriaCalculo>;

  @HasOne({ target: () => ProcessoJudicialHash, foreignKey: 'processo_judicial_id' })
  processoJudicialHash!: HasOneReference<ProcessoJudicialHash>;

  @HasMany({ target: () => Cda, foreignKey: 'processo_judicial_id' })
  cdas!: HasManyCollection<Cda>;

  @HasMany({ target: () => PredicaoEspecializadaMachineLearning, foreignKey: 'processo_judicial_id' })
  predicaoEspecializadaMachineLearnings!: HasManyCollection<PredicaoEspecializadaMachineLearning>;

  @HasMany({ target: () => MagistradoProcesso, foreignKey: 'processo_judicial_id' })
  magistradoProcessos!: HasManyCollection<MagistradoProcesso>;

}
