// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, BelongsToReference, ManyToManyCollection } from 'metal-orm';
import { Acervo } from './Acervo.js';
import { Acordo } from './Acordo.js';
import { Audiencia } from './Audiencia.js';
import { Carga } from './Carga.js';
import { Classificacao } from './Classificacao.js';
import { CodigoExterno } from './CodigoExterno.js';
import { CodigoExternoProcessoAdministrativo } from './CodigoExternoProcessoAdministrativo.js';
import { DocumentoAcordoContencioso } from './DocumentoAcordoContencioso.js';
import { DocumentoAnexoRascunho } from './DocumentoAnexoRascunho.js';
import { DocumentoProcessoAdministrativo } from './DocumentoProcessoAdministrativo.js';
import { DocumentoRascunho } from './DocumentoRascunho.js';
import { Especializada } from './Especializada.js';
import { Estado } from './Estado.js';
import { EstadoProcessoAdministrativo } from './EstadoProcessoAdministrativo.js';
import { ExitoSucumbencia } from './ExitoSucumbencia.js';
import { HistoricoDistribuicaoAcervo } from './HistoricoDistribuicaoAcervo.js';
import { HistoricoDistribuicaoEspecializada } from './HistoricoDistribuicaoEspecializada.js';
import { Interessado } from './Interessado.js';
import { InteressadoConsultivo } from './InteressadoConsultivo.js';
import { Manifestacao } from './Manifestacao.js';
import { Materia } from './Materia.js';
import { ModeloFormularioProcessoAdministrativo } from './ModeloFormularioProcessoAdministrativo.js';
import { NaturezaIncidente } from './NaturezaIncidente.js';
import { PalavraChave } from './PalavraChave.js';
import { PalavraChaveProcessoAdministrativo } from './PalavraChaveProcessoAdministrativo.js';
import { PedidoComplementar } from './PedidoComplementar.js';
import { PedidoComplementarProcessoAdministrativo } from './PedidoComplementarProcessoAdministrativo.js';
import { ProcessoAdministrativoProcessoAdministrativo } from './ProcessoAdministrativoProcessoAdministrativo.js';
import { ProcessoAdministrativoTema } from './ProcessoAdministrativoTema.js';
import { ProcessoFisicoAssociado } from './ProcessoFisicoAssociado.js';
import { ProcessoJudicial } from './ProcessoJudicial.js';
import { RegistroTramitacao } from './RegistroTramitacao.js';
import { RetornoProgramado } from './RetornoProgramado.js';
import { Solicitacao } from './Solicitacao.js';
import { SorteioCorreicaoProcessoAdministrativo } from './SorteioCorreicaoProcessoAdministrativo.js';
import { Tema } from './Tema.js';
import { TipoProcessoAdministrativo } from './TipoProcessoAdministrativo.js';
import { Urgencia } from './Urgencia.js';
import { Usuario } from './Usuario.js';
import { UsuarioPermitidoAcessarProcessoAdministrativoSigiloso } from './UsuarioPermitidoAcessarProcessoAdministrativoSigiloso.js';
import { ValorAdicional } from './ValorAdicional.js';

@Entity({ tableName: 'processo_administrativo' })
export class ProcessoAdministrativo {
  /**
   * Identificador do processo administrativo
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador único do exito de sucumbência.
   * @remarks References dbo.exito_sucumbencia.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'exito_sucumbencia', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  exito_sucumbencia_id?: number;

  /**
   * Identificador único da especializada.
   * @remarks References dbo.especializada.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'especializada', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  especializada_id!: number;

  /**
   * Identificador único da classificação.
   * @remarks References dbo.classificacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'classificacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  classificacao_id?: number;

  /**
   * Identificador único da matéria.
   * @remarks References dbo.materia.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'materia', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  materia_id?: number;

  /**
   * Acompanhar um processo judicial envolve estar informado sobre os acontecimentos e procedimentos legais de um caso em andamento perante um tribunal.
   */
  @Column(col.notNull(col.boolean()))
  acompanha_processo_judicial!: boolean;

  /**
   * Sigilo interno envolve a restrição cuidadosa do acesso e divulgação de informações sensíveis dentro de uma entidade
   */
  @Column(col.notNull(col.boolean()))
  sigilo_interno!: boolean;

  /**
   * Sequencia de números do processo administrativo
   */
  @Column(col.varchar(25))
  codigo_pa?: string;

  /**
   * Identificador único do tema principal.
   * @remarks References dbo.tema.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tema', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tema_principal_id?: number;

  /**
   * Armazena o criador.
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  criador?: number;

  /**
   * Armazena o responsável judicial.
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  responsavel_judicial?: number;

  /**
   * Armazena o responsável administrativo.
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  responsavel_administrativo?: number;

  /**
   * Identificador único da urgência.
   * @remarks References dbo.urgencia.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'urgencia', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  urgencia_id?: number;

  /**
   * "Data criação" se refere ao momento em que processo administrativo foi criado ou produzido
   */
  @Column(col.datetime<Date>())
  data_criacao?: Date;

  /**
   * Identificador único do estado.
   * @remarks References dbo.estado.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'estado', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  estado_id?: number;

  /**
   * Refere-se à quantia monetária associada a uma ação judicial
   */
  @Column(col.decimal(18, 2))
  valor_causa?: number;

  /**
   * É a quantia financeira que uma parte envolvida em um processo legal
   */
  @Column(col.decimal(18, 2))
  valor_economico_demanda?: number;

  /**
   * "Valor condenação" é o montante financeiro que uma parte é ordenada a pagar como resultado de uma decisão judicial.
   */
  @Column(col.decimal(18, 2))
  valor_condenacao?: number;

  /**
   * refere-se ao segundo valor do processo judicial
   */
  @Column(col.decimal(18, 2))
  valor_segundo?: number;

  /**
   * Se refere ao montante mínimo necessário para que um processo judicial seja encaminhado aos tribunais superiores em um sistema de jurisdição hierárquica.
   */
  @Column(col.decimal(18, 2))
  valor_tribunais_superiores?: number;

  /**
   * Identificador único do acervo.
   * @remarks References dbo.acervo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'acervo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  acervo_id?: number;

  /**
   * Identificador único do processo judicial.
   * @remarks References dbo.processo_judicial.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'processo_judicial', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_judicial_id?: number;

  /**
   * É a quantia monetária que uma parte vencedora em um processo judicial tem o direito de receber da parte perdedora
   */
  @Column(col.decimal(18, 2))
  valor_execucao?: number;

  /**
   * Se refere à importância ou benefício que a obtenção de informações detalhadas e insights de uma análise pode trazer.
   */
  @Column(col.decimal(18, 2))
  valor_analise?: number;

  /**
   * Refere-se à quantia oficialmente aprovada e confirmada por uma autoridade competente
   */
  @Column(col.decimal(18, 2))
  valor_homologado?: number;

  /**
   * Se refere a uma ordem de pagamento emitida por um tribunal, geralmente em resposta a uma decisão judicial que obriga uma entidade governamental a pagar uma quantia específica a um indivíduo ou entidade
   */
  @Column(col.decimal(18, 2))
  valor_precatorio?: number;

  /**
   * Se refere à quantia monetária que foi efetivamente desembolsada ou transferida como pagamento por bens, serviços, dívidas ou outras obrigações financeiras.
   */
  @Column(col.decimal(18, 2))
  valor_pago?: number;

  /**
   * Armazena o responsável substituto.
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  responsavel_substituto?: number;

  /**
   * Se refere a informações complementares relacionadas ao processo administrativo
   */
  @Column(col.text())
  informacao_complementar?: string;

  /**
   * É um termo usado para indicar que o processo administrativo foi cancelado
   * @defaultValue ((0))
   */
  @Column(col.defaultRaw(col.boolean(), '((0))'))
  cancelado?: boolean;

  /**
   * Refere-se ao tipo de criação do processo administrativo
   */
  @Column(col.varchar(1))
  tipo_criacao?: string;

  /**
   * Armazena o identificador único da natureza do incidente.
   * @remarks References dbo.natureza_incidente.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'natureza_incidente', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  natureza_incidente_id?: number;

  /**
   * Armazena o identificador único do tipo do processo administrativo.
   * @defaultValue ((1))
   * @remarks References dbo.tipo_processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.defaultRaw(col.notNull(col.int()), '((1))'), { table: 'tipo_processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_processo_administrativo_id!: number;

  /**
   * Se refere à quantificação aproximada dos efeitos ou consequências que uma ação, decisão ou evento pode ter em termos financeiros, sociais, ambientais ou outros aspectos relevantes.
   * @defaultValue (NULL)
   */
  @Column(col.defaultRaw(col.decimal(18, 2), '(NULL)'))
  valor_estimativa_impacto?: number;

  @BelongsToMany({ target: () => PalavraChave, pivotTable: () => PalavraChaveProcessoAdministrativo, pivotForeignKeyToRoot: 'processo_administrativo_id', pivotForeignKeyToTarget: 'palavra_chave_id' })
  palavrasChave!: ManyToManyCollection<PalavraChave>;

  @BelongsToMany({ target: () => Tema, pivotTable: () => ProcessoAdministrativoTema, pivotForeignKeyToRoot: 'processo_administrativo_id', pivotForeignKeyToTarget: 'tema_id' })
  temas!: ManyToManyCollection<Tema>;

  @BelongsToMany({ target: () => CodigoExterno, pivotTable: () => CodigoExternoProcessoAdministrativo, pivotForeignKeyToRoot: 'processo_administrativo_id', pivotForeignKeyToTarget: 'codigo_externo_id' })
  codigosExterno!: ManyToManyCollection<CodigoExterno>;

  @BelongsToMany({ target: () => PedidoComplementar, pivotTable: () => PedidoComplementarProcessoAdministrativo, pivotForeignKeyToRoot: 'processo_administrativo_id', pivotForeignKeyToTarget: 'pedido_complementar_id' })
  pedidosComplementar!: ManyToManyCollection<PedidoComplementar>;

  @BelongsToMany({ target: () => Usuario, pivotTable: () => UsuarioPermitidoAcessarProcessoAdministrativoSigiloso, pivotForeignKeyToRoot: 'processo_administrativo_id', pivotForeignKeyToTarget: 'usuario_id' })
  usuarios!: ManyToManyCollection<Usuario>;

  @HasMany({ target: () => PalavraChaveProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  palavrasChaveProcessoAdministrativo!: HasManyCollection<PalavraChaveProcessoAdministrativo>;

  @HasMany({ target: () => ProcessoAdministrativoTema, foreignKey: 'processo_administrativo_id' })
  processosAdministrativoTema!: HasManyCollection<ProcessoAdministrativoTema>;

  @HasMany({ target: () => ModeloFormularioProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  modelosFormularioProcessoAdministrativo!: HasManyCollection<ModeloFormularioProcessoAdministrativo>;

  @HasMany({ target: () => RetornoProgramado, foreignKey: 'processo_administrativo_id' })
  retornosProgramado!: HasManyCollection<RetornoProgramado>;

  @HasMany({ target: () => Manifestacao, foreignKey: 'processo_administrativo_id' })
  manifestacoes!: HasManyCollection<Manifestacao>;

  @HasMany({ target: () => DocumentoRascunho, foreignKey: 'processo_administrativo_id' })
  documentosRascunho!: HasManyCollection<DocumentoRascunho>;

  @HasMany({ target: () => Carga, foreignKey: 'processo_administrativo_id' })
  cargas!: HasManyCollection<Carga>;

  @HasMany({ target: () => DocumentoAcordoContencioso, foreignKey: 'processo_contencioso_id' })
  documentosAcordoContencioso!: HasManyCollection<DocumentoAcordoContencioso>;

  @HasMany({ target: () => EstadoProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  estadosProcessoAdministrativo!: HasManyCollection<EstadoProcessoAdministrativo>;

  @HasMany({ target: () => InteressadoConsultivo, foreignKey: 'processo_administrativo_id' })
  interessadosConsultivo!: HasManyCollection<InteressadoConsultivo>;

  @HasMany({ target: () => DocumentoAnexoRascunho, foreignKey: 'processo_administrativo_id' })
  documentosAnexoRascunho!: HasManyCollection<DocumentoAnexoRascunho>;

  @BelongsTo({ target: () => ExitoSucumbencia, foreignKey: 'exito_sucumbencia_id' })
  exitoSucumbencia!: BelongsToReference<ExitoSucumbencia>;

  @BelongsTo({ target: () => Especializada, foreignKey: 'especializada_id' })
  especializada!: BelongsToReference<Especializada>;

  @BelongsTo({ target: () => Classificacao, foreignKey: 'classificacao_id' })
  classificacao!: BelongsToReference<Classificacao>;

  @BelongsTo({ target: () => Materia, foreignKey: 'materia_id' })
  materia!: BelongsToReference<Materia>;

  @BelongsTo({ target: () => Tema, foreignKey: 'tema_principal_id' })
  temaPrincipal!: BelongsToReference<Tema>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'criador' })
  dboUsuario!: BelongsToReference<Usuario>;

  @BelongsTo({ target: () => Urgencia, foreignKey: 'urgencia_id' })
  urgencia!: BelongsToReference<Urgencia>;

  @BelongsTo({ target: () => Estado, foreignKey: 'estado_id' })
  estado!: BelongsToReference<Estado>;

  @BelongsTo({ target: () => Acervo, foreignKey: 'acervo_id' })
  acervo!: BelongsToReference<Acervo>;

  @BelongsTo({ target: () => ProcessoJudicial, foreignKey: 'processo_judicial_id' })
  processoJudicial!: BelongsToReference<ProcessoJudicial>;

  @BelongsTo({ target: () => NaturezaIncidente, foreignKey: 'natureza_incidente_id' })
  naturezaIncidente!: BelongsToReference<NaturezaIncidente>;

  @BelongsTo({ target: () => TipoProcessoAdministrativo, foreignKey: 'tipo_processo_administrativo_id' })
  tipoProcessoAdministrativo!: BelongsToReference<TipoProcessoAdministrativo>;

  @HasMany({ target: () => DocumentoProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  documentosProcessoAdministrativo!: HasManyCollection<DocumentoProcessoAdministrativo>;

  @HasMany({ target: () => HistoricoDistribuicaoAcervo, foreignKey: 'processo_administrativo_id' })
  historicosDistribuicaoAcervo!: HasManyCollection<HistoricoDistribuicaoAcervo>;

  @HasMany({ target: () => HistoricoDistribuicaoEspecializada, foreignKey: 'processo_administrativo_id' })
  historicosDistribuicaoEspecializada!: HasManyCollection<HistoricoDistribuicaoEspecializada>;

  @HasMany({ target: () => Acordo, foreignKey: 'processo_administrativo_id' })
  acordos!: HasManyCollection<Acordo>;

  @HasMany({ target: () => SorteioCorreicaoProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  sorteiosCorreicaoProcessoAdministrativo!: HasManyCollection<SorteioCorreicaoProcessoAdministrativo>;

  @HasMany({ target: () => RegistroTramitacao, foreignKey: 'processo_administrativo_id' })
  registrosTramitacao!: HasManyCollection<RegistroTramitacao>;

  @HasMany({ target: () => ProcessoAdministrativoProcessoAdministrativo, foreignKey: 'processo_administrativo_associado_id' })
  processosAdministrativoProcessoAdministrativo!: HasManyCollection<ProcessoAdministrativoProcessoAdministrativo>;

  @HasMany({ target: () => Audiencia, foreignKey: 'processo_administrativo_id' })
  audiencias!: HasManyCollection<Audiencia>;

  @HasMany({ target: () => CodigoExternoProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  codigosExternoProcessoAdministrativo!: HasManyCollection<CodigoExternoProcessoAdministrativo>;

  @HasMany({ target: () => ProcessoFisicoAssociado, foreignKey: 'processo_administrativo_id' })
  processosFisicoAssociado!: HasManyCollection<ProcessoFisicoAssociado>;

  @HasMany({ target: () => Interessado, foreignKey: 'processo_administrativo_id' })
  interessados!: HasManyCollection<Interessado>;

  @HasMany({ target: () => PedidoComplementarProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  pedidosComplementarProcessoAdministrativo!: HasManyCollection<PedidoComplementarProcessoAdministrativo>;

  @HasMany({ target: () => UsuarioPermitidoAcessarProcessoAdministrativoSigiloso, foreignKey: 'processo_administrativo_id' })
  usuariosPermitidoAcessarProcessoAdministrativoSigiloso!: HasManyCollection<UsuarioPermitidoAcessarProcessoAdministrativoSigiloso>;

  @HasMany({ target: () => ValorAdicional, foreignKey: 'processo_administrativo_id' })
  valoresAdicional!: HasManyCollection<ValorAdicional>;

  @HasMany({ target: () => Solicitacao, foreignKey: 'processo_administrativo_id' })
  solicitacoes!: HasManyCollection<Solicitacao>;

}
