// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, HasManyCollection, BelongsToReference } from 'metal-orm';
import { DocumentoProcessoAdministrativo } from './DocumentoProcessoAdministrativo.js';
import { DocumentoProtocolizacao } from './DocumentoProtocolizacao.js';
import { RespostaTj } from './RespostaTj.js';
import { TipoDocumento } from './TipoDocumento.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'protocolizacao' })
export class Protocolizacao {
  /**
   * Identificador da protocolização
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * É a data em que um documento, petição ou processo é oficialmente recebido e registrado em um sistema ou instituição
   */
  @Column(col.date<Date>())
  data_protocolizacao?: Date;

  /**
   * Identificador da petição
   * @remarks References dbo.documento_processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'documento_processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  peticao_id!: number;

  /**
   * Identificador do tipo de documento
   * @remarks References dbo.tipo_documento.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tipo_documento', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_documento_id?: number;

  /**
   * Identificador do usuário
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id?: number;

  /**
   * É o ato de apresentar documentos, petições ou processos a uma instituição ou órgão público fora das suas instalações ou por meios não convencionais
   */
  @Column(col.boolean())
  protocolizacao_externa?: boolean;

  @BelongsTo({ target: () => DocumentoProcessoAdministrativo, foreignKey: 'peticao_id' })
  peticao!: BelongsToReference<DocumentoProcessoAdministrativo>;

  @BelongsTo({ target: () => TipoDocumento, foreignKey: 'tipo_documento_id' })
  tipoDocumento!: BelongsToReference<TipoDocumento>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario!: BelongsToReference<Usuario>;

  @HasMany({ target: () => DocumentoProtocolizacao, foreignKey: 'protocolizacao_id' })
  documentosProtocolizacao!: HasManyCollection<DocumentoProtocolizacao>;

  @HasMany({ target: () => RespostaTj, foreignKey: 'protocolizacao_id' })
  respostasTj!: HasManyCollection<RespostaTj>;

}
