// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { Acervo } from './Acervo.js';
import { Pessoa } from './Pessoa.js';

@Entity({ tableName: 'raiz_cnpj_acervo' })
export class RaizCnpjAcervo {
  /**
   * Identificador da raiz de cnpj
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Os oito primeiros números formam a raiz
   */
  @Column(col.notNull(col.varchar(8)))
  raiz!: string;

  /**
   * Identificador do acervo
   * @remarks References dbo.acervo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'acervo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  acervo_id!: number;

  /**
   * Identificador da matriz
   * @remarks References dbo.pessoa.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'pessoa', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  matriz_id?: number;

  /**
   * criado
   */
  @Column(col.notNull(col.datetime<Date>()))
  created!: Date;

  /**
   * Modificado
   */
  @Column(col.notNull(col.datetime<Date>()))
  modified!: Date;

  @BelongsTo({ target: () => Acervo, foreignKey: 'acervo_id' })
  acervo!: BelongsToReference<Acervo>;

  @BelongsTo({ target: () => Pessoa, foreignKey: 'matriz_id' })
  matriz!: BelongsToReference<Pessoa>;

}
