// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { AvisoPendente } from './AvisoPendente.js';
import { Comunicacao } from './Comunicacao.js';

@Entity({ tableName: 'registro_envio_comunicacao' })
export class RegistroEnvioComunicacao {
  /**
   * Identificador do registro de envio da comunicaçao
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * É a pessoa, entidade ou grupo para o qual uma mensagem, correspondência, entrega ou ação é direcionada ou destinada
   */
  @Column(col.notNull(col.text()))
  destinatario!: string;

  /**
   * Id do aviso pendente
   * @remarks References dbo.aviso_pendente.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'aviso_pendente', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  aviso_pendente_id?: number;

  /**
   * refere-se à resposta ou resultado obtido após o envio de algo
   */
  @Column(col.notNull(col.text()))
  retorno_envio!: string;

  /**
   * É a data em que algo é oficialmente transmitido
   */
  @Column(col.notNull(col.datetime<Date>()))
  data_envio!: Date;

  /**
   * Refere-se à realização bem-sucedida, Indica a obtenção de um resultado desejado
   * @defaultValue ((1))
   */
  @Column(col.defaultRaw(col.notNull(col.boolean()), '((1))'))
  sucesso!: boolean;

  /**
   * É o ato de fazer algo novamente, reproduzindo uma ação, evento ou processo que já ocorreu anteriormente
   * @defaultValue ((0))
   */
  @Column(col.defaultRaw(col.notNull(col.boolean()), '((0))'))
  repetir!: boolean;

  /**
   * Refere-se a um código exclusivo atribuído a um usuário dentro de um sistema
   */
  @Column(col.int())
  usuario_id?: number;

  /**
   * Hash que acompanha o motivo
   */
  @Column(col.text())
  hash_motivo?: string;

  /**
   * Refere-se ao identificador da comunicação
   * @remarks References dbo.comunicacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'comunicacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  comunicacao_id?: number;

  @BelongsTo({ target: () => AvisoPendente, foreignKey: 'aviso_pendente_id' })
  avisoPendente!: BelongsToReference<AvisoPendente>;

  @BelongsTo({ target: () => Comunicacao, foreignKey: 'comunicacao_id' })
  comunicacao!: BelongsToReference<Comunicacao>;

}
