// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, BelongsToReference, ManyToManyCollection } from 'metal-orm';
import { DescricaoSolicitacao } from './DescricaoSolicitacao.js';
import { DocumentoRascunho } from './DocumentoRascunho.js';
import { Estado } from './Estado.js';
import { EstadoSolicitacao } from './EstadoSolicitacao.js';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';
import { ProvidenciaJuridica } from './ProvidenciaJuridica.js';
import { ProvidenciaJuridicaSolicitacao } from './ProvidenciaJuridicaSolicitacao.js';
import { RegistroTramitacao } from './RegistroTramitacao.js';
import { TipoSolicitacao } from './TipoSolicitacao.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'solicitacao' })
export class Solicitacao {
  /**
   * Identificador da solicitação
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador da solicitação
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  solicitante_id!: number;

  /**
   * Identificador do solicitado
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  solicitado_id!: number;

  /**
   * Solicitação que teve sucesso, obteve êxito
   */
  @Column(col.notNull(col.boolean()))
  solicitacao_resolvida!: boolean;

  /**
   * Tipo solicitação id
   * @remarks References dbo.tipo_solicitacao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'tipo_solicitacao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_solicitacao_id!: number;

  /**
   * Prazo da solitação
   */
  @Column(col.date<Date>())
  prazo?: Date;

  /**
   * Refere-se ao texto em execução
   */
  @Column(col.text())
  texto_execucao_OLD?: string;

  /**
   * Identificador do processo administrativo
   * @remarks References dbo.processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_administrativo_id?: number;

  /**
   * Retornado para revisão e correção de ajustes
   */
  @Column(col.boolean())
  retornar_para_revisao?: boolean;

  /**
   * Data do retorno
   */
  @Column(col.date<Date>())
  data_retorno?: Date;

  /**
   * Identificador do estado da solicitação
   * @remarks References dbo.estado.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'estado', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  estado_id?: number;

  /**
   * Retorno do usuário
   */
  @Column(col.int())
  usuario_retorno?: number;

  /**
   * Retorno da equipe
   */
  @Column(col.int())
  equipe_retorno?: number;

  @BelongsToMany({ target: () => ProvidenciaJuridica, pivotTable: () => ProvidenciaJuridicaSolicitacao, pivotForeignKeyToRoot: 'solicitacao_id', pivotForeignKeyToTarget: 'providencia_juridica_id' })
  providenciaJuridicas!: ManyToManyCollection<ProvidenciaJuridica>;

  @HasMany({ target: () => ProvidenciaJuridicaSolicitacao, foreignKey: 'solicitacao_id' })
  providenciaJuridicaSolicitacaos!: HasManyCollection<ProvidenciaJuridicaSolicitacao>;

  @HasMany({ target: () => EstadoSolicitacao, foreignKey: 'solicitacao_id' })
  estadoSolicitacaos!: HasManyCollection<EstadoSolicitacao>;

  @HasMany({ target: () => DocumentoRascunho, foreignKey: 'solicitacao_id' })
  documentoRascunhos!: HasManyCollection<DocumentoRascunho>;

  @HasMany({ target: () => DescricaoSolicitacao, foreignKey: 'solicitacao_id' })
  descricaoSolicitacaos!: HasManyCollection<DescricaoSolicitacao>;

  @HasMany({ target: () => RegistroTramitacao, foreignKey: 'solicitacao_id' })
  registroTramitacaos!: HasManyCollection<RegistroTramitacao>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'solicitante_id' })
  solicitante!: BelongsToReference<Usuario>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'solicitado_id' })
  solicitado!: BelongsToReference<Usuario>;

  @BelongsTo({ target: () => TipoSolicitacao, foreignKey: 'tipo_solicitacao_id' })
  tipoSolicitacao!: BelongsToReference<TipoSolicitacao>;

  @BelongsTo({ target: () => ProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  processoAdministrativo!: BelongsToReference<ProcessoAdministrativo>;

  @BelongsTo({ target: () => Estado, foreignKey: 'estado_id' })
  estado!: BelongsToReference<Estado>;

}
