// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, HasManyCollection } from 'metal-orm';
import { Correicao } from './Correicao.js';
import { Especializada } from './Especializada.js';
import { SorteioCorreicaoProcessoAdministrativo } from './SorteioCorreicaoProcessoAdministrativo.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'sorteio_correicao' })
export class SorteioCorreicao {
  /**
   * Id do sorteio
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Id da correição
   * @remarks References dbo.correicao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'correicao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  correicao_id!: number;

  /**
   * Nome do sorteio
   */
  @Column(col.notNull(col.varchar(255)))
  nome!: string;

  /**
   * Id da especializada
   * @remarks References dbo.especializada.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'especializada', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  especializada_id!: number;

  /**
   * Id do usuário
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id!: number;

  /**
   * criado
   * @defaultValue (getdate())
   */
  @Column(col.defaultRaw(col.notNull(col.datetime<Date>()), '(getdate())'))
  created!: Date;

  /**
   * Modificado
   * @defaultValue (getdate())
   */
  @Column(col.defaultRaw(col.notNull(col.datetime<Date>()), '(getdate())'))
  modified!: Date;

  /**
   * parâmetros do sorteio
   */
  @Column(col.text())
  parametros_sorteio?: string;

  @BelongsTo({ target: () => Correicao, foreignKey: 'correicao_id' })
  correicao?: Correicao;

  @BelongsTo({ target: () => Especializada, foreignKey: 'especializada_id' })
  especializada?: Especializada;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario?: Usuario;

  @HasMany({ target: () => SorteioCorreicaoProcessoAdministrativo, foreignKey: 'sorteio_correicao_id' })
  sorteioCorreicaoProcessoAdministrativos!: HasManyCollection<SorteioCorreicaoProcessoAdministrativo>;

}
