// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, HasManyCollection } from 'metal-orm';
import { Manifestacao } from './Manifestacao.js';

@Entity({ tableName: 'tipo_manifestacao' })
export class TipoManifestacao {
  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  @Column(col.notNull(col.varchar(255)))
  nome!: string;

  @Column(col.varchar(3))
  codigo?: string;

  @HasMany({ target: () => Manifestacao, foreignKey: 'tipo_manifestacao_id' })
  manifestacaos!: HasManyCollection<Manifestacao>;

}
