// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, HasManyCollection, BelongsToReference } from 'metal-orm';
import { DocumentoProtocolizacao } from './DocumentoProtocolizacao.js';
import { MniTribunal } from './MniTribunal.js';
import { TipoDocumentoProvidencia } from './TipoDocumentoProvidencia.js';

@Entity({ tableName: 'tipo_documento_mni' })
export class TipoDocumentoMni {
  /**
   * Id do documento MNI
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Identificador do local do tribunal
   */
  @Column(col.varchar(10))
  id_local_tribunal?: string;

  /**
   * Id do Tribunal
   * @remarks References dbo.mni_tribunal.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'mni_tribunal', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tribunal_id?: number;

  /**
   * Descrição do documento mni
   */
  @Column(col.varchar(500))
  descricao?: string;

  /**
   * Refere-se a tipo do documento cnj
   */
  @Column(col.int())
  tipoDocumentoCNJ?: number;

  /**
   * Refere-se ao tipo de petição cnj e suas características
   */
  @Column(col.int())
  tipoPeticaoCNJ?: number;

  /**
   * Refere-se  ao processo de arquivamento de documentos ou registros que não estão mais ativos, mas que ainda são oficialmente registrados ou protocolados para fins de manutenção
   */
  @Column(col.boolean())
  inativo_protocolizacao?: boolean;

  @HasMany({ target: () => DocumentoProtocolizacao, foreignKey: 'tipo_documento_mni_id' })
  documentoProtocolizacaos!: HasManyCollection<DocumentoProtocolizacao>;

  @HasMany({ target: () => TipoDocumentoProvidencia, foreignKey: 'tipo_documento_mni_id' })
  tipoDocumentoProvidencias!: HasManyCollection<TipoDocumentoProvidencia>;

  @BelongsTo({ target: () => MniTribunal, foreignKey: 'tribunal_id' })
  tribunal!: BelongsToReference<MniTribunal>;

}
