// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, HasManyCollection } from 'metal-orm';
import { RepresentanteJudicial } from './RepresentanteJudicial.js';

@Entity({ tableName: 'tipo_representante' })
export class TipoRepresentante {
  /**
   * identificador do tipo de representante. Ex: A (advogado)
   */
  @PrimaryKey(col.notNull(col.varchar(1)))
  id!: string;

  /**
   * qual é o tipo de representante. Ex: advogado, defensoria pública
   */
  @Column(col.varchar(100))
  descricao?: string;

  @HasMany({ target: () => RepresentanteJudicial, foreignKey: 'tipo_representante_id' })
  representantesJudicial!: HasManyCollection<RepresentanteJudicial>;

}
