// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { Estado } from './Estado.js';
import { TipoAcao } from './TipoAcao.js';

@Entity({ tableName: 'tipo_acao_estado' })
export class TipoAcaoEstado {
  /**
   * Id da ação estado
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * identificador da ação
   * @remarks References dbo.tipo_acao.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'tipo_acao', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_acao_id!: number;

  /**
   * Id do estado
   * @remarks References dbo.estado.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'estado', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  estado_id!: number;

  @BelongsTo({ target: () => TipoAcao, foreignKey: 'tipo_acao_id' })
  tipoAcao?: TipoAcao;

  @BelongsTo({ target: () => Estado, foreignKey: 'estado_id' })
  estado?: Estado;

}
