// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, HasManyCollection } from 'metal-orm';
import { SorteioCorreicaoProcessoAdministrativoQuesito } from './SorteioCorreicaoProcessoAdministrativoQuesito.js';

@Entity({ tableName: 'tipo_resposta_correicao' })
export class TipoRespostaCorreicao {
  /**
   * identificador do tipo de resposta da correição
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * descrição do tipo de resposta da correição. Ex: sim, não, N/A
   */
  @Column(col.notNull(col.varchar(255)))
  descricao!: string;

  /**
   * data de criação
   * @defaultValue (getdate())
   */
  @Column(col.defaultRaw(col.notNull(col.datetime<Date>()), '(getdate())'))
  created!: Date;

  /**
   * data de modificação
   * @defaultValue (getdate())
   */
  @Column(col.defaultRaw(col.notNull(col.datetime<Date>()), '(getdate())'))
  modified!: Date;

  @HasMany({ target: () => SorteioCorreicaoProcessoAdministrativoQuesito, foreignKey: 'tipo_resposta_correicao_id' })
  sorteioCorreicaoProcessoAdministrativoQuesitos!: HasManyCollection<SorteioCorreicaoProcessoAdministrativoQuesito>;

}
