// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, HasManyCollection } from 'metal-orm';
import { ValorAdicional } from './ValorAdicional.js';

@Entity({ tableName: 'tipo_valor_adicional' })
export class TipoValorAdicional {
  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  @Column(col.unique(col.notNull(col.varchar(50))))
  descricao!: string;

  @HasMany({ target: () => ValorAdicional, foreignKey: 'tipo_valor_adicional_id' })
  valorAdicionals!: HasManyCollection<ValorAdicional>;

}
