// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, BelongsTo, BelongsToMany, HasManyCollection, BelongsToReference, ManyToManyCollection } from 'metal-orm';
import { Comunicacao } from './Comunicacao.js';
import { DispensaGenerica } from './DispensaGenerica.js';
import { Especializada } from './Especializada.js';

@Entity({ tableName: 'tipo_dispensa' })
export class TipoDispensa {
  /**
   * Id da dispensa
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Nome do tipo de dispensa
   */
  @Column(col.notNull(col.text()))
  nome!: string;

  /**
   * armazena os links ou referências para documentos associados às dispensas
   */
  @Column(col.notNull(col.text()))
  link_documento!: string;

  /**
   * Identificador da especializada
   * @remarks References dbo.especializada.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'especializada', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  especializada_id!: number;

  @BelongsToMany({ target: () => Comunicacao, pivotTable: () => DispensaGenerica, pivotForeignKeyToRoot: 'tipo_dispensa_id', pivotForeignKeyToTarget: 'comunicacao_id' })
  comunicacoes!: ManyToManyCollection<Comunicacao>;

  @BelongsTo({ target: () => Especializada, foreignKey: 'especializada_id' })
  especializada!: BelongsToReference<Especializada>;

  @HasMany({ target: () => DispensaGenerica, foreignKey: 'tipo_dispensa_id' })
  dispensasGenerica!: HasManyCollection<DispensaGenerica>;

}
