// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, HasManyCollection } from 'metal-orm';
import { Acervo } from './Acervo.js';
import { EspecializadaTema } from './EspecializadaTema.js';

@Entity({ tableName: 'tipo_acervo' })
export class TipoAcervo {
  /**
   * Id do acervo
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * Nome do tipo de acervo
   */
  @Column(col.notNull(col.varchar(63)))
  nome!: string;

  @HasMany({ target: () => EspecializadaTema, foreignKey: 'tipo_acervo_id' })
  especializadaTemas!: HasManyCollection<EspecializadaTema>;

  @HasMany({ target: () => Acervo, foreignKey: 'tipo_acervo_id' })
  acervos!: HasManyCollection<Acervo>;

}
