// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey } from 'metal-orm';

@Entity({ tableName: 'tipo_instancia' })
export class TipoInstancia {
  /**
   * Id da instancia
   */
  @PrimaryKey(col.notNull(col.varchar(4)))
  id!: string;

  /**
   * Refere-se ao nome da instância
   */
  @Column(col.text())
  nome?: string;

}
