// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, HasMany, HasManyCollection } from 'metal-orm';
import { DecisaoJudicial } from './DecisaoJudicial.js';

@Entity({ tableName: 'tipo_decisao' })
export class TipoDecisao {
  /**
   * Identificador da decisão
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * contém informações descritivas que fornecem detalhes sobre os diferentes tipos de decisões registradas no sistema
   */
  @Column(col.unique(col.varchar(100)))
  descricao?: string;

  @HasMany({ target: () => DecisaoJudicial, foreignKey: 'tipo_decisao_id' })
  decisaoJudicials!: HasManyCollection<DecisaoJudicial>;

}
