// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo } from 'metal-orm';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'usuario_permitido_acessar_processo_administrativo_sigiloso' })
export class UsuarioPermitidoAcessarProcessoAdministrativoSigiloso {
  /**
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * @remarks References dbo.processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_administrativo_id?: number;

  /**
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id?: number;

  @BelongsTo({ target: () => ProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  processoAdministrativo?: ProcessoAdministrativo;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario?: Usuario;

}
