// AUTO-GENERATED by scripts/generate-entities.mjs
// Regenerate after schema changes.
import { col, Entity, Column, PrimaryKey, BelongsTo, BelongsToReference } from 'metal-orm';
import { ProcessoAdministrativo } from './ProcessoAdministrativo.js';
import { TipoValorAdicional } from './TipoValorAdicional.js';
import { Usuario } from './Usuario.js';

@Entity({ tableName: 'valor_adicional' })
export class ValorAdicional {
  /**
   * identificador do valor adicional
   * @remarks Auto-increment identity column
   */
  @PrimaryKey(col.notNull(col.autoIncrement(col.int())))
  id!: number;

  /**
   * nome do valor adicional
   */
  @Column(col.notNull(col.text()))
  nome!: string;

  /**
   * chave estrangeira que aponta para o processo administrativo que tem esse valor adicional
   * @remarks References dbo.processo_administrativo.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.notNull(col.int()), { table: 'processo_administrativo', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  processo_administrativo_id!: number;

  /**
   * o valor de fato
   */
  @Column(col.decimal(18, 2))
  valor?: number;

  /**
   * @remarks References dbo.tipo_valor_adicional.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'tipo_valor_adicional', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  tipo_valor_adicional_id?: number;

  /**
   * @remarks References dbo.usuario.id (on delete NO ACTION, on update NO ACTION)
   */
  @Column(col.references(col.int(), { table: 'usuario', column: 'id', onDelete: 'NO ACTION', onUpdate: 'NO ACTION' }))
  usuario_id?: number;

  @Column(col.datetime<Date>())
  created?: Date;

  @BelongsTo({ target: () => ProcessoAdministrativo, foreignKey: 'processo_administrativo_id' })
  processoAdministrativo!: BelongsToReference<ProcessoAdministrativo>;

  @BelongsTo({ target: () => TipoValorAdicional, foreignKey: 'tipo_valor_adicional_id' })
  tipoValorAdicional!: BelongsToReference<TipoValorAdicional>;

  @BelongsTo({ target: () => Usuario, foreignKey: 'usuario_id' })
  usuario!: BelongsToReference<Usuario>;

}
